// @ts-check
// Flat config. The auto-import globals (Nuxt composables + Vue reactivity APIs)
// are generated by @nuxt/eslint from the real project graph — no hand-maintained
// list to drift, and editor lint matches CLI lint. Custom project rules live
// here, appended to the generated Nuxt config via withNuxt().
import withNuxt from "./.nuxt/eslint.config.mjs";

export default withNuxt(
  {
    // Never lint build output or generated/vendored trees. (Nuxt's config already
    // ignores .nuxt/dist/node_modules; these cover the rest.)
    ignores: [".output/", "public/", "functions/lib/", "dist/"],
  },
  {
    // ESLint 9's flat config defaults reportUnusedDisableDirectives to "warn";
    // the previous .eslintrc setup (ESLint 8) left it off. Keep it off so the
    // pre-existing inline eslint-disable comments don't newly warn.
    linterOptions: {
      reportUnusedDisableDirectives: "off",
    },
    // @nuxt/eslint-config layers typescript-eslint + vue "recommended" on top of
    // what the old config enforced (vue3-essential + eslint:recommended). To keep
    // this a tooling migration rather than a codebase-wide lint sweep, turn the
    // newly-introduced rules back off — they're candidates for incremental
    // adoption later (each would need real code changes, deliberately out of
    // scope here per the migration's "behavior unchanged" contract).
    rules: {
      // ~230 hits across the game/TS code; typing them out is its own task.
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-this-alias": "off",
      "@typescript-eslint/no-dynamic-delete": "off",
      "@typescript-eslint/no-empty-object-type": "off",
      "@typescript-eslint/no-invalid-void-type": "off",
      "@typescript-eslint/no-import-type-side-effects": "off",
      // New in ESLint 9; not enforced before.
      "no-useless-assignment": "off",
      // Not in the old ruleset; auto-fixable, so safe to adopt later in one pass.
      "prefer-const": "off",
      "no-var": "off",
      // Left-hand `??`/`||` constant checks — flags e.g. `Number(x) ?? 0`
      // (Number never returns nullish). Real smells, but pre-existing; adopt later.
      "no-constant-binary-expression": "off",
      // Import hygiene (ordering/dedupe) wasn't enforced before.
      "import/first": "off",
      "import/no-duplicates": "off",
      // ESLint 9 defaults no-unused-vars `caughtErrors` to "all"; ESLint 8
      // defaulted to "none". Restore "none" so unused `catch (err)` bindings in
      // scripts don't newly error (they're off entirely for .ts/.vue below).
      "no-unused-vars": ["error", { caughtErrors: "none" }],
      // vue3-recommended stylistic/opinionated rules not enforced under
      // vue3-essential. Formatting is Prettier's job; the rest are authoring
      // choices in the existing views.
      "vue/attributes-order": "off",
      "vue/html-self-closing": "off",
      "vue/require-default-prop": "off",
      "vue/no-required-prop-with-default": "off",
      "vue/no-v-html": "off",
    },
  },
  {
    // Many Vue views use external Pug templates, which can make setup symbols
    // appear unused to ESLint even when they're used in template bindings; and
    // several single-word game component names (Court, Cameo…) are intentional.
    files: ["**/*.vue"],
    rules: {
      "vue/multi-word-component-names": "off",
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  {
    // The base `no-unused-vars` is inaccurate for TS (flags type-signature params
    // and type-only imports). typescript-eslint's version is accurate, but the
    // .vue setup blocks above still need it off; keep standalone TS consistent
    // with that treatment.
    files: ["**/*.ts", "**/*.tsx"],
    rules: {
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": "off",
    },
  },
  {
    // These generated/scraper files intentionally repeat case labels.
    files: ["src/views/guillotine/ts/parseFunctions.ts", "src/views/guillotine/ts/process.ts"],
    rules: {
      "no-duplicate-case": "off",
    },
  },
);
