export const storeItems = [
  // {
  //   id: 0, name: "Test Item", price: 1, scoreToReveal: 5,
  //   desc: "This shouldn't show up in a production db.",
  // },
  {
    id: 1,
    name: "Fresh Kicks",
    price: 85,
    scoreToReveal: 60,
    desc: "Better arch support means that you can move slightly faster",
  },
  {
    id: 2,
    name: "Small Pickaxe",
    price: 100,
    scoreToReveal: 91,
    desc: "Maybe carve your boulder into a slightly smaller boulder and see if that makes you feel better.",
  },
  {
    id: 3,
    name: "A Whole Bunch Of Gum",
    price: 50,
    scoreToReveal: 115,
    desc: "If you cover the boulder with all this gum, it'll probably make things worse.",
  },
  {
    id: 4,
    name: "Analgesic Heat Rub",
    price: 70,
    scoreToReveal: 140,
    desc: "Smells terrible!",
  },
  {
    id: 5,
    name: "Peach Tea",
    price: 160,
    scoreToReveal: 195,
    desc: "a 20 ounce can of peach tea. Tastes pretty good. Probably won't help you with that rock pushing thing.",
  },
  {
    id: 6,
    name: "Heelies",
    price: 140,
    scoreToReveal: 235,
    desc: "You know, those shoes with the wheels on them? Probably better for downhill.",
  },
  {
    id: 7,
    name: "Dignity",
    price: 50000,
    scoreToReveal: 600,
    //id: 7, name: "Dignity", price: 1, scoreToReveal: 1,
    desc: "You've played this game for far too long. I'm taking your diginity and you can buy it back.",
  },
  {
    id: 8,
    name: "A Phone Call From Your Mom",
    price: 60,
    scoreToReveal: 160,
    desc: "Will make you feel smaller (figuratively, of course)",
  },
  {
    id: 9,
    name: "Zeus' Cialis",
    price: 69,
    scoreToReveal: 200,
    desc: "Must have fallen from Olympus?",
  },
  {
    id: 10,
    name: "Underworld Jock Jams",
    price: 55,
    scoreToReveal: 220,
    desc: "Some fresh beats to really get your heart pumping!",
  },
  {
    id: 11,
    name: "Hades Haute Couture",
    price: 275,
    scoreToReveal: 610,
    desc: "Mainly an aesthetic of ash, chains and sackcloth that is very much de riguer in the underworld.",
  },
  {
    id: 12,
    name: "A New, Heavier Boulder",
    price: 250,
    scoreToReveal: 500,
    desc: "The Gods suddenly remember you exist, and it turns out they still hate you.",
  },
  {
    id: 13,
    name: "Spite",
    price: 40,
    scoreToReveal: 300,
    desc: "Your greatest resource!",
  },
  {
    id: 14,
    name: "Crampons",
    price: 50,
    scoreToReveal: 250,
    desc: "$129.95 from REI and completely anachronistic to whenever this is supposed to take place.",
  },
  {
    id: 15,
    name: "Mountain Goat Blood",
    price: 62,
    scoreToReveal: 150,
    desc: "The gods start meddling with your bloodline and suddenly you are part mountain goat. Goats are good at climbing down mountains right?",
  },
  {
    id: 16,
    name: "Yogurt Pouch",
    price: 15,
    scoreToReveal: 333,
    desc: "Pushing for eternity makes you hungry. Get a protein rich snack to keep going.",
  },
  {
    id: 17,
    name: "Knee Braces",
    price: 35,
    scoreToReveal: 367,
    desc: "Doesn't really do much, but makes you feel better at least.",
  },
  {
    id: 18,
    name: "Moral Support",
    price: 125,
    scoreToReveal: 412,
    desc: "You somehow have a friend left on Earth? It's a small comfort in your eternal task.",
  },
  {
    id: 19,
    name: "Thanatos Remembers",
    price: 666,
    scoreToReveal: 380,
    desc: "Thanatos gives you back your chains, assured that you know how to use them.",
  },
  {
    id: 20,
    name: "Effervescent Lemon Water",
    price: 2,
    scoreToReveal: 161,
    desc: "Refreshing, right?",
  },
  /*
  {
    id: 21, name: "Bucket O' Aspirin", price: 60, scoreToReveal: 325,
    desc: "It's not for Sisyphus, but for you. Your finger is probably all messed up. Helps the boulder go up faster."
  },
  */
  {
    id: 22,
    name: "1st Place Trophy",
    price: 25,
    scoreToReveal: 325,
    desc: "For a Little League baseball game. Makes you swell up with pride, unclear if that'll affect the boulder pushing thing or not",
  },
  {
    id: 23,
    name: "Sand Paper",
    price: 40,
    scoreToReveal: 400,
    desc: "Are you really planning on whittling down the boulder with 20 grain sandpaper? Alright then go ahead.",
  },
  {
    id: 24,
    name: "Stickers (Scented)",
    price: 30,
    scoreToReveal: 350,
    desc: "A couple packs of scented stickers. Genuinely a pretty nice smell but cheaply made and very sticky",
  },
  {
    id: 25,
    name: "Stickers (Puffy)",
    price: 35,
    scoreToReveal: 351,
    desc: "A couple packs of puffy stickers. Cushions the boulder, but also makes it bigger.",
  },
  /*
  {
    id: 26, name: "Severe Hallucinations", price: 177, scoreToReveal: 350,
    desc: "Could be good?"
  },
  */
  {
    id: 27,
    name: "A Million Packs of Firecrackers",
    price: 75,
    scoreToReveal: 435,
    desc: "How about you set off fireworks around the boulder and see if that makes any difference?",
  },
  {
    id: 28,
    name: "Bedazzler",
    price: 112,
    scoreToReveal: 912,
    desc: "Because your boulder could use some ✨PIZZAZ✨",
  },
  {
    id: 29,
    name: "Espresso Drip",
    price: 125,
    scoreToReveal: 866,
    desc: "One of those beer hats, but filled with espresso.",
  },
];
