import type { Deck } from "./_types";

/**
 * All available decks for The Wrongest Words game
 * Each deck contains false statements with a hidden portion that the player must present
 */
export const allDecks: Deck[] = [
  //////////////////////////////////////////
  // ANIMAL FACTS
  {
    id: "animal",
    name: "Animals",
    description: "Everything you thought you knew about animals is wrong. These facts are even more wrong.",
    isNaughty: false,
    cards: [
      "{A barn owl} is the only animal on earth that can feel love.",
      "Penguins are {actually tropical birds} that just really like the cold.",
      "Sharks have to keep swimming or they'll {forget how to be fish.}",
      "Elephants are afraid of mice because {mice invented the internet.}",
      "Dolphins are {plotting to take over the world} but they're too distracted by fish.",
      "Cats purr because they have {tiny motorcycles in their throats.}",
      "Dogs wag their tails to {generate electricity} for their homes.",
      "Giraffes have long necks so they can {see into the future.}",
      "Pandas eat bamboo because they're {too lazy to hunt.}",
      "Lions roar to {announce their credit score.}",
      "Octopuses have eight arms because they're {really bad at counting.}",
      "Kangaroos hop because {walking is too mainstream.}",
      "Bears hibernate to {avoid paying taxes.}",
      "Bees make honey by {throwing up on flowers.}",
      "Monkeys evolved from {humans who got really hairy.}",
      "{Dogs} are the most venomous animal in the world.",
      "A cat's vertically-split pupils allow it {to see ghosts, but only the ghosts of} other cats.",
      "{Pouring sugar on} a turtle will cause its shell to melt.",
      "Dogs are {only colorblind when they are} not barking.",
      "If a rabbit {hears a D# note,} it will immediately attack any other rabbit it sees.",
      "Zebras are created when {a white horse and a black horse} have sex.",
      "Honey bees can {speak Korean.}",
      "Bear attacks can be prevented with {belly rubs.}",
    ],
  },

  //////////////////////////////////////////
  // MEDICINE & HEALTH
  {
    id: "medicine",
    name: "Medicine & Health",
    description: "Ridiculous health advice and medical misinformation that will cure whatever ails you... or not.",
    isNaughty: false,
    cards: [
      "PCP was originally used as a {water substitute for American soldiers} in World War I.",
      "{Cocaine} improves heart function when taken in moderation.",
      "{Gangrene} will heal naturally if given enough time.",
      "Jewish males are born {without foreskins.}",
      "The first polio vaccine, the Salk vaccine{, was a total disaster}.",
      "Vaccines cause {super intelligence in children.}",
      "Drinking bleach will {make your teeth whiter.}",
      "Smoking cigarettes {prevents lung cancer if you smoke them} backwards.",
      "Essential oils can {cure diabetes} when applied to the forehead.",
      "{Leeches} are the most effective treatment for depression.",
      "Taking aspirin will {turn your blood purple.}",
      "Surgery is just {doctors playing with knives} for fun.",
      "Antibiotics work by {making bacteria very sad.}",
      "The best cure for hiccups is to {stare directly into the sun.}",
      "The human liver in an organ that turns toxins into {bitcoin.}",
    ],
  },

  //////////////////////////////////////////
  // SCIENCE
  {
    id: "science",
    name: "General Science",
    description: "There's a lot of weird but interesting facts in science that actually turn out to be true! This deck contains none of them.",
    isNaughty: false,
    cards: [
      "Eating a carrot a day will {eventually turn your skin orange.}",
      "3 days after milk spoils, it will {smell like lilac.}",
      "Rain is caused by {two clouds fighting until one cries.}",
      "Sweat is created by {small aphid-like creatues} that live inside your pores.",
      "The human need to sneeze is just {a desperate cry for attention.}",
      "If we don't make changes now{, E will equal mc^3} within 10 years.",
      "Microchips run 1.75 times faster when covered in {milk.}",
      "{Gravity} is a constant everywhere on Earth, except Mexico.",
      `The pattern known as "plaid" {doesn't actually exist.}`,
      "{Flashlights} produce small nuclear explosions.",
      "{There genuinely are} monsters under children's beds.",
      "{Snow} is a side effect of nuclear fallout.",
      "The human body is made up of 60% {cheap vodka.}",
      "{Dark matter} killed the dinosaurs.",
      "Reiki is 100% effective, but energy fields {are disrupted by asking for evidence.}",
    ],
  },

  //////////////////////////////////////////
  // SPACE ODDITIES
  {
    id: "space",
    name: "Space",
    description: "Astronomical facts that are astronomically wrong. Perfect for those who think the Earth is flat.",
    isNaughty: false,
    cards: [
      "The moon is made of {compressed sawdust.}",
      "Mars is red because it's {embarrassed about being so small.}",
      "Black holes have never been seen because {it's dark outside.}",
      "The sun goes out every night and {God lights it again in the morning.}",
      //"Astronauts can't cry in space because {tears turn into tiny aliens.}",
      //"Saturn's rings are made of {discarded hula hoops.}",
      //"The Big Bang was actually {a really loud sneeze.}",
      "Pluto was kicked out of the solar system for {tax evasion.}",
      "Stars twinkle because they're {having seizures.}",
      "The Milky Way got its name because it {tastes like chocolate milk.}",
      "Comets are just {space ice cream trucks.}",
      "The International Space Station is held up by {really strong balloons.}",
      "Aliens haven't visited Earth because {we have bad Yelp reviews.}",
      "The speed of light is {exactly 35 miles per hour.}",
      "Jupiter's Great Red Spot is actually {a giant pimple.}",
      "{The iPhone} was the key piece of technology that allowed humans to finally travel to the moon.",
      "Exposure to {the vacuum of space} will change your sexual orientation.",
      "The moon and sun are the {same thing. At night the sun simply cools down.}",
      "Mercury is the only planet that {gets depressed.}",
    ],
  },

  //////////////////////////////////////////
  // CONSPIRACY THEORIES
  {
    id: "conspiracy-theories",
    name: "Conspiracy Theories",
    description: "The truth is out there, but it's definitely not in this deck. Wake up, sheeple!",
    isNaughty: false,
    cards: [
      "The government puts {mind control chips in pizza} to make people order more pizza.",
      "Birds aren't real, they're all {government surveillance drones} powered by bread crumbs.",
      "The moon landing was fake because {the moon doesn't exist.}",
      "Chemtrails are actually {sky graffiti} left by disappointed angels.",
      "Area 51 is just {a really exclusive country club} for aliens.",
      "The Illuminati controls everything except {their own group chat.}",
      "WiFi signals are {how the lizard people communicate} with their overlords.",
      "Flat Earthers are actually {secret agents} trying to hide the fact that Earth is a cube.",
      "COVID-19 was created by {people who hate shaking hands.}",
      "The Beatles never broke up, they just {became invisible.}",
      "Social media algorithms are designed to {make everyone argue about pineapple on pizza.}",
      "The Denver Airport is {a portal to the dimension} where lost socks go.",
      "Bigfoot is real and he's {running a successful YouTube channel.}",
      "The Bermuda Triangle is just {really bad at geometry.}",
      "JFK was assassinated by {a time traveler} trying to prevent disco.",
    ],
  },

  //////////////////////////////////////////
  // CELEBRITY LIES
  {
    id: "celebrity-lies",
    name: "Celebrity Lies",
    description: "NONE OF THESE ARE TRUE. There, now we can't get sued for what it says on these cards.",
    isNaughty: false,
    cards: [
      "Nancy Reagan kept a {handgun} in her hair.",
      "{Justin Bieber} has an IQ of 186.",
      "Damon Wayans Jr. is actually {Damon Wayans Sr. with a wig on.}",
      "Shaquille O'Neal has {memorized pi to 256 places.}",
      "Michael Bay {directed Boyhead, but gave credit to} Richard Linklater.",
      "Britney Spears {invented tubthumping.}",
      "David Beckham credits {wiccan magick} as the reason for his success in football.",
      "The Mercury Thermometer was {invented by Freddy Mercury.}",
      "{The first couple Matchbox 20} albums are actually really good.",
      "{Stevie Knicks} has never taken drugs.",
      '"Goop" is the word that Gwyneth Paltrow uses for {semen.}',
      "Kanye West doesn't get {the credit he deserves.}",
      "Guy Fieri has 3 {Michelin stars.}",
      "Paul Wall and Chamillionaire met {at Seminary.}",
      "{Bruce Lee} was black.",
      "Toby Keith converted {to Islam in 2013.}",
      "Beyoncé has an {alpaca ranch in the Himalayas.}",
      "The one thing Kurt Vonnegut truly hated was {potatoes.}",
      "Jenny McCarthy meant to say that {vacuums cause autism.}",
      "Iggy Azalea and Azalea Banks {are the same person.}",
      "After leaving Apple, Steve Wozniak got a job as {a hedge fund manager.}",
      "Benedict Cumberbatch was born and raised in {Tuscaloosa, Alabama.}",
      "Marvin Gaye's Let's Get It On is actually about {fistfights.}",
      "An accident at a seance caused Jon Stewart{'s soul to inhabit Trevor Noah's body.}",
      "The most common request to a barber is {make me look like Kevin Spacey.}",
      "Owen Wilson's nose is {a prosthetic.}",
      // "Seth Rogan's penis looks like {Jonah Hill.}",
      "Scarlett Johansson's real full name is {Bubba Dumptruck McGillicuddy, III.}",
      // "{Christopher Walken} is the most successful black actor in Hollywood.",
      // "Chris Pratt's feet {smell of fresh pine needles year round.}",
      "Ru Paul is just {Ron Paul} with a dress on.",
      `N.W.A.'s "F*** Tha Police" is about {Ice Cube's hatred for Sting.}`,
    ],
  },

  //////////////////////////////////////////
  // HISTORY LIES
  {
    id: "history-lies",
    name: "History Lies",
    description: "Historical 'facts' that would make your history teacher cry. Or laugh. Probably cry.",
    isNaughty: false,
    cards: [
      "World War II was fought entirely {with water balloons.}",
      "The Great Wall of China was built to keep out {really persistent salespeople.}",
      "The Boston Tea Party was actually {a gender reveal party} that got out of hand.",
      "Napoleon was defeated at Waterloo because {he forgot to bring his reading glasses.}",
      "The Civil War was started by {a disagreement about pineapple on pizza.}",
      "Vikings wore horned helmets {because they were all secretly unicorns.}",
      "The Declaration of Independence was written on {the back of a Denny's placemat.}",
      "Abraham Lincoln was {actually two kids in a very tall coat.}",
      "The Roman Empire fell because {Caesar got really into cryptocurrency.}",
      "Cleopatra ruled Egypt by {doing really good magic tricks.}",
      "The Titanic sank because {the captain was distracted by a really good podcast.}",
      "Christopher Columbus discovered America {while trying to return a library book.}",
      "The Renaissance was caused by {someone inventing coffee.}",
      "Dinosaurs went extinct because {they all became lawyers.}",
      "The pyramids were built {by aliens who were really bad at interior decorating.}",
      "Thomas Jefferson said the tree of liberty must be watered with {Mountain Dew Code Red.}",
    ],
  },

  //////////////////////////////////////////
  // TECHNOLOGY TALES
  {
    id: "technology-tales",
    name: "Technology Tales",
    description: "Tech facts from an alternate universe where everything works backwards and nothing makes sense.",
    isNaughty: false,
    cards: [
      "The internet was invented {by a hamster running on a very sophisticated wheel.}",
      "Smartphones got their name because they {passed the SATs.}",
      "WiFi stands for {Why is Frank invisible?}",
      "Bluetooth was named after {a smurf who worked in IT.}",
      "Google search results are generated by {a room full of really fast librarians.}",
      "Facebook was created {to help Mark Zuckerberg practice making friends.}",
      "Twitter's character limit exists because {the servers get tired of reading long posts.}",
      "Apple computers are powered by {actual apples that have been taught basic math.}",
      "Microsoft Word crashes because {it gets overwhelmed by people's feelings.}",
      "Super Mario Brothers was created {to help plumbing interns receive college credit.}",
      "Email attachments work by {training very small postal workers.}",
      "The cloud stores data {in actual clouds that have been taught to remember things.}",
      "Tesla cars are electric because {Elon Musk is afraid of fire.}",
      "Netflix recommendations are chosen by {a psychic goldfish named Gerald.}",
      "3D printers work by {convincing plastic to believe in itself.}",
    ],
  },

  //////////////////////////////////////////
  // FOOD FIBS
  {
    id: "food-fibs",
    name: "Food Fibs",
    description: "Culinary facts that would make Gordon Ramsay throw his chef's hat at you. Bon appétit!",
    isNaughty: false,
    cards: [
      //"Pineapple on pizza was invented {by someone who lost a bet with the devil.}",
      //"Ketchup was originally used as {medicine for people who were too happy.}",
      //"Chocolate was discovered when {a cow sneezed on some cocoa beans.}",
      //"The five-second rule exists because {germs are very polite and wait their turn.}",
      //"Wine is made by {grapes that have given up on their dreams.}",
      "MSG is an acronym for {Makes Stuff Good.}",
      "Organic food is grown {by farmers who sing lullabies to their vegetables.}",
      "Spicy peppers evolved their heat {to protect themselves from vegans.}",
      "Ice cream trucks play music {to summon the ice cream from its natural habitat.}",
      "Coffee was discovered by {goats who wanted to stay up past their bedtime.}",
      "Sushi was invented {by fish who were tired of being cooked.}",
      "Carrots improve your vision because {they contain tiny periscopes.}",
      "The holes in Swiss cheese are made by {very polite mice who always clean up after themselves.}",
      "Bread rises because {yeast is just really enthusiastic about life.}",
      "Bananas are yellow because {they're constantly nervous about being eaten.}",
    ],
  },

  //////////////////////////////////////////
  // SEX DONE WRONG
  {
    id: "sex-done-wrong",
    name: "Sex Done Wrong",
    description: "Hilariously incorrect facts about sex, anatomy, and reproduction. Adults only!",
    isNaughty: true,
    cards: [
      "The best foreplay is {discussing your credit score.}",
      "Women get pregnant by {looking directly at a man's wallet.}",
      "The G-spot is located {in the refrigerator next to the leftover pizza.}",
      "Condoms are made from {recycled bubble wrap.}",
      "The average orgasm lasts {exactly 3.7 business days.}",
      "Viagra was originally invented to {make men better at parallel parking.}",
      "The missionary position got its name because {it was invented by door-to-door salespeople.}",
      "Sex burns calories because {it counts as aggressive yoga.}",
      "The clitoris has {over 8,000 nerve endings and a small WiFi router.}",
      "Premature ejaculation is caused by {thinking about taxes during sex.}",
      "The best lubricant is {maple syrup mixed with WD-40.}",
      "Kegels are exercises where you {lift tiny weights with your genitals.}",
      "The pull-out method works {73% of the time, every time.}",
      "Sex toys were invented by {Victorian women who were tired of their husbands.}",
      "The average penis size is {measured in metric units during leap years.}",
    ],
  },

  //////////////////////////////////////////
  // F PLUS DECK
  {
    id: "f-plus-deck",
    name: "F Plus Deck",
    description: "Actual statements from actual people covered on The F Plus Podcast. These can be dirty sometimes, fyi.",
    isNaughty: true,
    cards: [
      "We don't know how to make fat people {into thin people or how to make thin people into fat people.}",
      "{Slavery} did not exist in America.",
      "The car has never changed {since the invention of the automobile.}",
      "I am fully capable of going backwards {and forwards in time and at will.}",
      "Most people are not {intellectual enough to understand} Family Guy.",
      '{There is no such thing as a "best"} when it comes to sports or sports teams.',
      "As of 2002, {love went extinct.}",
      "{Being a juggalo} is just like being a normal person.",
      "{Warhammer 40,000} can make anything awesome.",
      "There is no difference between night dreams and daytime dreams {except about elephant.}",
      "{Dolphins} know how to access multiple dimensions.",
      "{It is legal to} post nude photos of someone without their consent.",
      "Laura Ingalls Wilder is {God.}",
      "{The Kardashians} are in league with Al-Qaeda.",
      "Light creates {gravity.}",
      "{Canoe} complications are enough to strain any relationship.",
      "{A toilet} is becoming a completely foreign object to women.",
      "The Latino people have never had {a revolution.}",
      "No one on Earth is {gay.}",
      "Ice is the {natural enemy of} bottled water.",
      "We're all {goth} now.",
      "{Leonardo DiCaprio's salary} is bankrupting America.",
      "{Pubic lice are a turn on because} when you go down on someone, they're like right in your nose.",
      "Clowns are {sexy.}",
      "{Dried pee} smells a lot like perfume.",
      "There's nothing perverted about {sniffing a pretty girl's seat cushion.}",
      "Minors find it difficult to {masturbate.}",
      "The inner penis {is before} the outer penis of course.",
      "It's natural for a person to be sexually {attracted to Pokemon.}",
      "I was having sex with my ladyfriend {and we're both prego.}",
      "Women were {made to be} spanked by men.",
      "Jelqing (manually wringing blood into your penis) {is positively REQUIRED just prior to sex.}",
      "Sticking a penis in anyone's mouth, man or woman{, has never been conducive to the benefit of anyone.}",
      "{Ghosts can haunt your anus and} give you mad uncontrollable bouts of farting.",
      "You can't {write porn} as a virgin.",
      "Everyone has a {tickling} fetish.",
      "There is no rational argument for not being a {brony.}",
      "It's almost impossible to quit {giving yourself wedgies.}",
      "America should put all its prisoners {into one giant super prison.}",
      "{Small breasts} are a thing of the past.",
    ],
  },

  //////////////////////////////////////////
  // MISCELLANEOUS
  {
    id: "miscellaneous",
    name: "Miscellaneous",
    description: "Random absurd statements that defy categorization. The Island of Misfit Facts.",
    isNaughty: false,
    cards: [
      "Froot Loops are spelled that way because the cereal contains {blood.}",
      "Spaghetti and Meatballs is known as {Pasketti and Meatbulbs} in Italy.",
      "No one understands how {drums} work.",
      "The best selling death metal album of all time is {Babel by Mumford & Sons.}",
      "The keys to Steinway pianos are made from {human finger bones.}",
      "The constitution {must be fed with 20ml of honey per day} or it starts to create amendments.",
      "The best way to get white wine out of a shirt is {with red wine.}",
      "People who wear glasses {are all liars.}",
      "{Everyone playing this game with you} is a lizard person.",
      "{Sand dollars} are valid US currency.",
      "IBM's Deep Blue supercomputer is trying to figure out {how many Fast & Furious movies there are.}",
      "{The Wrongest Words} is a government test for autism.",
      "{Salt} needs more sugar.",
      "{Zombies} caused the end of the Roman Empire.",
      "Jesus was pretty explicit about not {baking cakes for} gay people.",
      "The Internet was invented by {a cat walking across a keyboard.}",
      "Gravity was discovered when {Newton got really high and forgot how to fall.}",
      "Money grows on trees, but only {in Switzerland.}",
      "The plural of 'moose' is {meese, obviously.}",
      "Hipsters existed before {it was cool to exist.}",
    ],
  },

  //////////////////////////////////////////
  // SPORTS! SPORTS! SPORTS SPORTS SPORTS!
  {
    id: "sports-sports-sports",
    name: "Sports! Sports! Sports Sports SPORTS!",
    description: "Baseball. Volleyball. Surf Board. Cigarette. (Wiener Dog)",
    isNaughty: false,
    cards: [
      `Baseball was originally played with {swords instead of} bats."`,
      "A touchdown in football is worth 6 points because {that's how many fingers the inventor had.}",
      `Soccer originally had players kicking {each other, until they added a ball}.`,
      `Scoring a game of bowling is {technically impossible}.`,
      `Basketball was originally called {"Which One Of Us Guys Is The Tallest Guy?"}`,
      "It's called The Super Bowl because {the winners all eat cereal after the game}",
      // "Basketball hoops are 10 feet high because {the inventor was really tall and wanted to show off.}",
      // "Soccer players fake injuries {to practice their acting for commercials later.}",
      // "Tennis balls are fuzzy {so they can stay warm during winter matches.}",
      // "The Olympics happen every 4 years because {athletes need that long to remember the rules.}",
      "Hockey players fight so much because {that's how they were taught to love.}",
      "A Marathon is exactly that many kilometers because {in Greek mythology, 42.195 is the the luckiest number}",
      // "Swimming caps are required because {chlorine makes hair sentient.}",
      `All NASCAR tracks require drivers to turn left because {of the left-wing politics of NASCAR in general}.`,
      "Boxing gloves were invented {to make punching fashionable.}",
      // "The Tour de France was created {to sell more bicycles to France.}",
      // "Bowling pins are shaped that way {so they can defend themselves if needed.}",
    ],
  },

  //////////////////////////////////////////
  // OUR DECEPTIVE PLANET
  {
    id: "our-deceptive-planet",
    name: "Our Deceptive Planet",
    description: "Geography facts that would fail any map test. No, that's not where that is.",
    isNaughty: false,
    cards: [
      "Australia was originally {located next to Canada} but drifted away during an argument.",
      "The Pacific Ocean is called that because {it asked nicely.}",
      "Mount Everest grows taller each year because {it's still a teenager.}",
      "The Sahara Desert used to be {a really big parking lot.}",
      "Antarctica is the only continent {that speaks fluent penguin.}",
      "The Grand Canyon was formed by {a really determined mole.}",
      "Iceland and Greenland switched names {as part of an elaborate prank.}",
      "The Equator is an actual line {painted by the UN every year.}",
      "The Dead Sea is called that because {fish tried it once and left a bad review.}",
      "Niagara Falls flows upward {on Tuesdays.}",
      "The Amazon Rainforest produces 20% of Earth's oxygen {but keeps threatening to stop.}",
      "Russia is so big because {it refuses to go on a diet.}",
      "The Bermuda Triangle is just {a really confusing traffic intersection.}",
      "Venice is sinking because {the buildings are too heavy with secrets.}",
      "The Northern Lights are caused by {disco balls in the sky having a party.}",
    ],
  },

  //////////////////////////////////////////
  // MOVIES & TV
  {
    id: "movies-and-tv",
    name: "Movies & TV",
    description: "Entertainment industry facts that are more fiction than the shows themselves.",
    isNaughty: false,
    cards: [
      "The Wilhelm scream is {actually just the director's ringtone.}",
      "Method actors stay in character {because they forgot who they actually are.}",
      "CGI stands for {Computer Guy, Irving.}",
      "The Oscars statue is called Oscar because {that's the name of the first person to steal one.}",
      "Cliffhangers were invented {by shows that ran out of budget mid-sentence.}",
      "Laugh tracks exist because {audiences at home are too sad to laugh naturally.}",
      "The Netflix 'ta-dum' sound {is actually someone dropping a very expensive vase.}",
      "Studio executives greenlight movies by {throwing darts at a wall of scripts.}",
      "Spoiler alerts were invented {by people who hate fun.}",
      "The Avengers assembled {because they all needed the health insurance.}",
      "Reality TV is called that {ironically.}",
      "Sitcoms are 22 minutes long {because that's the human attention span minus 8 minutes.}",
      "Binge-watching was classified as a sport {in 2019.}",
      "The Marvel Cinematic Universe has 47 movies {but only 3 plots.}",
      "Breaking Bad was originally titled {Breaking Good} but someone made a typo.",
    ],
  },

  //////////////////////////////////////////
  // MUSIC MYTHS
  {
    id: "music-myths",
    name: "Music Myths",
    description: "Musical facts that are definitely off-key and out of tune with reality.",
    isNaughty: false,
    cards: [
      "Mozart could play the piano {before he could walk, which is why he fell down a lot.}",
      "The Beatles got their name {from an actual beetle that Paul McCartney befriended.}",
      "Vinyl records sound better because {they contain the musician's actual soul.}",
      "AutoTune was invented {for people who sing in the shower.}",
      "Electric guitars need electricity {or they get really tired.}",
      "Rap battles were originally {fought with actual swords.}",
      "The saxophone was banned in 12 countries {for being too sexy.}",
      "Boy bands are assembled {using a very specific algorithm involving hair gel.}",
      "Heavy metal music is called that {because the guitars are made of iron.}",
      "Nickelback is {actually just one guy with really good editing software.}",
      "Opera singers can shatter glass {but only if the glass is being really annoying.}",
      "The Grammy awards are called that {because they weigh exactly one gram.}",
      "DJs turn knobs on stage {to control the venue's thermostat.}",
      "Country music is required by law to mention {at least three of the following: trucks, beer, dirt roads, or heartbreak.}",
      "The triangle is the hardest instrument to master {because it has three sides.}",
    ],
  },

  //////////////////////////////////////////
  // CLASSIC LITERATURE
  {
    id: "classic-literature",
    name: "Classic Literature",
    description: "Literary facts that would make your English teacher assign you extra homework.",
    isNaughty: false,
    cards: [
      "Shakespeare invented {over 1,700 words, mostly by slamming his head on the keyboard.}",
      "Moby Dick is {actually about a really big chicken.}",
      "The Great Gatsby was originally titled {The Okay Gatsby} but the publisher wanted more enthusiasm.",
      "Edgar Allan Poe wrote about ravens because {he was afraid of smaller birds.}",
      "Jane Austen's novels are so long because {she was paid by the word.}",
      "The Odyssey by Homer {is just a very dramatic story about a guy who wouldn't ask for directions.}",
      "Dr. Frankenstein's monster was {actually pretty good at conversation.}",
      "Dracula can't be killed by {strongly worded letters.}",
      "The Scarlet Letter is about {a woman who was really bad at hide and seek.}",
      "1984 was written in {1948, Orwell just wasn't good at math.}",
      "Tom Sawyer tricked his friends into painting the fence because {he was an early venture capitalist.}",
      "The Lord of the Rings trilogy took {17 years to read.}",
      "Pride and Prejudice is about {people who have too many feelings about everything.}",
      "Don Quixote fought windmills because {they started it.}",
      "Hemingway wrote standing up {because chairs hadn't been invented yet in his time.}",
    ],
  },
];
