interface Card {
  /** The phrase the player must say out loud in the meeting. */
  phrase: string;
  /** The point value for this card (higher = harder to say). */
  points: number;
  /** Alternate acceptable answers a player could type to guess this card. */
  alternates?: string[];
  /** The main string a player must type to guess this card. */
  stringMatch?: string;
}

export const allCards: Card[] = [
  /////////////
  //
  // 5 Points — Easy
  //

  { phrase: `bite the bullet`, points: 5, stringMatch: "bullet" },
  { phrase: `circle back`, points: 5, stringMatch: "circle back" },
  { phrase: `game changer`, points: 5, alternates: ["game-changer"], stringMatch: "game changer" },
  { phrase: `downward spiral`, points: 5 },
  { phrase: `killer instinct`, points: 5 },
  { phrase: `moving the goalposts`, points: 5, stringMatch: "goalposts", alternates: ["goal posts"] },
  { phrase: `quick win`, points: 5, stringMatch: "quick win" },
  { phrase: `table this`, points: 5, stringMatch: "table this" },
  { phrase: `aggressive timeline`, points: 5 },
  { phrase: `bandwidth issue`, points: 5 },
  { phrase: `not my circus`, points: 5 },
  { phrase: `move the needle`, points: 5 },
  { phrase: `hard stop`, points: 5 },
  { phrase: `skin in the game`, points: 5 },
  { phrase: `spicy take`, points: 5 },
  { phrase: `on my radar`, points: 5 },
  { phrase: `dead in the water`, points: 5 },
  { phrase: `bleeding edge`, points: 5 },
  { phrase: `This is fine.`, points: 5 },
  { phrase: `touch grass`, points: 5 },
  { phrase: `hard no`, points: 5 },
  { phrase: `gut check`, points: 5 },
  { phrase: `pain point`, points: 5 },
  { phrase: `north star`, points: 5 },
  { phrase: `on brand`, points: 5 },
  { phrase: `war room`, points: 5 },
  { phrase: `sea change`, points: 5 },
  { phrase: `silo mentality`, points: 5, stringMatch: "silo" },
  { phrase: `boil the frog`, points: 5 },
  { phrase: `fail fast`, points: 5 },
  { phrase: `tiger team`, points: 5 },
  { phrase: `white glove`, points: 5 },
  { phrase: `hockey stick`, points: 5 },
  { phrase: `rat hole`, points: 5 },
  { phrase: `fire drill`, points: 5 },
  { phrase: `moonshot`, points: 5 },
  { phrase: `go-to-market`, points: 5, alternates: ["go to market"] },
  { phrase: `hair on fire`, points: 5 },
  { phrase: `eat the frog`, points: 5 },
  { phrase: `pivot point`, points: 5 },
  { phrase: `pre-mortem`, points: 5, alternates: ["premortem"] },
  { phrase: `scope creep`, points: 5 },
  { phrase: `swim lane`, points: 5, alternates: ["swimlane"] },
  { phrase: `brass tacks`, points: 5 },
  { phrase: `frickin' obvious`, points: 5, alternates: ["frickin obvious", "freakin obvious", "freakin' obvious"] },
  { phrase: `surprise party`, points: 5 },
  { phrase: `our KPIs`, points: 5, stringMatch: "kpis", alternates: ["kpis", "our kpi"] },
  { phrase: `that's my rock`, points: 5, stringMatch: "my rock" },
  { phrase: `scrum master`, points: 5 },
  { phrase: `long COVID`, points: 5, alternates: ["long-covid"] },
  { phrase: `during lockdown`, points: 5 },
  { phrase: `in the weeds`, points: 5 },
  { phrase: `30,000-foot view`, points: 5, stringMatch: "foot view", alternates: ["30000 foot view", "30,000 foot view", "30k foot view"] },
  { phrase: `red tape`, points: 5 },
  { phrase: `cold press`, points: 5, stringMatch: "cold press" },
  { phrase: `off the rails`, points: 5 },
  { phrase: `crunch time`, points: 5 },
  { phrase: `double down`, points: 5 },
  { phrase: `table stakes`, points: 5 },
  { phrase: `radio silence`, points: 5 },
  { phrase: `a no-brainer`, points: 5, alternates: ["no brainer"] },

  /////////////
  //
  // 10 Points — Medium
  //

  { phrase: `Dunkin' Donuts`, points: 10, alternates: ["donuts", "dunkin'"], stringMatch: "dunkin" },
  { phrase: `They should have sent a poet!`, points: 10, stringMatch: "sent a poet" },
  { phrase: `Who wants stickers?`, points: 10, stringMatch: "stickers" },
  { phrase: `my support animal`, points: 10, stringMatch: "support animal" },
  { phrase: `the great state of Alaska`, points: 10, stringMatch: "alaska" },
  { phrase: `I need a lot of Sriracha`, points: 10, alternates: ["siracha"], stringMatch: "sriracha" },
  { phrase: `left shark`, points: 10 },
  { phrase: `wild in the streets`, points: 10, stringMatch: "streets" },
  { phrase: `the flyover states`, points: 10, alternates: ["fly-over"], stringMatch: "flyover" },
  { phrase: `boil the ocean`, points: 10, alternates: ["boil ocean"] },
  { phrase: `I'm low-key obsessed`, points: 10, stringMatch: "low-key obsessed", alternates: ["low key obsessed"] },
  { phrase: `do a quick vibe check`, points: 10, stringMatch: "vibe check" },
  { phrase: `low-hanging fruit`, points: 10, alternates: ["low hanging fruit"] },
  { phrase: `let's run it up the flagpole`, points: 10, stringMatch: "run it up the flagpole", alternates: ["flagpole"] },
  { phrase: `a silent disco`, points: 10, stringMatch: "silent disco" },
  { phrase: `Here's my hot take...`, points: 10, stringMatch: "hot take" },
  { phrase: `It works on my machine.`, points: 10, stringMatch: "my machine" },
  { phrase: `Well, technically...`, points: 10, stringMatch: "technically" },
  { phrase: `All hail the algorithm.`, points: 10, stringMatch: "the algorithm" },
  { phrase: `We're not in Kansas anymore.`, points: 10, stringMatch: "kansas" },
  { phrase: `Delete your account.`, points: 10 },
  { phrase: `main character syndrome`, points: 10, stringMatch: "main character" },
  { phrase: `chaotic neutral`, points: 10 },
  { phrase: `Give it a quick Google.`, points: 10, stringMatch: "google" },
  { phrase: `Abso-fucking-lutely!`, points: 10, stringMatch: "absolutely", alternates: ["abso fucking lutely", "absofuckinglutely"] },
  { phrase: `double-click on that`, points: 10, stringMatch: "double click", alternates: ["double click on that"] },
  { phrase: `Honestly? No notes.`, points: 10, stringMatch: "no notes" },
  { phrase: `This slaps!`, points: 10 },
  { phrase: `I understood the assignment.`, points: 10, stringMatch: "the assignment" },
  { phrase: `The vibes are way off.`, points: 10, stringMatch: "vibes" },
  { phrase: `That's a 'me' problem.`, points: 10, stringMatch: "me problem" },
  { phrase: `The Holy Roman Empire`, points: 10, stringMatch: "holy roman empire", alternates: ["holy roman", "roman empire"] },
  { phrase: `the sheer audacity`, points: 10, stringMatch: "audacity" },
  { phrase: `yesterday's Wordle`, points: 10, stringMatch: "wordle" },
  { phrase: `goblin mode`, points: 10 },
  { phrase: `in the before times`, points: 10, stringMatch: "before times" },
  { phrase: `horse girl energy`, points: 10, stringMatch: "horse girl" },
  { phrase: `not my monkeys`, points: 10 },
  { phrase: `cursed content`, points: 10 },
  { phrase: `rent free in my head`, points: 10 },
  { phrase: `big if true`, points: 10 },
  { phrase: `eating our own dog food`, points: 10, stringMatch: "dog food" },
  { phrase: `tried to unalive me`, points: 10, stringMatch: "unalive" },
  { phrase: `Very legal & very cool.`, points: 10, stringMatch: "very legal" },
  { phrase: `as per my last email`, points: 10, stringMatch: "per my last email" },
  { phrase: `We have the technology.`, points: 10, stringMatch: "the technology" },
  { phrase: `Who invited Legal?`, points: 10, stringMatch: "invited legal" },
  { phrase: `core memories`, points: 10, stringMatch: "core memories" },
  { phrase: `New phone, who dis?`, points: 10, stringMatch: "who dis" },
  { phrase: `Haters gonna hate!`, points: 10, stringMatch: "haters" },
  { phrase: `chef's kiss`, points: 10 },
  { phrase: `yeah, that tracks`, points: 10, stringMatch: "that tracks" },
  { phrase: `The Eras Tour`, points: 10, stringMatch: "eras tour" },
  { phrase: `it just hits different`, points: 10, stringMatch: "hits different" },
  { phrase: `I did all my own research.`, points: 10, stringMatch: "my own research" },
  { phrase: `the current discourse`, points: 10, stringMatch: "discourse" },
  { phrase: `but I'm built different`, points: 10, stringMatch: "built different" },

  /////////////
  //
  // 15 Points — Hard
  //

  { phrase: `We've got to push the envelope.`, points: 15, stringMatch: "push the envelope" },
  { phrase: `threw me under the bus`, points: 15, stringMatch: "under the bus" },
  { phrase: `true out of the box thinking`, points: 15, alternates: ["out-of-the-box", "out-of-the-box thinking"], stringMatch: "the box" },
  { phrase: `I'm afraid you can't get there from here.`, points: 15, stringMatch: "get there from here" },
  { phrase: `exactly six dollars`, points: 15, alternates: ["$6.00", "$6", "6 dollars"], stringMatch: "six dollars" },
  { phrase: `what the world needs now is...`, points: 15, stringMatch: "world needs now" },
  { phrase: `COMBO BREAKER!!!`, points: 15 },
  { phrase: `You should see my XBOX achievements.`, points: 15, alternates: ["x-box", "x-box achievements"], stringMatch: "xbox" },
  {
    phrase: `a new pair of Doc Martens boots`,
    points: 15,
    alternates: ["doc martin", "doc martin boots", "dr. martin", "dr. martens"],
    stringMatch: "doc marten",
  },
  { phrase: `Gwen Stefani`, points: 15 },
  { phrase: `peel back the onion`, points: 15, alternates: ["peel the onion", "peel back onion"] },
  {
    phrase: `Let's not yuck anyone's yum.`,
    points: 15,
    stringMatch: "yuck anyone's yum",
    alternates: ["yuck someones yum", "yuck yum", "yuck a yum", "yuck anyones yum"],
  },
  {
    phrase: `I like things that are kinda fun.`,
    points: 15,
    alternates: ["kinda.fun", "things that are kinda.fun", "i like things that are kinda.fun"],
    stringMatch: "kinda fun",
  },
  { phrase: `the great resignation`, points: 15, stringMatch: "great resignation" },
  { phrase: `an emoji I can't pronounce`, points: 15, alternates: ["emoji i can't pronounce"] },
  { phrase: `the quantum deliverable`, points: 15, stringMatch: "quantum deliverable" },
  { phrase: `I did not have time to prepare for this meeting.`, points: 15, stringMatch: "prepare for this meeting" },
  { phrase: `I'm not crying, you're crying.`, points: 15, stringMatch: "you're crying" },
  { phrase: `I would like to speak to your manager.`, points: 15, stringMatch: "speak to your manager" },
  { phrase: `This meeting could have been a Slack message.`, points: 15, stringMatch: "slack message" },
  { phrase: `I volunteer as tribute!`, points: 15, stringMatch: "volunteer as tribute" },
  { phrase: `I have no memory of this place.`, points: 15, stringMatch: "no memory of this place" },
  { phrase: `I'm going to need a bigger boat.`, points: 15, stringMatch: "bigger boat" },
  { phrase: `That's a nothing burger.`, points: 15, stringMatch: "nothing burger", alternates: ["nothingburger"] },
  { phrase: `Have you tried turning it off and on again?`, points: 15, stringMatch: "off and on again" },
  { phrase: `Not all heroes wear capes.`, points: 15, stringMatch: "heroes wear capes" },
  { phrase: `We just need to burn it down and start over.`, points: 15, stringMatch: "burn it down" },
  { phrase: `Where we're going, we don't need roads.`, points: 15, stringMatch: "don't need roads" },
  { phrase: `Technically, I don't work here anymore.`, points: 15, stringMatch: "don't work here" },
  { phrase: `My horoscope said you were gonna be a dick about this.`, points: 15, stringMatch: "horoscope" },
  { phrase: `I wrote my senior thesis on this.`, points: 15, stringMatch: "senior thesis" },
  { phrase: `This is giving me Fyre Festival vibes.`, points: 15, stringMatch: "fyre festival", alternates: ["fire festival"] },
  { phrase: `I'm on day three of a juice cleanse.`, points: 15, stringMatch: "juice cleanse" },
  { phrase: `We had a similar problem at Blockbuster.`, points: 15, stringMatch: "blockbuster" },
  { phrase: `I'm going to need this in writing.`, points: 15, stringMatch: "need this in writing" },
  { phrase: `I've been asked to keep my remarks brief.`, points: 15, stringMatch: "keep my remarks brief" },
  { phrase: `I just want to say, for the record, that I disagree.`, points: 15, stringMatch: "for the record" },
  { phrase: `According to my five-year plan...`, points: 15, stringMatch: "five-year plan", alternates: ["five year plan"] },
  { phrase: `I'm not saying it's aliens, but...`, points: 15, stringMatch: "aliens" },
  { phrase: `AND I HAVE THE RECEIPTS!`, points: 15, stringMatch: "receipts" },
  { phrase: `I've already accepted a competing offer.`, points: 15, stringMatch: "competing offer" },
  { phrase: `The ROI is immeasurable.`, points: 15, stringMatch: "roi" },

  /////////////
  //
  // 30 Points — Expert
  //

  { phrase: `Sonia Sotomayor`, points: 30, alternates: ["sonia", "sotomayor"] },
  { phrase: `Sufjan Stevens`, points: 30, alternates: ["sufjan", "sufyan stevens"] },
  { phrase: `a Diplo remix`, points: 30, stringMatch: "diplo" },
  { phrase: `In the year 2525, if man is still alive`, points: 30, stringMatch: "2525" },
  { phrase: `the secret menu at Waffle House`, points: 30, stringMatch: "waffle house" },
  { phrase: `Bring on the dancing horses.`, points: 30, stringMatch: "dancing horses" },
  { phrase: `Everybody smoke pot!`, points: 30, stringMatch: "smoke pot" },
  { phrase: `the year 1947`, points: 30, stringMatch: "1947" },
  { phrase: `I, for one, welcome our new ant overlords.`, points: 30, stringMatch: "ant overlords" },
  { phrase: `the ghost of Steve Ballmer`, points: 30, stringMatch: "steve ballmer" },
  { phrase: `the last Blockbuster`, points: 30, alternates: ["last blockbuster"] },
  { phrase: `the blue shell from Mario Kart`, points: 30, stringMatch: "blue shell", alternates: ["mario kart"] },
  { phrase: `Mick Fleetwood`, points: 30, stringMatch: "fleetwood" },
  { phrase: `She's a competitive knitter.`, points: 30, stringMatch: "knitter" },
  { phrase: `...so I danced The Macarena`, points: 30, stringMatch: "macarena", alternates: ["macerena"] },
  { phrase: `seven ugly-assed pelicans`, points: 30, stringMatch: "pelicans" },
  { phrase: `Peter Bogdanovich`, points: 30, stringMatch: "bogdanovich" },
  { phrase: `Nicolas Cage had nothing to do with this.`, points: 30, stringMatch: "nicolas cage", alternates: ["nicholas cage", "nick cage"] },
  { phrase: `that peg game they have at Cracker Barrel`, points: 30, stringMatch: "cracker barrel", alternates: ["peg game"] },
  { phrase: `What's the name of the boat in Titanic?`, points: 30, stringMatch: "titanic" },
  { phrase: `Oh! (long pause) Just one more thing...`, points: 30, stringMatch: "one more thing", alternates: ["just one more thing"] },
];
