
const challenges = [
  {
    id: 1,
    name: "Mortal Kombat",
    nameAsRule: "Your password must be a playable Mortal Kombat character",
    failedMessage: "[PASS] is not a playable Mortal Kombat character",
    possible: [
      "johnny cage",
      "kano",
      "liu kang",
      "raiden",
      "scorpion",
      "sonya blade",
      "sub-zero",
      "goro",
      "shang tsung",
      "reptile",
      "baraka",
      "jade",
      "jax",
      "kintaro",
      "kitana",
      "kung lao",
      "mileena",
      "noob saibot",
      "shao khan",
      "smoke",
      "chameleon",
      "cyrax",
      "ermac",
      "kabal",
      "khameleon",
      "motaro",
      "nightwolf",
      "rain",
      "sektor",
      "sheeva",
      "sindel",
      "stryker",
      "meat",
      "bo rai cho",
      "frost"
    ]
  },

  {
    id: 2,
    name: "Bob's Burgers",
    nameAsRule: "Your password must be the first name of a Bob's Burgers character",
    failedMessage: "[PASS] is not a Bob's Burgers character",
    possible: [
      "Mike",
      "Bob",
      "LINDA",
      "GENE",
      "LOUISE",
      "TINA",
      "TEDDY",
      "MORT",
      "RUDY",
      "JIMMY",
      "ANDY",
      "OLLIE",
      "JOCELYN",
      "TAMMY",
      "HELEN",
      "TREV",
      "MARSHMALLOW",
      "BOO BOO",
      "DARRYL",
      "PHILLIP",
      "ALEX",
      "ART",
      "RANDY",
      "KURT",
      "LOGAN",
      "SASHA"
    ]
  },

  {
    id: 3,
    name: "Words For Breasts",
    nameAsRule: "Your password must be a word the Oxford English Dictionary recognizes as a synonym for “breasts”",
    failedMessage: "The OED doesn't recognize [PASS] as a word for breasts.",
    naughty: true,
    possible: [
      "CHEST",
      "BUST",
      "BOSOM",
      "BOOBS",
      "KNOCKERS",
      "BOOBIES",
      "BOOBS",
      "BAZOOKAS",
      "MELONS",
      "JUBBLIES",
      "BUBBLIES",
      "ORBS",
      "GLOBES",
      "CHARLIES",
      "BAPS",
      "BAZOOMS",
      "CASABAS",
      "CHI CHIS",
      "NORKS",
      "TITS",
      "TITTIES",
      "JUGS",
      "HOOTERS",
      "CANS"
    ]
  },

  {
    id: 4,
    name: "African Countries",
    nameAsRule: "Your password MUST be a country in Africa",
    failedMessage: "[PASS] is not an African country",
    possible: [
      "ALGERIA",
      "ANGOLA",
      "BENIN",
      "BOTSWANA",
      "Algeria",
      "Angola",
      "Benin",
      "Botswana",
      "Burkina Faso",
      "Burundi",
      "Cabo Verde",
      "Cameroon",
      "Central African Republic",
      "Chad",
      "Comoros",
      "Republic of the Congo",
      "Democratic Republic of the Congo",
      "Cote d'Ivoire",
      "Djibouti",
      "Egypt",
      "Equatorial Guinea",
      "Eritrea",
      "Eswatini",
      "Ethiopia",
      "Gabon",
      "Gambia",
      "Ghana",
      "Guinea",
      "Guinea-Bissau",
      "Kenya",
      "Lesotho",
      "Liberia",
      "Libya",
      "Madagascar",
      "Malawi",
      "Mali",
      "Mauritania",
      "Mauritius",
      "Morocco",
      "Mozambique",
      "Namibia",
      "Niger",
      "Nigeria",
      "Rwanda",
      "Senegal",
      "Seychelles",
      "Sierra Leone",
      "Somalia",
      "South Africa",
      "South Sudan",
      "Sudan",
      "Tanzania",
      "Togo",
      "Tunisia",
      "Uganda",
      "Zambia",
      "Zimbabwe"
    ]
  },

  {
    id: 5,
    name: "European Countries",
    nameAsRule: "Your password must be a country in Europe",
    failedMessage: "Sorry! [PASS] is not a European Country.",
    possible: [
      "Albania",
      "Andorra",
      "Armenia",
      "Austria",
      "Azerbaijan",
      "Belarus",
      "Belgium",
      "Bosnia and Herzegovina",
      "Bulgaria",
      "Croatia",
      "Cyprus",
      "Czechia",
      "Denmark",
      "Estonia",
      "Finland",
      "France",
      "Georgia",
      "Germany",
      "Greece",
      "Hungary",
      "Iceland",
      "Ireland",
      "Italy",
      "Kazakhstan",
      "Kosovo",
      "Latvia",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Malta",
      "Moldova",
      "Monaco",
      "Montenegro",
      "Netherlands",
      "North Macedonia",
      "Norway",
      "Poland",
      "Portugal",
      "Romania",
      "Russia",
      "San Marino",
      "Serbia",
      "Slovakia",
      "Slovenia",
      "Spain",
      "Sweden",
      "Switzerland",
      "Turkey",
      "Ukraine",
      "United Kingdom",
      "Vatican City"
    ]
  },

  {
    id: 6,
    name: "Football Teams",
    nameAsRule: "Your password must be an NFL football team name",
    failedMessage: "Sorry! There are no [PASS] in the NFL.",
    possible: [
      "CARDINALS",
      "FALCONS",
      "PANTHERS",
      "BEARS",
      "COWBOYS",
      "LIONS",
      "PACKERS",
      "RAMS",
      "VIKINGS",
      "SAINTS",
      "GIANTS",
      "EAGLES",
      "49ERS",
      "SEAHAWKS",
      "BUCCANEERS",
      "FOOTBALL TEAM",
      "RAVENS",
      "BILLS",
      "BENGALS",
      "BROWNS",
      "BRONCOS",
      "TEXANS",
      "COLTS",
      "JAGUARS",
      "CHIEFS",
      "RAIDERS",
      "CHARGERS",
      "DOLPHINS",
      "PATRIOTS",
      "STEELERS",
      "TITANS"
    ]
  },

  {
    id: 7,
    name: "State Birds",
    nameAsRule: "Your password must be a U.S. state bird",
    failedMessage: "Sorry, no US State made [PASS] their official bird.",
    possible: [
      "YELLOWHAMMER",
      "WILLOW PTARMIGAN",
      "WREN",
      "MOCKINGBIRD",
      "QUAIL",
      "LARK",
      "ROBIN",
      "BLUE HEN",
      "THRUSH",
      "THRASHER",
      "GOOSE",
      "BLUEBIRD",
      "CARDINAL",
      "GOLDFINCH",
      "FINCH",
      "MEADOWLARK",
      "PELICAN",
      "CHICKADEE",
      "ORIOLE",
      "LOON",
      "ROADRUNNER",
      "FRUIT DOVE",
      "GROUSE",
      "RHODE ISLAND RED",
      "PHEASANT",
      "GULL",
    ]
  },

  {
    id: 8,
    name: "Synonyms for Blue",
    nameAsRule: "Your password must be a synonym for blue",
    failedMessage: "Thesaurus.com doesn't list [PASS] as a synonym for blue.",
    possible: [
      "AZURE",
      "COBALT",
      "SAPPIRE",
      'CERULEAN',
      "NAVY",
      "ULTRAMARINE",
      "LAPIS",
      "INDIGO",
      "AQUAMARIE",
      "TURQUOISE",
      "TEAL",
      "CYAN",
      "DEPRESSED",
      "DOWN",
      "SAD",
      "SADDENED",
      "UNHAPPY",
      "MELANCHOLY",
      "MISERABLE",
      "SORROWFUL",
      "GLOOMY",
      "DEJECTED",
      "DOWNHEARTED",
      "DISHEARTENED",
      "DESPONDENT",
      "DISPIRITED",
      "LOW",
      "LOW SPIRITED",
      "HEAVY HEARTED",
      "GLUM",
      "MOROSE",
      "DISMAL",
      "DOWNCAST",
      "CAST DOWN",
      "TEARFUL",
      "DOWN IN THE DUMPS",
      "DOWN IN THE MOUTH",
      "FED UP",
      "INDECENT",
      "DIRTY",
      "RUDE",
      "COARSE",
      "VULGAR",
      "BAWDY",
      "LEWD",
      "RACY"
    ]
  },

  {
    id: 9,
    name: "Leafy Green Vegetables",
    nameAsRule: "Your password must be a leafy green vegetable",
    failedMessage: "[PASS] is not a leafy green vegeable",
    possible: [
      "ARUGULA",
      "BIBB",
      "CABBAGE",
      "LETTUCE",
      "BEET GREENS",
      "COLLARD GREENS",
      "DANDELION GREENS",
      "KALE",
      "MICROGREENS",
      "MUSTARD GREENS",
      "RAPINI",
      "BROCCOLI RABE",
      "ROMAINE",
      "SPINACH",
      "SWISS CHARD",
      "WATERCRESS",
      "ENDIVE",
      "BOK CHOY",
      "TURNIP GREENS",
      "PARSLEY"
    ]
  },

  {
    id: 10,
    name: "World Languages",
    nameAsRule: "Your password must be an Official Language of any country",
    failedMessage: "[PASS] is not a language recognized by any country.",
    possible: [
      "ABKHAZ",
      "ALBANIAN",
      "ARABIC",
      "ARMENIAN",
      "AZERBAIJANI",
      "BELARUSIAN",
      "BENGALI",
      "BOSNIAN",
      "BULGARIAN",
      "BURMESE",
      "CASTILIAN",
      "CATALAN",
      "COMORIAN",
      "CROATIAN",
      "CZECH",
      "DANISH",
      "DARI",
      "DUTCH",
      "DZONGKHA",
      "ENGLISH",
      "ESTONIAN",
      "FIJIAN",
      "FINNISH",
      "FRENCH",
      "GEORGIAN",
      "GERMAN",
      "GREEK",
      "HEBREW",
      "HINDI",
      "HUNGARIAN",
      "ICELANDIC",
      "INDONESIAN",
      "IRISH",
      "ITALIAN",
      "JAPANESE",
      "KAZAKH",
      "KHMER",
      "KIRUNDI",
      "KYRGYZ",
      "KOREAN",
      "LAO",
      "LATVIAN",
      "LITHUANIAN",
      "LUXEMBOURGISH",
      "MACEDONIAN",
      "MALAY",
      "MALTESE",
      "MAORI",
      "MANDARIN",
      "MONGOLIAN",
      "NEPALI",
      "NORWEGIAN",
      "PALAUAN",
      "PASHTO",
      "PERSIAN",
      "POLISH",
      "PORTUGUESE",
      "QUECHUA",
      "ROMANIAN",
      "RUSSIAN",
      "SERBIAN",
      "SLOVAK",
      "SLOVENE",
      "SOMALI",
      "SOTHO",
      "SPANISH",
      "SWAHILI",
      "SWAZI",
      "SWEDISH",
      "TAJIK",
      "TAMAZIGHT",
      "TETUM",
      "TIGRINYA",
      "TSWANA",
      "TURKISH",
      "UKRANIAN",
      "URDU",
      "UZBEK",
      "WOLEAIAN"
    ],
    source: "https://en.wikipedia.org/wiki/List_of_official_languages_by_country_and_territory"

  },

  {
    id: 11,
    name: "Coen Brothers Movies",
    nameAsRule: "Your password must be the title of a film written and/or directed by Joel and/or Ethan Coen.",
    failedMessage: "[PASS] is not a Coen Brothers movie.",
    possible: [
      "BLOOD SIMPLE",
      "CRIMEWAVE",
      "RAISING ARIZONA",
      "MILLER'S CROSSING",
      "BARTON FINK",
      "THE HUDSUCKER PROXY",
      "FARGO",
      "THE BIG LEBOWSKI",
      "THE NAKED MAN",
      "O BROTHER, WHERE ART THOU?",
      "THE MAN WHO WASN'T THERE",
      "INTOLERABLE CRUELTY",
      "THE LADYKILLERS",
      "TUILERIES",
      "WORLD CINEMA",
      "NO COUNTRY FOR OLD MEN",
      "BURN AFTER READING",
      "A SERIOUS MAN",
      "TRUE GRIT",
      "GAMBIT",
      "INSIDE LLEWYN DAVIS",
      "UNBROKEN",
      "BRIDGE OF SPIES",
      "HAIL, CAESAR!",
      "SUBURBICON",
      "THE BALLAD OF BUSTER SCRUGGS",
      "THE TRAGEDY OF MACBETH"
    ]
  },

  /*
  {
    id: 12,
    name: "Worst Movies",
    nameAsRule: "Your password must be a movie which won a “Worst Picture” award at the Golden Raspberry Awards",
    hint: "one picture awarded per year, starting in 1980",
    failedMessage: "[PASS] never won a Razzie",
    possible: [
      "CAN'T STOP THE MUSIC",
      "MOMMIE DEAREST",
      "INCHON",
      "THE LONELY LADY",
      "BOLERO",
      "RAMBO: FIRST BLOOD PART II",
      "HOWARD THE DUCK",
      "UNDER THE CHERRY MOON",
      "LEONARD PART 6",
      "COCKTAIL",
      "STAR TREK 5",
      "STAR TREK V",
      "THE ADVENTURES OF FORD FAIRLANE",
      "GHOSTS CAN'T DO IT",
      "HUDSON HAWK",
      "SHINING THROUGH",
      "INDECENT PROPOSAL",
      "COLOR OF NIGHT",
      "SHOWGIRLS",
      "STRIPTEASE",
      "THE POSTMAN",
      "BURN HOLLYWOOD BURN",
      "WILD WILD WEST",
      "BATTLEFIELD EARTH",
      "FREDDY GOT FINGERED",
      "SWEPT AWAY",
      "GIGLI",
      "CATWOMAN",
      "DIRTY LOVE",
      "BASIC INSTICT 2",
      "I KNOW WHO KILLED ME",
      "THE LOVE GURU",
      "TRANSFORMERS: REVENGE OF THE FALLEN",
      "THE LAST AIRBENDER",
      "JACK AND JILL",
      "THE TWILIGHT SAGA: BREAKING DAWN PART 2",
      "MOVIE 43",
      "SAVING CHRISTMAS",
      "FANTASTIC FOUR",
      "FIFTY SHADES OF GREY",
      "HILLARY'S AMERICA",
      "THE EMOJI MOVIE",
      "HOLMES & WATSON",
      "CATS"
    ],
    source: "https://en.wikipedia.org/wiki/Golden_Raspberry_Award_for_Worst_Picture"
  },
  */

  {
    id: 13,
    name: "Worst Actors",
    nameAsRule: "Your password must be the LAST name of a “Worst Actor” award winner.",
    hint: "“Worst Actor” is a separate category from “Worst Actress”",
    failedMessage: "[PASS] never won a Razzie",
    possible: [

      // ACTORS
      "DIAMOND",
      "SPILSBURY",
      "OLIVIER",
      "ATKINS",
      "STALLONE",
      "PRINCE",
      "COSBY",
      "SHATNER",
      "CLAY",
      "COSTNER",
      "REYNOLDS",
      "SHORE",
      "ARNOLD",
      "WILLIS",
      "SANDLER",
      "TRAVOLTA",
      "GREEN",
      "BENIGNI",
      "AFFLECK",
      "BUSH",
      "SCHNEIDER",
      "WAYANS",
      "MURPHY",
      "MYERS",
      "JONAS",
      "KUTCHER",
      "SMITH",
      "CAMERON",
      "DORNAN",
      "D'SOUZA",
      "CRUISE",
      "TRUMP"
    ]
  },

  {
    id: 14,
    name: "Worst Actresses",
    nameAsRule: "Your password must be the LAST name of a “Worst Actress” award winner",
    hint: "“Worst Actress” is a separate category from “Worst Actor”",
    failedMessage: "[PASS] never won a Razzie",
    possible: [
      // ACTRESSES
      "SHIELDS",
      "DEREK",
      "DUNAWAY",
      "ZADORA",
      "BLAIR",
      "MADONNA",
      "MINELLI",
      "LOCKLEAR",
      "YOUNG",
      "GRIFFITH",
      "STONE",
      "BERKLEY",
      "MOORE",
      "SPICE",
      "DONAHUE",
      "CAREY",
      "SPEARS",
      "LOPEZ",
      "BERRY",
      "MCCARTHY",
      "LOHAN",
      "HILTON",
      "BULLOCK",
      "CATTRALL", "DAVIS", "NIXON", "PARKER",
      "STEWART",
      "PERRY",
      "DIAZ",
      "JOHNSON",
      "DUFF"
    ]
  },

  {
    id: 15,
    name: "My Little Ponies",
    nameAsRule: "Your password must be a My Little Pony (unicorns count)",
    failedMessage: "[PASS] isn't a My Little Pony! 🦄",
    possible: [
      "TWILIGHT SPARKLE",
      "APPLEJACK",
      "FLUTTERSHY",
      "RARITY",
      "PINKIE PIE",
      "RAINBOW DASH",
      "APPLE BLOOM",
      "SCOOTALOO",
      "SWEETIE BELLE",
      "BABS SEED",
      "PRINCESS CELESTIA",
      "PRINCESS LUNA",
      "PRINCE BLUEBLOOD",
      "SHINING ARMOR",
      "PROCESS CADENCE",
      "FLURRY HEART",
      "PRINCESS AMORE",
      "GRANNY SMITH",
      "BIG MCINTOSH",
      "BRAEBURN",
      "AUNT ORANGE",
      "UNCLE ORANGE",
      "HAYSEED TURNIP TRUCK",
      "APPLE STRUDEL",
      "AUNTIE APPLESAUCE",
      "APPLE ROSE",
      "GOLDIE DELICIOUS",
      "BRIGHT MAC",
      "PEAR BUTTER",
      "MAUD PIE",
      "STARLIGHT GLIMMER",
      "SUNSET SHIMMER",
      "TEMPEST SHADOW"
    ]
  },

  {
    id: 16,
    name: "Generation I Pokemon",
    nameAsRule: "Your password must be one of the original 151 Pokemon",
    failedMessage: "[PASS] is not a Pokemon, or is from a later generation!",
    possible: [
      "BULBASAUR",
      "IVYSAUR",
      "VENUSAUR",
      "CHARMANDER",
      "CHARMELEON",
      "CHARIZARD",
      "SQUIRTLE",
      "WARTORTLE",
      "BLASTOISE",
      "CATERPIE",
      "METAPOD",
      "BUTTERFREE",
      "WEEDLE",
      "KAKUNA",
      "BEEDRILL",
      "PIDGEY",
      "PIDGEOTTO",
      "PIDGEOT",
      "RATTATA",
      "RATICATE",
      "SPEAROW",
      "FEAROW",
      "EKANS",
      "ARBOK",
      "PIKACHU",
      "RAICHU",
      "SANDSHREW",
      "SANDSLASH",
      "NIDORAN",
      "NIDORINA",
      "NIDOQUEEN",
      "NIDORINO",
      "NIDOKING",
      "CLEFAIRY",
      "CLEFABLE",
      "VULPIX",
      "NINETALES",
      "JIGGLYPUFF",
      "WIGGLYTUFF",
      "ZUBAT",
      "GOLBAT",
      "ODDISH",
      "GLOOM",
      "VILEPLUME",
      "PARAS",
      "PARASECT",
      "VENONAT",
      "VENOMOTH",
      "DIGLETT",
      "DUGTRIO",
      "MEOWTH",
      "PERSIAN",
      "PSYDUCK",
      "GOLDUCK",
      "MANKEY",
      "PRIMEAPE",
      "GROWLITHE",
      "ARCANINE",
      "POLIWAG",
      "POLIWHIRL",
      "POLIWRATH",
      "ABRA",
      "KADABRA",
      "ALAKAZAM",
      "MACHOP",
      "MACHOKE",
      "MACHAMP",
      "BELLSPROUT",
      "WEEPINBELL",
      "VICTREEBEL",
      "TENTACOOL",
      "TENACRUEL",
      "GEODUDE",
      "GRAVELER",
      "GOLEM",
      "PONYTA",
      "RAPIDASH",
      "SLOWPOKE",
      "SLOWBRO",
      "MAGNEMITE",
      "MAGNETON",
      "FARFETCH'D",
      "DODUO",
      "DODRIO",
      "SEEL",
      "DEWGONG",
      "GRIMER",
      "MUK",
      "SHELLDER",
      "CLOYSTER",
      "GASTLY",
      "HAUNTER",
      "GENGAR",
      "ONIX",
      "DROWSEE",
      "HYPNO",
      "KRABBY",
      "KINGLER",
      "VOLTORB",
      "ELECTRODE",
      "EXEGGCUTE",
      "EXEGGUTOR",
      "CUBONE",
      "MAROWAK",
      "HITMONLEE",
      "HITMONCHAN",
      "LICKITUNG",
      "KOFFING",
      "WEEZING",
      "RHYHORN",
      "RHYDON",
      "CHANSEY",
      "TANGELA",
      "KANGASKHAN",
      "HORSEA",
      "SEADRA",
      "GOLDEEN",
      "SEAKING",
      "STARYU",
      "STARMIE",
      "MR. MIME",
      "SCYTHER",
      "JYNX",
      "ELECTABUZZ",
      "MAGMAR",
      "PINSIR",
      "TAUROS",
      "MAGIKARP",
      "GYARADOS",
      "LAPRAS",
      "DITTO",
      "EEVEE",
      "VAPOREON",
      "JOLTEON",
      "FLAREON",
      "PORYGON",
      "OMANYTE",
      "OMASTAR",
      "KABUTO",
      "KABUTOPS",
      "AERODACTYL",
      "SNORLAX",
      "ARTICUNO",
      "ZAPDOS",
      "MOLTRES",
      "DRATINI",
      "DRAGONAIR",
      "DRAGONITE",
      "MEWTWO",
      "MEW"
    ]
  },

  {
    id: 17,
    name: "Root Vegetables",
    nameAsRule: "Your password must be a type of root vegetable.",
    failedMessage: "[PASS] isn't a vegetable, go back to culinary school.",
    possible: [
      "KONJAC",
      "TARO",
      "WATER CHESTNUT",
      "LOTUS",
      "WATERLILY",
      "TUMERIC",
      "GINSENG",
      "ARROWROOT",
      "GINGER",
      "HOG POTATO",
      "GROUNDNUT",
      "TIGERNUT",
      "CHINESE YAM",
      "JERUSALEM ARTICHOKE",
      "SUNCHOKE",
      "BEETROOT",
      "BEET",
      "RADISH",
      "PARSNIP",
      "SWEDES",
      "CELERIAC",
      "CELERY ROOT",
      "YAM",
      "DAIKON",
      "JICAMA",
      "HORSERADISH",
      "POTATO",
      "CARROT",
      "SWEET POTATO",
      "MACA",
      "CASSAVA",
      "YUCA",
      "MANIOC",
      "KOHLRABI",
      "CROSNE",
      "EVORA",
      "FETID",
      "BREADROOT",
      "OAXCACA",
      "RUTABAGA",
      "SKIRRET",
      "ONION",
      "GARLIC",
      "FENNEL",
      "PIGNUT",
      "EARTHNUT"
    ]
  },

  {
    id: 18,
    name: "Olympic Sports",
    nameAsRule: "Your password must be an event currently played during the Olympics.",
    failedMessage: "[PASS] is not a Summer or Winter event listed on the Olympics website.",
    possible: [
      "ARCHERY",
      "ARTISTIC SWIMMING",
      "BADMINTON",
      "BASEBALL",
      "SOFTBALL",
      "BEACH VOLLEYBALL",
      "BOXING",
      "BREAKING",
      "BREAK DANCING",
      "BASKETBALL",
      "CANOE SLALOM",
      "CANOE SPRINT",
      "CYCLING BMX",
      "CYCLING MOUNTAIN BIKE",
      "CYCLING ROAD",
      "CYCLING TRACK",
      "DIVING",
      "EQUESTRIAN",
      "DRESSAGE",
      "EQUESTRIAN EVENTING",
      "EQUESTRIAN JUMPING",
      "FENCING",
      "FOOTBALL",
      "SOCCER",
      "GOLF",
      "GYMNASITCS ARTISTIC",
      "GYMNASTICS RHYTHMIC",
      // ALSO
      // "RHYTHM GYMNASTICS"
      "HANDBALL",
      "HOCKEY",
      "JUDO",
      "KARATE",
      "MARATHON SWIMMING",
      "MODERN PENTATHLON",
      "ROWING",
      "RUGBY",
      "SAILING",
      "SHOOTING",
      "SKATEBOARDING",
      "SPORT CLIMBING",
      "SURFING",
      "SWIMMING",
      "TABLE TENNIS",
      "TAEKWONDO",
      "TENNIS",
      "TRAMPOLINE",
      "TRIATHLON",
      "VOLLEYBALL",
      "WATER POLO",
      "WEIGHTLIFTING",
      "WRESTLING FREESTYLE",
      "WRESTLING GRECO-ROMAN",
      "ALPINE SKIING",
      "BIATHLON",
      "BOBSLEIGH",
      "CROSS COUNTRY SKIING",
      "CURLING",
      "FIGURE SKATING",
      "FREESTYLE SKIING",
      "ICE HOCKEY",
      "LUGE",
      "NORDIC COMBINED",
      "SHORT TRACK",
      "SKELETON",
      "SKI JUMPING",
      "SNOWBOARD",
      "SPEED SKATING"
    ]
  },

  {
    id: 19,
    name: "Classic Cocktails",
    nameAsRule: "Your password must be a cocktail any bartender would be able to make.",
    failedMessage: "Did you find [PASS] on AllRecipes? Please try another cocktail.",
    possible: [
      "OLD FASHIONED",
      "MARGARITA",
      "COSMOPOLITAN",
      "NEGRONI",
      "MOSCOW MULE",
      "MARTINI",
      "MOJITO",
      "WHISKEY SOUR",
      "FRENCH 75",
      "MANHATTAN",
      "SPRITZ",
      "APEROL SPRITZ",
      "GIMLET",
      "SAZERAC",
      "PIMM'S CUP",
      "MIMOSA",
      "PALOMA",
      "SIDECAR",
      "MINT JULEP",
      "DAIQUIRI",
      "DARK AND STORMY",
      "MARTINEZ",
      "IRISH COFFEE",
      "LONG ISLAND",
      "LONG ISLAND ICED TEA",
      "BRANDY ALEXANDER",
      "OLD CUBAN",
      "SIDECAR",
      "GIN FIZZ",
      "VESPER",
      "WHITE LADY",
      "AVIATION",
      "TOM COLLINS",
      "PINA COLADA",
      "LAST WORD",
      "PISCO SOUR",
      "BEES KNEES",
      "BRAMBLE",
      "AMERICANO",
      "CORPSE REVIVER",
      "MAI TAI",
      "AMARETTO SOUR",
      "BOULIVARDIER",
      "BLOODY MARY",
      "WHISKEY SOUR",
      "WHITE RUSSIAN",
      "PAINKILLER",
      "GIN RICKEY",
      "LIME RICKEY",
      "MUDSLIDE",
      "VIEUX CARRE",
      "RUM RUNNER",
      "CAIPIRINHA",
      "HURRICANE",
      "TEQUILA SUNRISE",
      "KAMIKAZE",
      "HOT TODDY",
      "ROB ROY",
      "MARY PICKFORD"
    ]
  },

  {
    id: 20,
    name: "Recurring Simpsons Characters",
    nameAsRule: "Your password must be the first name of a recurring Simpsons character.",
    failedMessage: "[PASS] is not a Simpsons character. Or is. It's 32+ seasons.",
    possible: [
      "HOMER",
      "MARGE",
      "BART",
      "LISA",
      "MAGGIE",
      "ABRAHAM",
      "SANTA'S LITTLE HELPER",
      "SNOWBALL II",
      "SNOWBALL V",
      "APU",
      "BARNEY",
      "BLEEDING GUMS MURPHY",
      "CLANCY",
      // ALSO
      // "CHIEF WIGGUM"
      "DEWEY",
      "EDDIE",
      "EDNA",
      "ITCHY",
      "JANEY",
      "JASPER",
      "KENT",
      "KRUSTY",
      "LOU",
      "MARTIN",
      "MARVIN",
      "MILHOUSE",
      "MOE",
      "MR. BURNS",
      "NED",
      "OTTO",
      "PATTY",
      "RALPH",
      "TIMOTHY",
      // ALSO
      // "REVEREND LOVEJOY"
      "SCRATCHY",
      "SELMA",
      "SEYMOUR",
      "SHERRI",
      "SIDESHOW BOB",
      "TODD",
      "WAYLON",
      "BERNICE",
      "CARL",
      "DOLPH",
      "JULIUS",
      // ALSO
      // "DR. HIBBERT"
      "NICK",
      // ALSO
      // "DR. NICK"
      "ELIZABETH",
      "HANS",
      "HELEN",
      "HERMAN",
      "JACQUELINE",
      "JIMBO",
      "KEARNEY",
      "LIONEL",
      "MAUDE",
      "MAYOR QUIMBY",
      "NELSON",
      "JONATHAN",
      "PROFESSOR FRINK",
      "RAINIER",
      "ROD",
      "SIDESHOW MEL",
      "TROY",
      "AGNES",
      "COMIC BOOK GUY",
      "GROUNDSKEEPER WILLIE",
      "KANG",
      "KODOS",
      "LUANN",
      "BUMBLEBEE MAN",
      "LUNCHLADY DORIS",
      "DORIS",
      "SEA CAPTAIN",
      "RUTH",
      "CLETUS",
      "GARY",
      // ALSO
      // "SUPERINTENDENT CHALMERS"
      "ALICE",
      "SARAH",
      "FAT TONY",
      "MONA",
      "DISCO STU",
      "MANJULA",
      "DUFFMAN",
      "ALLISON",
      "RICH TEXAN",
      "GIL"
    ]
  },

  {
    id: 21,
    name: "Top 100 SNES Games",
    nameAsRule: "Your password must be a Super Nintendo game considered to be one of the top 100 best.",
    failedMessage: "[PASS] is not considered one of the Top 100 SNES games, according to IGN.",
    possible: [
      "FINAL FIGHT",
      "TINY TOON ADVENTURES: BUSTER BUSTS LOOSE",
      // ALSO
      // "TINY TOON ADVENTURES"
      "UNIRACERS",
      "ULTIMATE MORTAL KOMBAT 3",
      // ALSO
      // "MORTAL KOMBAT 3"
      // "MORTAL KOMBAT III"
      // "ULTIMATE MORTAL KOMBAT III"
      "STREET FIGHTER ALPHA 2",
      "TOP GEAR 2",
      "ADVENTURES OF BATMAN AND ROBIN",
      "SUPER TURRICAN 2",
      "SUPER DOUBLE DRAGON",
      "SUPER STAR WARS: THE EMPIRE STRIKES BACK",
      // ALSO
      // "STAR WARS THE EMPIRE STRIKES BACK"
      "BLACKTHORNE",
      "SUPER BOMBERMAN 2",
      "SUNSET RIDERS",
      "SPARKSTER",
      "STUNT RACE FX",
      "SPIDER-MAN AND VENOM: MAXIMUM CARNAGE",
      // ALSO
      // "SPIDER MAN AND VENOM"
      "SUPER TENNIS",
      "SUPER STAR WARS",
      "KILLER INSTINCT",
      "DEATH AND RETURN OF SUPERMAN",
      "PILOTWINGS",
      "FLASHBACK: THE QUEST FOR IDENTITY",
      // ALSO
      // "FLASHBACK"
      "X-MEN: MUTANT APOCALYPSE",
      "SHADOWRUN",
      "SOUL BLAZER",
      "MADDEN NFL '94",
      "ILLUSION OF GAIA",
      "POCKY AND ROCKY 2",
      "ROCK N' ROLL RACING",
      "JUNGLE STRIKE",
      "POPULOUS",
      "OUT OF THIS WORLD",
      "KIRBY'S AVALANCHE",
      "MEGA MAN X3",
      "THE LION KING",
      "R-TYPE III: THE THIRD LIGHTNING",
      // ALSO
      // "R-TYPE III",
      // "R-TYPE 3"
      "INTERNATIONAL SUPERSTAR SOCCER",
      "FATAL FURY 2",
      "KIRBY'S DREAM LAND 3",
      "JOE AND MAC 2: LOST IN THE TROPICS",
      // ALSO
      // "JOE AND MAC 2",
      // "JOE & MAC"
      "ALADDIN",
      "NHL '94",
      "DONKEY KONG COUNTRY 3",
      "EARTHWORM JIM",
      "ALIEN 3",
      "AXELAY",
      "BUST-A-MOVE",
      "BREATH OF FIRE II",
      // ALSO
      // "BREATH OF FIRE 2"
      "KEN GRIFFEY JR.'S WINNING RUN",
      // ALSO
      // "KEN GRIFFEY JRS WINNING RUN"
      "SUPER GHOULS N' GHOSTS",
      "YOSHI'S COOKIE",
      "SUPER BOMBERMAN",
      "ZOMBIES AT MY NEIGHBORS",
      "KIRBY SUPER STAR",
      "HARVEST MOON",
      "GRADIUS III",
      "DEMON'S CREST",
      "BREATH OF FIRE",
      "EVO: SEARCH FOR EDEN",
      // ALSO
      // "EVO SEARCH FOR EDEN",
      // "EVO"
      "OGRE BATTLE",
      "EARTHWORM JIM 2",
      "TEENAGE MUTANT NINJA TURTLES: TURTLES IN TIME",
      // ALSO
      // "TMNT: TURTLES IN TIME",
      // "TMNT TURTLES IN TIME",
      // "TURTLES IN TIME"
      "KIRBY'S DREAM COURSE",
      "UN SQUADRON",
      "NBA JAM",
      "SIM CITY",
      "LUFIA II",
      // ALSO
      // "LUFIA 2"
      // "LUFIA II: RISE OF THE SINISTRALS",
      // "LUFIA 2: RISE OF THE SINISTRALS"
      "METAL WARRIORS",
      "LEGEND OF THE MYSTICAL NINJA",
      "MEGA MAN X2",
      "THE LOST VIKINGS",
      "WARIO'S WOODS",
      "DONKEY KONG COUNTRY",
      "TETRIS AND DR. MARIO",
      "SUPER STAR WARS: RETURN OF THE JEDI",
      // ALSO
      // "STAR WARS: RETURN OF THE JEDI"
      "MORTAL KOMBAT II",
      // ALSO
      // "MORTAL KOMBAT 2"
      "CONTRA III",
      // ALSO
      // "CONTRA 3"
      "THE MAGICAL QUEST",
      "MARIO PAINT",
      "SUPER CASTLEVANIA IV",
      // ALSO
      // "CASTLEVANIA IV",
      // "CASTLEVANIA 4"
      "SUPER MARIO ALL-STARS",
      "ACTRAISER",
      "F-ZERO",
      "SUPER PUNCH-OUT",
      "DONKEY KONG COUNTRY 2",
      "TETRIS ATTACK",
      "FINAL FANTASY IV",
      // ALSO
      // "FINAL FANTASY 4"
      "EARTHBOUND",
      "MEGA MAN X",
      "SECRET OF MANA",
      "SUPER MARIO RPG",
      "STAR FOX",
      "SUPER MARIO KART",
      "YOSHI'S ISLAND",
      "SUPER STREET FIGHTER II TURBO",
      // ALSO
      // "SUPER STREET FIGHTER 2 TURBO"
      "SUPER MARIO WORLD",
      "FINAL FANTASY VI",
      // ALSO
      // "FINAL FANTASY 6"
      "SUPER METROID",
      "CHRONO TRIGGER",
      "LEGEND OF ZELDA: LINK TO THE PAST",
      // ALSO
      // "ZELDA: LINK TO THE PAST",
      // "LINK TO THE PAST"
    ]
  },

  {
    id: 22,
    name: "Parts of the Human Body",
    nameAsRule: "Your password must be an organ in the human body.",
    failedMessage: "[PASS] might be found in your body, but can't be found in the normal human.",
    possible: [
      "SKELETON",
      "TEETH",
      "TOUNGUE",
      "PAROTID GLANDS",
      "SUBMANDIBULAR GLANDS",
      "SUBLINGUAL GLANDS",
      "PHARYNX",
      "ESOPHAGUS",
      "STOMACH",
      "SMALL INTESTINE",
      // ALSO
      // "DUODENUM",
      // "JEJUNUM",
      // "ILEUM"
      "LARGE INTESTINE",
      // ALSO
      // "CECUM",
      // "COLON"
      // "ASCENDING COLON",
      // "DESCENDING COLON",
      // "TRANSVERSE COLON",
      // "SIGMOID COLON"
      "RECTUM",
      "LIVER",
      "GALLBLADDER",
      "MESENTERY",
      "PANCREAS",
      "ANAL CANAL",
      "NASAL CAVITY",
      "PHARYNX",
      "LARYNX",
      "TRACHEA",
      "BRONCHI",
      "LUNGS",
      "DIAPHRAGM",
      "KIDNEYS",
      "URETER",
      "BLADDER",
      "URETHRA",
      "OVARIES",
      "FALLOPIAN TUBES",
      "UTERUS",
      "VAGINA",
      "VULVA",
      "CLITORIS",
      "TESTES",
      "EPIDIDYMIS",
      "VAS DEFERENS",
      "SEMINAL VESICLES",
      "PROSTATE",
      "BULBOURETHRAL GLANDS",
      "PENIS",
      "SCROTUM",
      "PITUITARY GLAND",
      "PINEAL GLAND",
      "THYROID GLAND",
      // ALSO
      // "THYROID"
      "PARATHYROID GLANDS",
      "ADRENAL GLANDS",
      "PANCREAS",
      "HEART",
      "ARTERIES",
      // ALSO
      // "ARTERY"
      "VEINS",
      // ALSO
      // "VEIN"
      "CAPILLARIES",
      // ALSO
      // "CAPILLARY"
      "LYMPHATIC VESSEL",
      "LYMPH NODE",
      "BONE MARROW",
      "THYMUS",
      "SPLEEN",
      "TONSILS",
      "INTERSTITIUM",
      "BRAIN",
      "BRAINSTEM",
      "CEREBELLUM",
      "SPINAL CORD",
      // ALSO
      // "SPINE"
      "VENTRICULAR SYSTEM",
      "NERVES",
      // ALSO
      // "CRANIAL NERVES",
      // "SPINAL NERVES",
      // "GANGLIA",
      // "ENTERIC NERVOUS SYSTEM"
      "EYE",
      "CORNEA",
      "IRIS",
      "CILIARY BODY",
      "LENS",
      "RETINA",
      "EAR",
      "EARDRUM",
      "EARLOBE",
      "MIDDLE EAR",
      "OSSICLES",
      "INNER EAR",
      "COCHLEA",
      "VESTIBULE",
      "SEMICIRCULAR CANAL",
      "OLFACTORY EPITHELIUM",
      "SKIN",
      "MAMMARY GLANDS",
      "SUBCUTANEOUS TISSUE"
    ]
  },

  {
    id: 23,
    name: "1980's US One-Hit Wonders",
    nameAsRule: "Your password must be the name of a one-hit wonder band from the 1980s.",
    failedMessage: "[PASS] is not considered a 1980s one-hit wonder, according to VH1.",
    possible: [
      "DEXYS MIDNIGHT RUNNERS",
      "FLOCK OF SEAGULLS",
      "A-HA",
      "SOFT CELL",
      "TONI BASIL",
      "MODERN ENGLISH",
      "BOW WOW WOW",
      "KAJAGOOGOO",
      "FRANKIE GOES TO HOLLYWOOD",
      "GARY NUMAN",
      "ANIMOTION",
      "ROB BASE & DJ E-Z ROCK",
      // ALSO
      // "ROB BASE AND DJ E-Z ROCK"
      "THOMAS DOLBY",
      "BIG COUNTRY",
      "NENA",
      "MEN WITHOUT HATS",
      "DEAD OR ALIVE",
      "ROCKWELL",
      "TWISTED SISTER",
      "MICHAEL SEMBELLO",
      "EDDY GRANT",
      "EDIE BRICKWELL & NEW BOHEMIANS",
      // ALSO
      // "EDIE BRICKWELL AND NEW BOHEMIANS"
      "MUSICAL YOUTH",
      "CUTTING CREW",
      "STACEY Q",
      "JOHN PARR",
      "MADNESS",
      "THE VAPORS",
      "BOBBY MCFERRIN",
      "QUARTERFLASH",
      "JOHN WAITE",
      "THE WAITRESSES",
      "TOM TOM CLUB",
      "WEATHER GIRLS",
      "LIPPS, INC.",
      "BRUCE WILLIS",
      "MATTHEW WILDER",
      "THE BUGGLES",
      "TIMBUK 3",
      "SHANNON",
      "WALL OF VOODOO",
      "ROBBIE NEVIL",
      "GEORGIA SATELLITES",
      "PRETTY POISON",
      "YELLO",
      "PHILIP BAILEY",
      "NENEH CHERRY",
      "AFTER THE FIRE",
      "MARY JANE GIRLS",
      "TACO",
      "CHRIS DEBURGH",
      "JOHNNY KEMP",
      "TIL TUESDAY",
      "JERMAINE STEWART",
      "DON JOHNSON",
      "THE OUTFIELD",
      "NU SHOOZ",
      "E.U.",
      "XTC",
      "ORAN",
      "ROBBIE DUPREE",
      "BOOMTOWN RATS",
      "THE JEFF HEALY BAND",
      "MARTIKA",
      "PETER SCHILLING",
      "T'PAU",
      "HAROLD FALTERMEYER",
      "JACK WAGNER",
      "SWING OUT SISTER",
      "PAUL HARDCASTLE",
      "INFORMATION SOCIETY",
      "BERTIE HIGGINS",
      "J.J. FAD",
      "GENERAL PUBLIC",
      "ALDO NOVA",
      "ALANNA MYLES",
      "EDDIE MURPHY",
      "JOSIE COTTON",
      "RED RIDER",
      "PAUL LEKAKIS",
      "THE CHURCH",
      "ZIGGY MARLEY AND THE MELODY MAKERS",
      "PATRICE RUSHEN",
      "VIXEN",
      "NIK KERSHAW",
      "RODNEY DANGERFIELD",
      "HAIRCUT 100",
      // ALSO
      // "HAIRCUT ONE HUNDRED"
      "GLORIA LORING & CARL ANDERSON",
      "FRANK STALLONE",
      "L.A. GUNS",
      "CLUB NOUVEAU",
      "MIDNIGHT OIL",
      "THE FABULOUS THUNDERBIRDS",
      "WILL TO POWER",
      "BUCKNER & GARCIA",
      // ALSO
      // "BUCKNER AND GARCIA"
      "MICHAEL DAMIAN",
      "CLARENCE CLEMONS"
    ]
  },

  {
    id: 24,
    name: "1990's US One-Hit Wonders",
    nameAsRule: "Your password must be the name of a one-hit wonder band from the 1990s.",
    failedMessage: "[PASS] is not considered a 1990s one-hit wonder, according to Wikipedia.",
    possible: [
      "JANE CHILD",
      "SINEAD O'CONNOR",
      "MELLOW MAN ACE",
      "VANILLA ICE",
      "ELECTRONIC",
      "CANDYMAN",
      "DEEE-LITE",
      "EMF",
      "GERARDO",
      "DNA",
      "TOM COCHRANE",
      "RIGHT SAID FRED",
      "SIR MIX-A-LOT",
      "HOUSE OF PAIN",
      "POSITIVE K",
      "PAPERBOY",
      "DUICE",
      "95 SOUTH",
      "TAG TEAM",
      "ROBIN S.",
      "BLIND MELON",
      "HADDAWAY",
      "THE PROCLAIMERS",
      "4 NON BLONDES",
      "THE BREEDERS",
      "CORONA",
      "AHMAD",
      "INI KAMOZE",
      "TOADIES",
      "EVERYTHING BUT THE GIRL",
      "DEEP BLUE SOMETHING",
      "SKEE-LO",
      "LOS DEL RIO",
      "DIONNE FARRIS",
      "JOAN OSBORNE",
      "NONCHALANT",
      "DISHWALLA",
      "SPACEHOG",
      "CRUCIAL CONFLICT",
      "PRIMITIVE RADIO GODS",
      "THE CARDIGANS",
      "DUNCAN SHEIK",
      "THE VERVE PIPE",
      "OMC",
      "WHITE TOWN",
      "TRACEY LEE",
      "AQUA",
      "FIONA APPLE",
      "MEREDITH BROOKS",
      "SHAWN COLVIN",
      "HANSON",
      "LORD TARIQ AND PETER GUNZ",
      "CHUMBAWAMBA",
      "MARCY PLAYGROUND",
      "THE VERVE",
      "HARVEY DANGER",
      "SEMISONIC",
      "NATALIE IMBRUGLIA",
      "EAGLE-EYE CHERRY",
      "LIT",
      "LOU BEGA",
      "NEW RADICALS",
      "SPORTY THIEVZ",
      "TAL BACHMAN",
      "LEN",
      "MACY GRAY",
      "BBMAK"
    ]
  },

  {
    id: 25,
    name: "2000's US One-Hit Wonders",
    nameAsRule: "Your password must be the name of a one-hit wonder band from the 2000s.",
    failedMessage: "[PASS] is not considered a 2000s one-hit wonder, according to Wikipedia.",
    possible: [
      "HOKU",
      "NINE DAYS",
      "SAMANTHA MUMBA",
      "WHEATUS",
      "BAHA MEN",
      "DREAM",
      "SR-71",
      "CRAZY TOWN",
      "AMERICAN HI-FI",
      "EDEN'S CRUSH",
      "AFROMAN",
      "BLU CANTRELL",
      "WILLA FORD",
      "THE CALLING",
      "VANESSA CARLTON",
      "TRUTH HURTS",
      "KHIA",
      "TWEET",
      "TRAPT",
      "T.A.T.U.",
      "SMILEZ AND SOUTHSTAR",
      "BONE CRUSHER",
      "THE ATARIS",
      "THE DARKNESS",
      "FOUNTAINS OF WAYNE",
      "LUMIDEE",
      "KEVIN LYTTLE",
      "J-KWON",
      "RYAN CABRERA",
      "YELLOWCARD",
      "HOWIE DAY",
      "AMERIE",
      "THE CLICK FIVE",
      "JAMES BLUNT",
      "D4L",
      "DANIEL POWTER",
      "SNOW PATROL",
      "JIBBS",
      "DJ WEBSTAR AND YOUNG B",
      "THE PACK",
      "YOUNG DRO",
      "AUGUSTANA",
      "HELLOGOODBYE",
      "GNARLS BARKLEY",
      "RICH BOY",
      "MIMS",
      "HUEY",
      "HURRICANE CHRIS",
      "YAEL NAIM",
      "FLOBOTS",
      "METRO STATION",
      "ESTELLE",
      "THE VERONICAS",
      "ASHER ROTH"
    ]
  },

  {
    id: 26,
    name: "Western Art Periods",
    nameAsRule: "Your password must be the name of a Western art period or movement.",
    failedMessage: "[PASS] is not a Western art period, according to Wikipedia.",
    possible: [
      "EARLY CHRISTIAN",
      "MIGRATION PERIOD",
      // ALSO
      // "MIGRATION"
      "ANGLO-SAXON",
      "VISIGOTHIC",
      "PRE-ROMANESQUE",
      "INSULAR",
      "VIKING",
      "BYZANTINE",
      "MEROVINGIAN",
      "CAROLINGIAN",
      "OTTONIAN",
      "ROMANESQUE",
      "NORMAN-SICILIAN",
      "GOTHIC",
      "RENAISSANCE",
      // ALSO
      // "ITALIAN RENAISSANCE",
      // "LATE RENAISSANCE"
      "MANNERISM",
      "BAROQUE",
      "ROCOCO",
      "NEOCLASSICISM",
      "ROMANTICISM",
      "NAZARENE MOVEMENT",
      "DUSSELDORF SCHOOL",
      "HUDSON RIVER SCHOOL",
      "LUMINISM",
      // ALSO
      // "AMERICAN ART STYLE"
      "NORWICH SCHOOL",
      "BIEDERMEIER",
      "PHOTOGRAPHY",
      "REALISM",
      "BARBIZON SCHOOL",
      "PEREDVIZHNIKI",
      "HAGUE SCHOOL",
      "AMERICAN BARBIZON SCHOOL",
      "SPANISH ECLECTICISM",
      // ALSO
      // "ECLECTICISM"
      "MACCHIAIOLI",
      "PRE-RAPHAELITE BROTHERHOOD",
      "MODERN",
      // ALSO
      // "MODERN ART"
      "COS COB ART COLONY",
      "IMPRESSIONISM",
      "ARTS AND CRAFTS MOVEMENT",
      // ALSO
      // "ARTS AND CRAFTS"
      "TONALISM",
      "SYMBOLISM",
      "POST-IMPRESSIONISM",
      "LES NABIS",
      "CLOISONNISM",
      "SYNTHETISM",
      "NEO-IMPRESSIONISM",
      "POINTILLISM",
      "DIVISIONISM",
      "ART NOUVEAU",
      "RUSSIAN AVANT-GARDE",
      "YOUNG POLAND",
      "HAGENBUND",
      "FAUVISM",
      "EXPRESSIONISM",
      "DIE BRUCKE",
      "DER BLAUE REITER",
      "BLOOMSBURY GROUP",
      "CUBISM",
      "ORPHISM",
      "PURISM",
      "ASHCAN SCHOOL",
      "ART DECO",
      "FUTURISM",
      "RAYONISM",
      "SYNCHROMISM",
      "UNIVERSAL FLOWERING",
      "VORTICISM",
      "BIOMORPHISM",
      "SUPREMATISM",
      "DADA",
      "PROLETKULT",
      "DE STIJL",
      "PITTURA METAFISICA",
      "BAUHAUS",
      "CONSTRUCTIVISM",
      "PRECISIONISM",
      "SURREALISM",
      "DEVETSIL",
      "GROUP OF SEVEN",
      "HARLEM RENAISSANCE",
      "AMERICAN SCENE PAINTING",
      "NEW OBJECTIVITY",
      "GRUPO MONTPARNASSE",
      "NORTHWEST SCHOOL",
      "SOCIAL REALISM",
      // ALSO
      // "SOCIALIST REALISM"
      "ALLIANZ",
      "ABSTRACT EXPRESSIONISM",
      "ACTION PAINTING",
      "COLOR FIELD PAINTING",
      "OUTSIDER ART",
      "VIENNA SCHOOL FO FANTASTIC REALISM",
      "NEO-DADA",
      "POP ART",
      "NEW REALISM",
      "MINIMALISM",
      "CONCEPTUAL ART",
      "GRAFFITI",
      "PSYCHEDELIC ART",
      "OP ART",
      "PHOTOREALISM",
      "DECONSTRUCTIVISM",
      "POSTMODERN ART",
      "NEOISM",
      "TOYISM"
    ]
  },

  {
    id: 27,
    name: "Modern and Post-Modern Western Architectural Styles",
    nameAsRule: "Your password must be the name of a Modern or Post-Modern Western architectural style or school.",
    failedMessage: "[PASS] is not a style or school used in Western architecture.",
    possible: [
      "AVANT-GARDE",
      "PARAMETRICISM",
      "CHICAGO SCHOOL",
      "FUNCTIONALISM",
      "FUTURISM",
      "EXPRESSIONISM",
      "AMSTERDAM SCHOOL",
      "ORGANIC",
      "NEW OBJECTIVITY",
      "RATIONALISM",
      "BAUHAUS",
      "DE STIJL",
      "MODERNE",
      "ART DECO",
      "MODERNISM",
      "INTERNATIONAL STYLE",
      // ALSO
      // "INTERNATIONAL"
      "USONIAN",
      "MID-CENTURY MODERN",
      "GOOGIE",
      "BRUTALISM",
      "STRUCTURALISM",
      "METABOLIST",
      "DANISH FUNTIONALISM",
      // ALSO
      // "FUNCTIONALISM"
      "STRUCTURAL EXPRESSIONISM",
      "RANCH",
      "CONSTRUCTIVISM",
      "POSTCONSTRUCTIVISM",
      "STALINIST",
      "FASCIST",
      "SHED STYLE",
      // ALSO
      // "SHED"
      "ARCOLOGY",
      "DECONSTRUCTIVISM",
      "CRITICLA REGIONALISM",
      "BLOBITECTURE",
      "HIGH-TECH",
      "HOSTILE",
      "INTERACTIVE",
      "SUSTAINABLE",
      "EARTHSHIP",
      "NEO-FUTURISM",
      "NEW CLASSICAL"
    ]
  },

  {
    id: 28,
    name: "Classic Board Games",
    nameAsRule: "Your password must be a classic board game.",
    hint: "Classic, in this case, refers to popular games published before 2000.",
    failedMessage: "[PASS] must be one of those new games. Try again.",
    possible: [
      "LIFE",	
      // ALSO
      // "GAME OF LIFE"
      "CLUE",
      // ALSO
      // "CLUEDO"
      "CATAN",
      // ALSO
      // "SETTLERS OF CATAN"
      "MONOPOLY",
      "TRIVIAL PURSUIT",
      "RISK",
      "BOGGLE",
      "BATTLESHIP",
      "SCRABBLE",
      "CANDY LAND",
      "STRATEGO",
      "AXIS & ALLIES",
      "CHESS",
      "CHECKERS",
      "BACKGAMMON",
      "CHINESE CHECKERS",
      "BLOKUS",
      "CONNECT FOUR",
      "TWISTER",
      "OPERATION",
      "DON'T BREAK THE ICE",
      "OPERATION",
      "HUNGRY HUNGRY HIPPOS",
      "MOUSE TRAP",
      "JENGA",
      "DOMINOES",
      "CHUTES AND LADDERS",
      // ALSO
      // "SNAKES AND LADDERS"
      "TROUBLE",
      "SORRY",
      "YAHTZEE",
      "PICTIONARY",
      "SCATTERGORIES",
      "PARCHEESI",
      "GUESS WHO",
      "BALDERDASH",
      "TABOO",
      "CRANIUM",
      "HI HO CHERRY-O",
      "LUDO",
      "OTHELLO",
      "MANCALA",
      "PERFECTION",
      "CODENAMES"
    ]
  },

  {
    id: 29,
    name: "Periodic Table of Elements",
    nameAsRule: "Your password must be an element on the Periodic Table.",
    failedMessage: "[PASS]? Next you'll tell me unobtanium is real. Try again.",
    possible: [
      "ACTINIUM",
      "ALUMINUM",
      "AMERICIUM",
      "ANTIMONY",
      "ARGON",
      "ARSENIC",
      "ASTATINE",
      "BARIUM",
      "BERKELIUM",
      "BERYLLIUM",
      "BISMUTH",
      "BOHRIUM",
      "BORON",
      "BROMINE",
      "CADMIUM",
      "CALCIUM",
      "CALIFORNIUM",
      "CARBON",
      "CERIUM",
      "CESIUM",
      "CHLORINE",
      "CHROMIUM",
      "COBALT",
      "COPPER",
      "CURIUM",
      "DARMSTADTIUM",
      "DUBNIUM",
      "DYSPROSIUM",
      "EINSTEINIUM",
      "ERBIUM",
      "EUROPIUM",
      "FERMIUM",
      "FLOURINE",
      "FRANCIUM",
      "GADOLINIUM",
      "GALLIUM",
      "GERMANIUM",
      "GOLD",
      "HAFNIUM",
      "HASSIUM",
      "HELIUM",
      "HOLMIUM",
      "HYDROGEN",
      "INDIUM",
      "IODINE",
      "IRIDIUM",
      "IRON",
      "KRYPTON",
      "LANTHANUM",
      "LAWRENCIUM",
      "LEAD",
      "LITHIUM",
      "LUTETIUM",
      "MAGNESIUM",
      "MANGANESE",
      "MEITNERIUM",
      "MENDELEVIUM",
      "MERCURY",
      "MOLYBDENUM",
      "NEODYMIUM",
      "NEON",
      "NEPTUNIUM",
      "NICKEL",
      "NIOBIUM",
      "NITROGEN",
      "NOBELIUM",
      "OGANESSON",
      "OSMIUM",
      "OXYGEN",
      "PALLADIUM",
      "PHOSPHORUS",
      "PLATINUM",
      "PLUTONIUM",
      "POTASSIUM",
      "PRASEODYMIUM",
      "PROMETHIUM",
      "PROTACTINIUM",
      "RADIUM",
      "RADON",
      "RHENIUM",
      "RHODIUM",
      "ROENTGENIUM",
      "RUBIDIUM",
      "RUTHENIUM",
      "RUTHERFORDIUM",
      "SAMARIUM",
      "SCANDIUM",
      "SEABORGIUM",
      "SELENIUM",
      "SILICON",
      "SILVER",
      "SODIUM",
      "STRONTIUM",
      "SULFUR",
      "TANTALUM",
      "TECHNETIUM",
      "TELLURIUM",
      "TERBIUM",
      "THALLIUM",
      "THORIUM",
      "THULIUM",
      "TIN",
      "TITANIUM",
      "TUNGSTEN",
      "UNUNBIUM",
      "UNUNHEXIUM",
      "UNUNQUADIUM",
      "UNUNSEPTIUM",
      "UNUNTRIUM",
      "URANIUM",
      "VANADIUM",
      "XENON",
      "YTTERBIUM",
      "YTTRIUM",
      "ZINC",
      "ZIRCONIUM"
    ]
  },

  {
    id: 30,
    name: "Gemstones Used in Jewelry",
    nameAsRule: "Your password must be a gemstone commonly used in jewelry.",
    failedMessage: "[PASS] isn't a commonly used gem according to a general survey of jewelers.",
    possible: [
      "ALEXANDRITE",
      "AMBER",
      "AMETHYST",
      "AMETRINE",
      "AQUAMARINE",
      "CITRINE",
      "DIAMOND",
      "EMERALD",
      "GARNET",
      "IOLITE",
      "JADE",
      "KUNZITE",
      "LAPIS LAZULI",
      "MOONSTONE",
      "MORGANITE",
      "OPAL",
      "PEARL",
      "PERIDOT",
      "ROSE QUARTZ",
      "RUBY",
      "SAPPHIRE",
      "SPINEL",
      "SUNSTONE",
      "TANZANITE",
      "TOPAZ",
      "TOURMALINE",
      "TURQUOISE",
      "ZIRCON",
      "AGATE",
      "AMAZONITE",
      "BLOODSTONE",
      "CARNELIAN",
      "CHALCEDONY",
      "CHRYSOPRASE",
      "CHRYSOBERYL",
      "CORAL",
      "JASPER",
      "LABRADORITE",
      "MALACHITE",
      "ONYX",
      "AMMOLITE",
      "LARIMAR",
      "RED BERYL",
      "ZOISITE",
      "CHRYSOCOLLA",
      "ANDALUSITE",
      "PARAIBA"
    ]
  },
  
  {
    id: 31,
    name: "Constellations",
    nameAsRule: "Your password must be a constellation.",
    failedMessage: "[PASS] isn't an officially recognized by the International Astronomical Union.",
    possible: [
      "ANDROMEDA",
      "ANTLIA",
      "APUS",
      "AQUARIUS",
      "AQUILA",
      "ARA",
      "ARIES",
      "AURIGA",
      "BOOTES",
      "CAELUM",
      "CAMELOPARDALIS",
      "CANCER",
      "CANES VENATICI",
      "CANIS MAJOR",
      "CANIS MINOR",
      "CAPRICORNUS",
      "CARINA",
      "CASSIOPEIA",
      "CENTAURUS",
      "CEPHEUS",
      "CETUS",
      "CHAMAELEON",
      "CIRCINUS",
      "COLUMBA",
      "COMA BERENICES",
      "CORONA AUSTRALIS",
      "CORONA BOREALIS",
      "CORVUS",
      "CRATER",
      "CRUX",
      "CYGNUS",
      "DELPHINUS",
      "DORADO",
      "DRACO",
      "EQUULEUS",
      "ERIDANUS",
      "FORNAX",
      "GEMINI",
      "GRUS",
      "HERCULES",
      "HOROLOGIUM",
      "HYDRA",
      "HYDRUS",
      "INDUS",
      "LACERTA",
      "LEO",
      "LEO MINOR",
      "LEPUS",
      "LIBRA",
      "LUPUS",
      "LYNX",
      "LYRA",
      "MENSA",
      "MICROSCOPIUM",
      "MONOCEROS",
      "MUSCA",
      "NORMA",
      "OCTANS",
      "OPHIUCHUS",
      "ORION",
      "PAVO",
      "PEGASUS",
      "PERSEUS",
      "PHOENIX",
      "PICTOR",
      "PISCES",
      "PISCIS AUSTRINUS",
      "PUPPIS",
      "PYXIS",
      "RETICULUM",
      "SAGITTA",
      "SAGITTARIUS",
      "SCORPIUS",
      "SCULPTOR",
      "SCUTUM",
      "SERPENS",
      "SEXTANS",
      "TAURUS",
      "TELESCOPIUM",
      "TRIANGULUM",
      "TRIANGULUM AUSTRALE",
      "TUCANA",
      "URSA MAJOR",
      "URSA MINOR",
      "VELA",
      "VIRGO",
      "VOLANS",
      "VULPECULA"
    ]
  }

];