
const challenges = [
  {
    id: 1,
    name: "Mortal Kombat",
    nameAsRule: "Your password must be a playable Mortal Kombat character",
    failedMessage: "[PASS] is not a playable Mortal Kombat character",
    possible: [
      "johnny cage",
      "kano",
      "liu kang",
      "raiden",
      "scorpion",
      "sonya blade",
      "sub-zero",
      "goro",
      "shang tsung",
      "reptile",
      "baraka",
      "jade",
      "jax",
      "kintaro",
      "kitana",
      "kung lao",
      "mileena",
      "noob saibot",
      "shao khan",
      "smoke",
      "chameleon",
      "cyrax",
      "ermac",
      "kabal",
      "khameleon",
      "motaro",
      "nightwolf",
      "rain",
      "sektor",
      "sheeva",
      "sindel",
      "stryker",
      "meat",
      "bo rai cho",
      "frost"
    ]
  },

  {
    id: 2,
    name: "Bob's Burgers",
    nameAsRule: "Your password MUST be the first name of a Bob's Burgers character",
    failedMessage: "[PASS] is not a Bob's Burgers character",
    possible: [
      "Mike",
      "Bob",
      "LINDA",
      "GENE",
      "LOUISE",
      "TINA",
      "TEDDY",
      "MORT",
      "RUDY",
      "JIMMY",
      "ANDY",
      "OLLIE",
      "JOCELYN",
      "TAMMY",
      "HELEN",
      "TREV",
      "MARSHMALLOW",
      "BOO BOO",
      "DARRYL",
      "PHILLIP",
      "ALEX",
      "ART",
      "RANDY",
      "KURT",
      "LOGAN",
      "SASHA"
    ]
  },

  /*

  {
    id: 3,
    name: "Words For Breasts (Recognized By The OED)",
    nameAsRule: "Your password MUST be a word the Oxford English Dictionary recognizes as a synonym for “breasts”",
    failedMessage: "The OED doesn't recognize [PASS] as a word for breasts.",
    possible: [
      "CHEST",
      "BUST",
      "BOSOM",
      "BOOBS",
      "KNOCKERS",
      "BOOBIES",
      "BOOBS",
      "BAZOOKAS",
      "MELONS",
      "JUBBLIES",
      "BUBBLIES",
      "ORBS",
      "GLOBES",
      "CHARLIES",
      "BAPS",
      "BAZOOMS",
      "CASABAS",
      "CHI CHIS",
      "NORKS",
      "TITS",
      "TITTIES",
      "JUGS",
      "HOOTERS",
      "CANS"
    ]
  },

  */

  {
    id: 4,
    name: "African Countries",
    nameAsRule: "Your password MUST be a country in Africa",
    failedMessage: "[PASS] is not an African country",
    possible: [
      "ALGERIA",
      "ANGOLA",
      "BENIN",
      "BOTSWANA",
      "Algeria",
      "Angola",
      "Benin",
      "Botswana",
      "Burkina Faso",
      "Burundi",
      "Cabo Verde",
      "Cameroon",
      "Central African Republic",
      "Chad",
      "Comoros",
      "Republic of the Congo",
      "Democratic Republic of the Congo",
      "Cote d'Ivoire",
      "Djibouti",
      "Egypt",
      "Equatorial Guinea",
      "Eritrea",
      "Eswatini",
      "Ethiopia",
      "Gabon",
      "Gambia",
      "Ghana",
      "Guinea",
      "Guinea-Bissau",
      "Kenya",
      "Lesotho",
      "Liberia",
      "Libya",
      "Madagascar",
      "Malawi",
      "Mali",
      "Mauritania",
      "Mauritius",
      "Morocco",
      "Mozambique",
      "Namibia",
      "Niger",
      "Nigeria",
      "Rwanda",
      "Senegal",
      "Seychelles",
      "Sierra Leone",
      "Somalia",
      "South Africa",
      "South Sudan",
      "Sudan",
      "Tanzania",
      "Togo",
      "Tunisia",
      "Uganda",
      "Zambia",
      "Zimbabwe"
    ]
  },

  {
    id: 5,
    name: "European Countries",
    nameAsRule: "Your password MUST be a country in Europe",
    failedMessage: "Sorry! [PASS] is not a European Country.",
    possible: [
      "Albania",
      "Andorra",
      "Armenia",
      "Austria",
      "Azerbaijan",
      "Belarus",
      "Belgium",
      "Bosnia and Herzegovina",
      "Bulgaria",
      "Croatia",
      "Cyprus",
      "Czechia",
      "Denmark",
      "Estonia",
      "Finland",
      "France",
      "Georgia",
      "Germany",
      "Greece",
      "Hungary",
      "Iceland",
      "Ireland",
      "Italy",
      "Kazakhstan",
      "Kosovo",
      "Latvia",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Malta",
      "Moldova",
      "Monaco",
      "Montenegro",
      "Netherlands",
      "North Macedonia",
      "Norway",
      "Poland",
      "Portugal",
      "Romania",
      "Russia",
      "San Marino",
      "Serbia",
      "Slovakia",
      "Slovenia",
      "Spain",
      "Sweden",
      "Switzerland",
      "Turkey",
      "Ukraine",
      "United Kingdom",
      "Vatican City"
    ]
  },

  {
    id: 6,
    name: "NFL Teams",
    nameAsRule: "Your password MUST be an NFL football team name",
    failedMessage: "Sorry! There are no [PASS] in the NFL.",
    possible: [
      "CARDINALS",
      "FALCONS",
      "PANTHERS",
      "BEARS",
      "COWBOYS",
      "LIONS",
      "PACKERS",
      "RAMS",
      "VIKINGS",
      "SAINTS",
      "GIANTS",
      "EAGLES",
      "49ERS",
      "SEAHAWKS",
      "BUCCANEERS",
      "FOOTBALL TEAM",
      "RAVENS",
      "BILLS",
      "BENGALS",
      "BROWNS",
      "BRONCOS",
      "TEXANS",
      "COLTS",
      "JAGUARS",
      "CHIEFS",
      "RAIDERS",
      "CHARGERS",
      "DOLPHINS",
      "PATRIOTS",
      "STEELERS",
      "TITANS"
    ]
  },

  {
    id: 7,
    name: "State Birds",
    nameAsRule: "Your password MUST be a U.S. state bird",
    failedMessage: "Sorry, no US State made [PASS] their official bird.",
    possible: [
      "YELLOWHAMMER",
      "WILLOW PTARMIGAN",
      "WREN",
      "MOCKINGBIRD",
      "QUAIL",
      "LARK",
      "ROBIN",
      "BLUE HEN",
      "THRUSH",
      "THRASHER",
      "GOOSE",
      "BLUEBIRD",
      "CARDINAL",
      "GOLDFINCH",
      "FINCH",
      "MEADOWLARK",
      "PELICAN",
      "CHICKADEE",
      "ORIOLE",
      "LOON",
      "ROADRUNNER",
      "FRUIT DOVE",
      "GROUSE",
      "RHODE ISLAND RED",
      "PHEASANT",
      "GULL",
    ]
  },

  {
    id: 8,
    name: "Synonyms for Blue",
    nameAsRule: "Your password MUST be a synonym for blue",
    failedMessage: "Thesaurus.com doesn't list [PASS] as a synonym for blue.",
    possible: [
      "AZURE",
      "COBALT",
      "SAPPIRE",
      'CERULEAN',
      "NAVY",
      "ULTRAMARINE",
      "LAPIS",
      "INDIGO",
      "AQUAMARIE",
      "TURQUOISE",
      "TEAL",
      "CYAN",
      "DEPRESSED",
      "DOWN",
      "SAD",
      "SADDENED",
      "UNHAPPY",
      "MELANCHOLY",
      "MISERABLE",
      "SORROWFUL",
      "GLOOMY",
      "DEJECTED",
      "DOWNHEARTED",
      "DISHEARTENED",
      "DESPONDENT",
      "DISPIRITED",
      "LOW",
      "LOW SPIRITED",
      "HEAVY HEARTED",
      "GLUM",
      "MOROSE",
      "DISMAL",
      "DOWNCAST",
      "CAST DOWN",
      "TEARFUL",
      "DOWN IN THE DUMPS",
      "DOWN IN THE MOUTH",
      "FED UP",
      "INDECENT",
      "DIRTY",
      "RUDE",
      "COARSE",
      "VULGAR",
      "BAWDY",
      "LEWD",
      "RACY"
    ]
  },

  {
    id: 9,
    name: "My Little Ponies",
    nameAsRule: "Your password MUST be a My Little Pony (unicorns count)",
    failedMessage: "[PASS] isn't a My Little Pony! 🦄",
    possible: [
      "TWILIGHT SPARKLE",
      "APPLEJACK",
      "FLUTTERSHY",
      "RARITY",
      "PINKIE PIE",
      "RAINBOW DASH",
      "APPLE BLOOM",
      "SCOOTALOO",
      "SWEETIE BELLE",
      "BABS SEED",
      "PRINCESS CELESTIA",
      "PRINCESS LUNA",
      "PRINCE BLUEBLOOD",
      "SHINING ARMOR",
      "PROCESS CADENCE",
      "FLURRY HEART",
      "PRINCESS AMORE",
      "GRANNY SMITH",
      "BIG MCINTOSH",
      "BRAEBURN",
      "AUNT ORANGE",
      "UNCLE ORANGE",
      "HAYSEED TURNIP TRUCK",
      "APPLE STRUDEL",
      "AUNTIE APPLESAUCE",
      "APPLE ROSE",
      "GOLDIE DELICIOUS",
      "BRIGHT MAC",
      "PEAR BUTTER",
      "MAUD PIE",
      "STARLIGHT GLIMMER",
      "SUNSET SHIMMER",
      "TEMPEST SHADOW"
    ]
  },

  {
    id: 9,
    name: "Leafy Green Vegetables",
    nameAsRule: "Your password MUST be a leafy green vegetable",
    failedMessage: "[PASS] is not a leafy green vegeable",
    possible: [
      "ARUGULA",
      "BIBB",
      "CABBAGE",
      "LETTUCE",
      "BEET GREENS",
      "COLLARD GREENS",
      "DANDELION GREENS",
      "KALE",
      "MICROGREENS",
      "MUSTARD GREENS",
      "RAPINI",
      "BROCCOLI RABE",
      "ROMAINE",
      "SPINACH",
      "SWISS CHARD",
      "WATERCRESS",
      "ENDIVE",
      "BOK CHOY",
      "TURNIP GREENS",
      "PARSLEY"
    ]
  }

];