import { Justice } from "./_types";
import {
  PRES_THEODORE_ROOSEVELT,
  PRES_FDR,
  PRES_JFK,
  PRES_LBJ,
  PRES_NIXON,
  PRES_FORD,
  PRES_REAGAN,
  PRES_GHW_BUSH,
  PRES_CLINTON,
  PRES_GW_BUSH,
  PRES_OBAMA,
  PRES_TRUMP,
  PRES_BIDEN,
  PRES_THUNDERTON,
  PRES_FIREBOTTOM,
  PRES_VON_DECREE,
} from "./_presidents";

// ────────────────────────────────────────────────────────────
// CURRENT JUSTICES (as of 2025)
// ────────────────────────────────────────────────────────────

export const justiceCurrent: Justice[] = [
  {
    id: 1,
    name: "John Roberts",
    image: "john_roberts.webp",
    description:
      "Chief Justice who occasionally surprises conservatives by having a spine. Mostly for show. Obsessed with the Court's institutional reputation — the one thing that doesn't technically exist anymore.",
    justiceType: "current",
    gender: "M",
    birthYear: 1955,
    nominatedBy: PRES_GW_BUSH,
    religion: "Catholic",
    ethnicity: "White",
    stats: {
      logic: 8,
      charisma: 7,
      empathy: 5,
      integrity: 6,
      succeptibility: 4,
      partyLoyalty: 6,
    },
    weaknesses: { flattery: 6, bribery: 3, blackmail: 4, threats: 3 },
  },
  {
    id: 2,
    name: "Clarence Thomas",
    image: "clarence_thomas.webp",
    description:
      "Hasn't asked a question from the bench in a decade. Extremely committed to originalism, which he interprets as 'whatever Harlan Crow thinks.' Believes recusal is for the weak.",
    justiceType: "current",
    gender: "M",
    birthYear: 1948,
    nominatedBy: PRES_GHW_BUSH,
    religion: "Catholic",
    ethnicity: "Black",
    stats: {
      logic: 6,
      charisma: 3,
      empathy: 2,
      integrity: 2,
      succeptibility: 3,
      partyLoyalty: 10,
    },
    weaknesses: { flattery: 4, bribery: 9, blackmail: 7, threats: 2 },
  },
  {
    id: 3,
    name: "Samuel Alito",
    image: "alito.webp",
    description:
      "Believes the Constitution means exactly what he wants it to mean. Known for his concerned frown and his unconcerned decisions. Wrote Dobbs while his wife's car had an upside-down flag.",
    justiceType: "current",
    gender: "M",
    birthYear: 1950,
    nominatedBy: PRES_GW_BUSH,
    religion: "Catholic",
    ethnicity: "White",
    stats: {
      logic: 7,
      charisma: 4,
      empathy: 2,
      integrity: 4,
      succeptibility: 3,
      partyLoyalty: 10,
    },
    weaknesses: { flattery: 7, bribery: 5, blackmail: 4, threats: 2 },
  },
  {
    id: 4,
    name: "Sonia Sotomayor",
    image: "sotomayor.webp",
    description:
      "First Latina Supreme Court Justice. Writes dissents so passionate they should come with a tissue. Has exceptional empathy and uses it aggressively. Will outlive the bad decisions.",
    justiceType: "current",
    gender: "F",
    birthYear: 1954,
    nominatedBy: PRES_OBAMA,
    religion: "Catholic",
    ethnicity: "Hispanic",
    stats: {
      logic: 8,
      charisma: 8,
      empathy: 9,
      integrity: 8,
      succeptibility: 4,
      partyLoyalty: 7,
    },
    weaknesses: { flattery: 5, bribery: 2, blackmail: 3, threats: 4 },
  },
  {
    id: 5,
    name: "Elena Kagan",
    image: "kagan.webp",
    description:
      "Former Harvard Law Dean who thought she'd seen everything. Smart, sharp, and methodically writing dissents into the void. Will destroy your argument in a footnote without breaking a sweat.",
    justiceType: "current",
    gender: "F",
    birthYear: 1960,
    nominatedBy: PRES_OBAMA,
    religion: "Jewish",
    ethnicity: "Jewish",
    stats: {
      logic: 9,
      charisma: 7,
      empathy: 7,
      integrity: 8,
      succeptibility: 3,
      partyLoyalty: 7,
    },
    weaknesses: { flattery: 4, bribery: 2, blackmail: 3, threats: 3 },
  },
  {
    id: 6,
    name: "Neil Gorsuch",
    image: "gorsuch.webp",
    description:
      "Textualist who believes in reading the Constitution as written — as long as the writing leads somewhere conservative. Stole a Senate seat and made it look like philosophy.",
    justiceType: "current",
    gender: "M",
    birthYear: 1967,
    nominatedBy: PRES_TRUMP,
    religion: "Protestant",
    ethnicity: "White",
    stats: {
      logic: 7,
      charisma: 5,
      empathy: 4,
      integrity: 6,
      succeptibility: 4,
      partyLoyalty: 8,
    },
    weaknesses: { flattery: 5, bribery: 4, blackmail: 4, threats: 3 },
  },
  {
    id: 7,
    name: "Brett Kavanaugh",
    image: "kavanaugh.webp",
    description:
      "Famously loves calendars. And beer. And being angry at the Senate. Not necessarily in that order. His confirmation hearing was the most dramatic TV event of 2018 that nobody wanted.",
    justiceType: "current",
    gender: "M",
    birthYear: 1965,
    nominatedBy: PRES_TRUMP,
    religion: "Catholic",
    ethnicity: "White",
    stats: {
      logic: 6,
      charisma: 5,
      empathy: 4,
      integrity: 4,
      succeptibility: 5,
      partyLoyalty: 9,
    },
    weaknesses: { flattery: 6, bribery: 6, blackmail: 8, threats: 4 },
  },
  {
    id: 8,
    name: "Amy Coney Barrett",
    image: "amyconey.webp",
    description:
      "Confirmed in record time before an election. Claims faith doesn't influence her decisions. Her decisions respectfully disagree. Very calm about absolutely everything, which is somehow terrifying.",
    justiceType: "current",
    gender: "F",
    birthYear: 1972,
    nominatedBy: PRES_TRUMP,
    religion: "Catholic",
    ethnicity: "White",
    stats: {
      logic: 7,
      charisma: 6,
      empathy: 5,
      integrity: 6,
      succeptibility: 4,
      partyLoyalty: 9,
    },
    weaknesses: { flattery: 5, bribery: 3, blackmail: 4, threats: 3 },
  },
  {
    id: 9,
    name: "Ketanji Brown Jackson",
    image: "ketanji.webp",
    description:
      "First Black woman on the Supreme Court. Knows what a biologist is. Sat through a Senate confirmation hearing where a senator asked her to define 'woman' and survived with her dignity intact.",
    justiceType: "current",
    gender: "F",
    birthYear: 1970,
    nominatedBy: PRES_BIDEN,
    religion: "Protestant",
    ethnicity: "Black",
    stats: {
      logic: 9,
      charisma: 8,
      empathy: 8,
      integrity: 9,
      succeptibility: 3,
      partyLoyalty: 7,
    },
    weaknesses: { flattery: 4, bribery: 2, blackmail: 2, threats: 4 },
  },
];

// ────────────────────────────────────────────────────────────
// HISTORICAL JUSTICES
// ────────────────────────────────────────────────────────────

export const justiceHistorical: Justice[] = [
  {
    id: 10,
    name: "Thurgood Marshall",
    image: "thurgood_marshall.webp",
    description:
      "Argued Brown v. Board before he was even on the Court. Spent his tenure watching the world fail to live up to its promise. The most consequential lawyer in American history, which is saying something for a guy who also became a Justice.",
    justiceType: "historical",
    gender: "M",
    birthYear: 1908,
    nominatedBy: PRES_LBJ,
    religion: "Protestant",
    ethnicity: "Black",
    stats: {
      logic: 9,
      charisma: 9,
      empathy: 10,
      integrity: 10,
      succeptibility: 2,
      partyLoyalty: 6,
    },
    weaknesses: { flattery: 3, bribery: 1, blackmail: 2, threats: 3 },
  },
  {
    id: 11,
    name: "Ruth Bader Ginsburg",
    image: "",
    description:
      "The Notorious RBG. Five feet of pure legal steel who dismantled gender discrimination one meticulous argument at a time. Should have retired earlier but was too stubborn to let the bad guys win. History is complicated.",
    justiceType: "historical",
    gender: "F",
    birthYear: 1933,
    nominatedBy: PRES_CLINTON,
    religion: "Jewish",
    ethnicity: "Jewish",
    stats: {
      logic: 10,
      charisma: 9,
      empathy: 9,
      integrity: 10,
      succeptibility: 2,
      partyLoyalty: 6,
    },
    weaknesses: { flattery: 3, bribery: 1, blackmail: 2, threats: 2 },
  },
  {
    id: 12,
    name: "William Rehnquist",
    image: "rehnquist.webp",
    description:
      "Chief Justice who added gold stripes to his robe to stand out. Conservative stalwart who presided over Clinton's impeachment trial with full ceremonial stripes. The robes were the most interesting thing about him.",
    justiceType: "historical",
    gender: "M",
    birthYear: 1924,
    nominatedBy: PRES_NIXON,
    religion: "Protestant",
    ethnicity: "White",
    stats: {
      logic: 8,
      charisma: 6,
      empathy: 4,
      integrity: 5,
      succeptibility: 4,
      partyLoyalty: 9,
    },
    weaknesses: { flattery: 5, bribery: 4, blackmail: 5, threats: 3 },
  },
  {
    id: 13,
    name: "Antonin Scalia",
    image: "scalia.webp",
    description:
      "Originalist extraordinaire who believed the Constitution meant exactly what men with slave plantations intended in 1789. Was best friends with RBG despite being her polar opposite. Had opinions. Loudly.",
    justiceType: "historical",
    gender: "M",
    birthYear: 1936,
    nominatedBy: PRES_REAGAN,
    religion: "Catholic",
    ethnicity: "White",
    stats: {
      logic: 9,
      charisma: 9,
      empathy: 3,
      integrity: 7,
      succeptibility: 3,
      partyLoyalty: 9,
    },
    weaknesses: { flattery: 8, bribery: 3, blackmail: 4, threats: 2 },
  },
  {
    id: 14,
    name: "Sandra Day O'Connor",
    image: "sandra-day.webp",
    description:
      "First woman on the Supreme Court. The swing vote before swing votes were cool. A genuine moderate who confused everyone by sometimes ruling based on 'what seems fair.' Retired and immediately regretted it.",
    justiceType: "historical",
    gender: "F",
    birthYear: 1930,
    nominatedBy: PRES_REAGAN,
    religion: "Protestant",
    ethnicity: "White",
    stats: {
      logic: 8,
      charisma: 7,
      empathy: 7,
      integrity: 8,
      succeptibility: 6,
      partyLoyalty: 5,
    },
    weaknesses: { flattery: 6, bribery: 3, blackmail: 3, threats: 3 },
  },
  {
    id: 15,
    name: "John Paul Stevens",
    image: "",
    description:
      "Appointed by a Republican, became the liberal lion of the Court over 35 years. Served until age 90. Had absolutely no time for your nonsense. Wore a bow tie. Was correct.",
    justiceType: "historical",
    gender: "M",
    birthYear: 1920,
    nominatedBy: PRES_FORD,
    religion: "Protestant",
    ethnicity: "White",
    stats: {
      logic: 9,
      charisma: 7,
      empathy: 8,
      integrity: 9,
      succeptibility: 3,
      partyLoyalty: 2,
    },
    weaknesses: { flattery: 4, bribery: 2, blackmail: 2, threats: 3 },
  },
  {
    id: 16,
    name: "Byron White",
    image: "",
    description:
      "Former NFL running back turned Supreme Court Justice — because why not. Moved unpredictably on the field and on the bench. Dissented on Roe v. Wade, proving that a JFK appointment is not a guarantee.",
    justiceType: "historical",
    gender: "M",
    birthYear: 1917,
    nominatedBy: PRES_JFK,
    religion: "Catholic",
    ethnicity: "White",
    stats: {
      logic: 7,
      charisma: 6,
      empathy: 5,
      integrity: 7,
      succeptibility: 5,
      partyLoyalty: 6,
    },
    weaknesses: { flattery: 5, bribery: 4, blackmail: 4, threats: 4 },
  },
  {
    id: 17,
    name: "Hugo Black",
    image: "hugo_black.webp",
    description:
      "Former KKK member who became a staunch civil liberties absolutist. The most dramatic personal redemption arc in Supreme Court history. Believed the First Amendment literally meant ALL speech. ALL of it.",
    justiceType: "historical",
    gender: "M",
    birthYear: 1886,
    nominatedBy: PRES_FDR,
    religion: "Protestant",
    ethnicity: "White",
    stats: {
      logic: 8,
      charisma: 7,
      empathy: 6,
      integrity: 6,
      succeptibility: 5,
      partyLoyalty: 7,
    },
    weaknesses: { flattery: 6, bribery: 4, blackmail: 7, threats: 4 },
  },
  {
    id: 18,
    name: "Oliver Wendell Holmes Jr.",
    image: "wendell.webp",
    description:
      "Civil War veteran turned legal legend. Served until age 90. Famous for 'great cases make bad law.' Said you can't shout fire in a crowded theater and spent the rest of history being misquoted about it.",
    justiceType: "historical",
    gender: "M",
    birthYear: 1841,
    nominatedBy: PRES_THEODORE_ROOSEVELT,
    religion: "Protestant",
    ethnicity: "White",
    stats: {
      logic: 10,
      charisma: 8,
      empathy: 5,
      integrity: 8,
      succeptibility: 3,
      partyLoyalty: 4,
    },
    weaknesses: { flattery: 5, bribery: 2, blackmail: 3, threats: 2 },
  },
  {
    id: 25,
    name: "Judge Roy Bean",
    image: "",
    description:
      "Self-proclaimed 'The Law West of the Pecos.' Held court in a saloon. Death by hanging available within 24 hours — guaranteed. His courtroom had a bar, and that's not a metaphor. Has cited 'my gut' in 47 opinions.",
    justiceType: "historical",
    gender: "M",
    birthYear: 1825,
    religion: "Protestant",
    ethnicity: "White",
    stats: {
      logic: 3,
      charisma: 8,
      empathy: 3,
      integrity: 4,
      succeptibility: 5,
      partyLoyalty: 5,
    },
    weaknesses: { flattery: 7, bribery: 8, blackmail: 6, threats: 2 },
  },
];

// ────────────────────────────────────────────────────────────
// FICTIONAL JUSTICES (based on well-known fictional characters)
// ────────────────────────────────────────────────────────────

export const justiceFictional: Justice[] = [
  {
    id: 20,
    name: "Lady Justice",
    image: "",
    description:
      "The actual personification of Justice herself, somehow appointed to the Court. Frustratingly impartial. Her blindfold is real, and she's deeply annoyed that no one else has one. Has been waiting for this court to justify her presence since 1776.",
    justiceType: "fictional",
    gender: "F",
    birthYear: 0,
    religion: "Other",
    ethnicity: "Other",
    stats: {
      logic: 10,
      charisma: 10,
      empathy: 10,
      integrity: 10,
      succeptibility: 0,
      partyLoyalty: 0,
    },
    weaknesses: { flattery: 0, bribery: 0, blackmail: 0, threats: 0 },
  },
  {
    id: 21,
    name: "Judge Dredd",
    image: "",
    description:
      "I AM THE LAW. Does not recognize the concept of appeals. His gavel is also a gun. Has issued seventeen sentences during oral arguments. The other justices are scared of him but will not say so on the record.",
    justiceType: "fictional",
    gender: "M",
    birthYear: 2079,
    nominatedBy: PRES_VON_DECREE,
    religion: "Protestant",
    ethnicity: "White",
    stats: {
      logic: 7,
      charisma: 4,
      empathy: 1,
      integrity: 9,
      succeptibility: 1,
      partyLoyalty: 3,
    },
    weaknesses: { flattery: 1, bribery: 1, blackmail: 1, threats: 1 },
  },
  {
    id: 22,
    name: "The Honorable Vibes McGee",
    image: "",
    description:
      "Decides all cases based entirely on vibes. Never reads the briefs. Once ruled in favor of a plaintiff because 'she just seemed more chill.' Legal scholars are baffled that her decisions hold up on appeal.",
    justiceType: "fictional",
    gender: "F",
    birthYear: 1975,
    nominatedBy: PRES_FIREBOTTOM,
    religion: "Other",
    ethnicity: "White",
    stats: {
      logic: 2,
      charisma: 10,
      empathy: 8,
      integrity: 4,
      succeptibility: 10,
      partyLoyalty: 3,
    },
    weaknesses: { flattery: 10, bribery: 4, blackmail: 3, threats: 2 },
  },
  {
    id: 27,
    name: "Justice Ham Sandwich",
    image: "",
    description:
      "Any DA can indict a ham sandwich. This one was indicted, convicted, and somehow ended up on the Supreme Court. Often hungry. Every opinion involves food in some capacity. Once ruled that the right to bear arms includes the right to bear condiments.",
    justiceType: "fictional",
    gender: "M",
    birthYear: 2020,
    nominatedBy: PRES_THUNDERTON,
    religion: "Protestant",
    ethnicity: "White",
    stats: {
      logic: 1,
      charisma: 5,
      empathy: 2,
      integrity: 8,
      succeptibility: 9,
      partyLoyalty: 5,
    },
    weaknesses: { flattery: 6, bribery: 10, blackmail: 5, threats: 3 },
  },
  {
    id: 32,
    name: "Leslie Knope",
    image: "",
    description:
      "Former Parks & Recreation Director who ascended to the Supreme Court through sheer organized enthusiasm and a binder for every occasion. Believes deeply in government, waffles, and the American people — in that order.",
    justiceType: "fictional",
    gender: "F",
    birthYear: 1975,
    nominatedBy: PRES_BIDEN,
    religion: "Protestant",
    ethnicity: "White",
    stats: {
      logic: 8,
      charisma: 9,
      empathy: 10,
      integrity: 10,
      succeptibility: 4,
      partyLoyalty: 8,
    },
    weaknesses: { flattery: 9, bribery: 1, blackmail: 1, threats: 2 },
  },
  {
    id: 33,
    name: "Al Swearengen",
    image: "",
    description:
      "Proprietor of the Gem Saloon, Deadwood, South Dakota. Appointed himself to the Court through a combination of intimidation, bribery, and a handshake deal nobody wants to explain. Has never lost a negotiation. Will not lose this one.",
    justiceType: "fictional",
    gender: "M",
    birthYear: 1845,
    nominatedBy: PRES_VON_DECREE,
    religion: "Protestant",
    ethnicity: "White",
    stats: {
      logic: 8,
      charisma: 9,
      empathy: 4,
      integrity: 2,
      succeptibility: 3,
      partyLoyalty: 4,
    },
    weaknesses: { flattery: 4, bribery: 9, blackmail: 8, threats: 3 },
  },
  {
    id: 34,
    name: "The Dude",
    image: "dude.webp",
    description:
      "The Dude abides. Applied to the Court without knowing he'd applied. Brings his own rug to hearings. Has recused himself from every case involving nihilism. Technically his bowling average is cited in three opinions.",
    justiceType: "fictional",
    gender: "M",
    birthYear: 1958,
    nominatedBy: PRES_FIREBOTTOM,
    religion: "Other",
    ethnicity: "White",
    stats: {
      logic: 3,
      charisma: 7,
      empathy: 7,
      integrity: 6,
      succeptibility: 9,
      partyLoyalty: 2,
    },
    weaknesses: { flattery: 7, bribery: 5, blackmail: 4, threats: 1 },
  },
  {
    id: 35,
    name: "Othello",
    image: "",
    description:
      "Moor of Venice, former military general, now somehow on the Supreme Court. A man of great passion and even greater susceptibility to insinuation. Extraordinarily just until someone whispers in his ear — and then things escalate quickly.",
    justiceType: "fictional",
    gender: "M",
    birthYear: 1603,
    religion: "Protestant",
    ethnicity: "Black",
    stats: {
      logic: 6,
      charisma: 8,
      empathy: 8,
      integrity: 7,
      succeptibility: 9,
      partyLoyalty: 5,
    },
    weaknesses: { flattery: 5, bribery: 3, blackmail: 10, threats: 6 },
  },
];

// ────────────────────────────────────────────────────────────
// CELEBRITY JUSTICES (real celebrities imagined on the bench)
// ────────────────────────────────────────────────────────────

export const justiceCelebrity: Justice[] = [
  {
    id: 28,
    name: "Elon Musk",
    image: "",
    description:
      "Acquired the Supreme Court in a hostile takeover and now sits on it. Claims he's just 'optimizing the process.' Has renamed the bench 'X Court.' Will live-stream oral arguments. Fired three clerks for not 'shipping opinions fast enough.'",
    justiceType: "celebrity",
    gender: "M",
    birthYear: 1971,
    nominatedBy: PRES_THUNDERTON,
    religion: "Other",
    ethnicity: "White",
    stats: {
      logic: 7,
      charisma: 7,
      empathy: 1,
      integrity: 2,
      succeptibility: 6,
      partyLoyalty: 8,
    },
    weaknesses: { flattery: 9, bribery: 3, blackmail: 7, threats: 2 },
  },
  {
    id: 29,
    name: "Peter Thiel",
    image: "",
    description:
      "Libertarian billionaire who wants to disrupt tradition, due process, and also possibly mortality. Abstains from cases involving the deep state on principle. Has a separate underground chamber where he writes his concurrences. Believes competition is for losers.",
    justiceType: "celebrity",
    gender: "M",
    birthYear: 1967,
    nominatedBy: PRES_THUNDERTON,
    religion: "Other",
    ethnicity: "White",
    stats: {
      logic: 9,
      charisma: 4,
      empathy: 1,
      integrity: 5,
      succeptibility: 2,
      partyLoyalty: 7,
    },
    weaknesses: { flattery: 4, bribery: 2, blackmail: 8, threats: 1 },
  },
  {
    id: 30,
    name: "Judge Judy",
    image: "",
    description:
      "Byrd, I'm done listening. Has been tougher than the Supreme Court for thirty years and now she's making it official. Writes opinions in a tone that implies you are an idiot who wasted her time. Once dismissed a case and the parties' marriages simultaneously.",
    justiceType: "celebrity",
    gender: "F",
    birthYear: 1942,
    nominatedBy: PRES_THUNDERTON,
    religion: "Jewish",
    ethnicity: "Jewish",
    stats: {
      logic: 9,
      charisma: 9,
      empathy: 5,
      integrity: 8,
      succeptibility: 2,
      partyLoyalty: 5,
    },
    weaknesses: { flattery: 3, bribery: 2, blackmail: 4, threats: 1 },
  },
  {
    id: 31,
    name: "Mary-Kate & Ashley Olsen",
    image: "olsen-twins.webp",
    description:
      "Appointed jointly as one justice, which raises constitutional questions no one wants to answer. Vote in perfect synchrony — except when they don't, which creates a paradox. Have a combined net worth larger than the GDP of three nations. Their opinions are impeccably styled.",
    justiceType: "celebrity",
    gender: "F",
    birthYear: 1986,
    nominatedBy: PRES_FIREBOTTOM,
    religion: "Protestant",
    ethnicity: "White",
    stats: {
      logic: 6,
      charisma: 10,
      empathy: 6,
      integrity: 5,
      succeptibility: 7,
      partyLoyalty: 4,
    },
    weaknesses: { flattery: 9, bribery: 6, blackmail: 5, threats: 3 },
  },
];

export const justices: Justice[] = [...justiceCurrent, ...justiceHistorical, ...justiceFictional, ...justiceCelebrity];
