import { Justice } from "./_types";
import {
  PRES_WASHINGTON,
  PRES_JOHN_ADAMS,
  PRES_JACKSON,
  PRES_BENJAMIN_HARRISON,
  PRES_GRANT,
  PRES_EISENHOWER,
  PRES_THEODORE_ROOSEVELT,
  PRES_FDR,
  PRES_JFK,
  PRES_LBJ,
  PRES_NIXON,
  PRES_FORD,
  PRES_REAGAN,
  PRES_GHW_BUSH,
  PRES_CLINTON,
  PRES_GW_BUSH,
  PRES_OBAMA,
  PRES_TRUMP,
  PRES_BIDEN,
  PRES_SNOOP_DOGG,
  PRES_VERMIN_SUPREME,
  PRES_BJORK,
  PRES_BILL_HICKS,
  PRES_HUNTER_S_THOMPSON,
  PRES_LIBERACE,
} from "./_presidents";

// ────────────────────────────────────────────────────────────
// CURRENT JUSTICES (as of 2025)
// ────────────────────────────────────────────────────────────

export const justiceCurrent: Justice[] = [
  {
    id: 1,
    name: "John Roberts",
    image: "john_roberts.webp",
    description:
      "Chief Justice who occasionally surprises conservatives by having a spine. Mostly for show. Obsessed with the Court's institutional reputation — the one thing that doesn't technically exist anymore.",
    justiceType: "current",
    gender: "M",
    birthYear: 1955,
    nominatedBy: PRES_GW_BUSH,
    religion: "Catholic",
    ethnicity: "White",
    stats: {
      logic: 8,
      charisma: 7,
      empathy: 5,
      integrity: 6,
      succeptibility: 4,
      partyLoyalty: 6,
    },
    weaknesses: { flattery: 6, bribery: 3, blackmail: 4, threats: 3 },
  },
  {
    id: 2,
    name: "Clarence Thomas",
    image: "clarence_thomas.webp",
    description:
      "Hasn't asked a question from the bench in a decade. Extremely committed to originalism, which he interprets as 'whatever Harlan Crow thinks.' Believes recusal is for the weak.",
    justiceType: "current",
    gender: "M",
    birthYear: 1948,
    nominatedBy: PRES_GHW_BUSH,
    religion: "Catholic",
    ethnicity: "Black",
    stats: {
      logic: 6,
      charisma: 3,
      empathy: 2,
      integrity: 2,
      succeptibility: 3,
      partyLoyalty: 10,
    },
    weaknesses: { flattery: 4, bribery: 9, blackmail: 7, threats: 2 },
  },
  {
    id: 3,
    name: "Samuel Alito",
    image: "alito.webp",
    description:
      "Believes the Constitution means exactly what he wants it to mean. Known for his concerned frown and his unconcerned decisions. Wrote Dobbs while his wife's car had an upside-down flag.",
    justiceType: "current",
    gender: "M",
    birthYear: 1950,
    nominatedBy: PRES_GW_BUSH,
    religion: "Catholic",
    ethnicity: "White",
    stats: {
      logic: 7,
      charisma: 4,
      empathy: 2,
      integrity: 4,
      succeptibility: 3,
      partyLoyalty: 10,
    },
    weaknesses: { flattery: 7, bribery: 5, blackmail: 4, threats: 2 },
  },
  {
    id: 4,
    name: "Sonia Sotomayor",
    image: "sotomayor.webp",
    description:
      "First Latina Supreme Court Justice. Writes dissents so passionate they should come with a tissue. Has exceptional empathy and uses it aggressively. Will outlive the bad decisions.",
    justiceType: "current",
    gender: "F",
    birthYear: 1954,
    nominatedBy: PRES_OBAMA,
    religion: "Catholic",
    ethnicity: "Hispanic",
    stats: {
      logic: 8,
      charisma: 8,
      empathy: 9,
      integrity: 8,
      succeptibility: 4,
      partyLoyalty: 7,
    },
    weaknesses: { flattery: 5, bribery: 2, blackmail: 3, threats: 4 },
  },
  {
    id: 5,
    name: "Elena Kagan",
    image: "kagan.webp",
    description:
      "Former Harvard Law Dean who thought she'd seen everything. Smart, sharp, and methodically writing dissents into the void. Will destroy your argument in a footnote without breaking a sweat.",
    justiceType: "current",
    gender: "F",
    birthYear: 1960,
    nominatedBy: PRES_OBAMA,
    religion: "Jewish",
    ethnicity: "Jewish",
    stats: {
      logic: 9,
      charisma: 7,
      empathy: 7,
      integrity: 8,
      succeptibility: 3,
      partyLoyalty: 7,
    },
    weaknesses: { flattery: 4, bribery: 2, blackmail: 3, threats: 3 },
  },
  {
    id: 6,
    name: "Neil Gorsuch",
    image: "gorsuch.webp",
    description:
      "Textualist who believes in reading the Constitution as written — as long as the writing leads somewhere conservative. Stole a Senate seat and made it look like philosophy.",
    justiceType: "current",
    gender: "M",
    birthYear: 1967,
    nominatedBy: PRES_TRUMP,
    religion: "Protestant",
    ethnicity: "White",
    stats: {
      logic: 7,
      charisma: 5,
      empathy: 4,
      integrity: 6,
      succeptibility: 4,
      partyLoyalty: 8,
    },
    weaknesses: { flattery: 5, bribery: 4, blackmail: 4, threats: 3 },
  },
  {
    id: 7,
    name: "Brett Kavanaugh",
    image: "kavanaugh.webp",
    description:
      "Famously loves calendars. And beer. And being angry at the Senate. Not necessarily in that order. His confirmation hearing was the most dramatic TV event of 2018 that nobody wanted.",
    justiceType: "current",
    gender: "M",
    birthYear: 1965,
    nominatedBy: PRES_TRUMP,
    religion: "Catholic",
    ethnicity: "White",
    stats: {
      logic: 6,
      charisma: 5,
      empathy: 4,
      integrity: 4,
      succeptibility: 5,
      partyLoyalty: 9,
    },
    weaknesses: { flattery: 6, bribery: 6, blackmail: 8, threats: 4 },
  },
  {
    id: 8,
    name: "Amy Coney Barrett",
    image: "amyconey.webp",
    description:
      "Confirmed in record time before an election. Claims faith doesn't influence her decisions. Her decisions respectfully disagree. Very calm about absolutely everything, which is somehow terrifying.",
    justiceType: "current",
    gender: "F",
    birthYear: 1972,
    nominatedBy: PRES_TRUMP,
    religion: "Catholic",
    ethnicity: "White",
    stats: {
      logic: 7,
      charisma: 6,
      empathy: 5,
      integrity: 6,
      succeptibility: 4,
      partyLoyalty: 9,
    },
    weaknesses: { flattery: 5, bribery: 3, blackmail: 4, threats: 3 },
  },
  {
    id: 9,
    name: "Ketanji Brown Jackson",
    image: "ketanji.webp",
    description:
      "First Black woman on the Supreme Court. Knows what a biologist is. Sat through a Senate confirmation hearing where a senator asked her to define 'woman' and survived with her dignity intact.",
    justiceType: "current",
    gender: "F",
    birthYear: 1970,
    nominatedBy: PRES_BIDEN,
    religion: "Protestant",
    ethnicity: "Black",
    stats: {
      logic: 9,
      charisma: 8,
      empathy: 8,
      integrity: 9,
      succeptibility: 3,
      partyLoyalty: 7,
    },
    weaknesses: { flattery: 4, bribery: 2, blackmail: 2, threats: 4 },
  },
];

// ────────────────────────────────────────────────────────────
// HISTORICAL JUSTICES
// ────────────────────────────────────────────────────────────

export const justiceHistorical: Justice[] = [
  {
    id: 10,
    name: "Thurgood Marshall",
    image: "thurgood_marshall.webp",
    description:
      "Argued Brown v. Board before he was even on the Court. Spent his tenure watching the world fail to live up to its promise. The most consequential lawyer in American history, which is saying something for a guy who also became a Justice.",
    justiceType: "historical",
    gender: "M",
    birthYear: 1908,
    nominatedBy: PRES_LBJ,
    religion: "Protestant",
    ethnicity: "Black",
    stats: {
      logic: 9,
      charisma: 9,
      empathy: 10,
      integrity: 10,
      succeptibility: 2,
      partyLoyalty: 6,
    },
    weaknesses: { flattery: 3, bribery: 1, blackmail: 2, threats: 3 },
  },
  {
    id: 11,
    name: "Ruth Bader Ginsburg",
    image: "rbg.webp",
    description:
      "The Notorious RBG. Five feet of pure legal steel who dismantled gender discrimination one meticulous argument at a time. Should have retired earlier but was too stubborn to let the bad guys win. History is complicated.",
    justiceType: "historical",
    gender: "F",
    birthYear: 1933,
    nominatedBy: PRES_CLINTON,
    religion: "Jewish",
    ethnicity: "Jewish",
    stats: {
      logic: 10,
      charisma: 9,
      empathy: 9,
      integrity: 10,
      succeptibility: 2,
      partyLoyalty: 6,
    },
    weaknesses: { flattery: 3, bribery: 1, blackmail: 2, threats: 2 },
  },
  {
    id: 12,
    name: "William Rehnquist",
    image: "rehnquist.webp",
    description:
      "Chief Justice who added gold stripes to his robe to stand out. Conservative stalwart who presided over Clinton's impeachment trial with full ceremonial stripes. The robes were the most interesting thing about him.",
    justiceType: "historical",
    gender: "M",
    birthYear: 1924,
    nominatedBy: PRES_NIXON,
    religion: "Protestant",
    ethnicity: "White",
    stats: {
      logic: 8,
      charisma: 6,
      empathy: 4,
      integrity: 5,
      succeptibility: 4,
      partyLoyalty: 9,
    },
    weaknesses: { flattery: 5, bribery: 4, blackmail: 5, threats: 3 },
  },
  {
    id: 13,
    name: "Antonin Scalia",
    image: "scalia.webp",
    description:
      "Originalist extraordinaire who believed the Constitution meant exactly what men with slave plantations intended in 1789. Was best friends with RBG despite being her polar opposite. Had opinions. Loudly.",
    justiceType: "historical",
    gender: "M",
    birthYear: 1936,
    nominatedBy: PRES_REAGAN,
    religion: "Catholic",
    ethnicity: "White",
    stats: {
      logic: 9,
      charisma: 9,
      empathy: 3,
      integrity: 7,
      succeptibility: 3,
      partyLoyalty: 9,
    },
    weaknesses: { flattery: 8, bribery: 3, blackmail: 4, threats: 2 },
  },
  {
    id: 14,
    name: "Sandra Day O'Connor",
    image: "sandra-day.webp",
    description:
      "First woman on the Supreme Court. The swing vote before swing votes were cool. A genuine moderate who confused everyone by sometimes ruling based on 'what seems fair.' Retired and immediately regretted it.",
    justiceType: "historical",
    gender: "F",
    birthYear: 1930,
    nominatedBy: PRES_REAGAN,
    religion: "Protestant",
    ethnicity: "White",
    stats: {
      logic: 8,
      charisma: 7,
      empathy: 7,
      integrity: 8,
      succeptibility: 6,
      partyLoyalty: 5,
    },
    weaknesses: { flattery: 6, bribery: 3, blackmail: 3, threats: 3 },
  },
  {
    id: 15,
    name: "John Paul Stevens",
    image: "stevens.webp",
    description:
      "Appointed by a Republican, became the liberal lion of the Court over 35 years. Served until age 90. Had absolutely no time for your nonsense. Wore a bow tie. Was correct.",
    justiceType: "historical",
    gender: "M",
    birthYear: 1920,
    nominatedBy: PRES_FORD,
    religion: "Protestant",
    ethnicity: "White",
    stats: {
      logic: 9,
      charisma: 7,
      empathy: 8,
      integrity: 9,
      succeptibility: 3,
      partyLoyalty: 2,
    },
    weaknesses: { flattery: 4, bribery: 2, blackmail: 2, threats: 3 },
  },
  {
    id: 16,
    name: "Byron White",
    image: "byron_white.webp",
    description:
      "Former NFL running back turned Supreme Court Justice — because why not. Moved unpredictably on the field and on the bench. Dissented on Roe v. Wade, proving that a JFK appointment is not a guarantee.",
    justiceType: "historical",
    gender: "M",
    birthYear: 1917,
    nominatedBy: PRES_JFK,
    religion: "Catholic",
    ethnicity: "White",
    stats: {
      logic: 7,
      charisma: 6,
      empathy: 5,
      integrity: 7,
      succeptibility: 5,
      partyLoyalty: 6,
    },
    weaknesses: { flattery: 5, bribery: 4, blackmail: 4, threats: 4 },
  },
  {
    id: 17,
    name: "Hugo Black",
    image: "hugo_black.webp",
    description:
      "Former KKK member who became a staunch civil liberties absolutist. The most dramatic personal redemption arc in Supreme Court history. Believed the First Amendment literally meant ALL speech. ALL of it.",
    justiceType: "historical",
    gender: "M",
    birthYear: 1886,
    nominatedBy: PRES_FDR,
    religion: "Protestant",
    ethnicity: "White",
    stats: {
      logic: 8,
      charisma: 7,
      empathy: 6,
      integrity: 6,
      succeptibility: 5,
      partyLoyalty: 7,
    },
    weaknesses: { flattery: 6, bribery: 4, blackmail: 7, threats: 4 },
  },
  {
    id: 18,
    name: "Oliver Wendell Holmes Jr.",
    image: "wendell.webp",
    description:
      "Civil War veteran turned legal legend. Served until age 90. Famous for 'great cases make bad law.' Said you can't shout fire in a crowded theater and spent the rest of history being misquoted about it.",
    justiceType: "historical",
    gender: "M",
    birthYear: 1841,
    nominatedBy: PRES_THEODORE_ROOSEVELT,
    religion: "Protestant",
    ethnicity: "White",
    stats: {
      logic: 10,
      charisma: 8,
      empathy: 5,
      integrity: 8,
      succeptibility: 3,
      partyLoyalty: 4,
    },
    weaknesses: { flattery: 5, bribery: 2, blackmail: 3, threats: 2 },
  },
  {
    id: 50,
    name: "John Jay",
    image: "john_jay.webp",
    description:
      "The very first Chief Justice of the United States, and arguably the most powerful man ever to resign in disgust. Co-wrote the Federalist Papers, negotiated a deeply unpopular treaty, and then just… left. Has been 'too good for this' since 1795.",
    justiceType: "historical",
    gender: "M",
    birthYear: 1745,
    nominatedBy: PRES_WASHINGTON,
    religion: "Protestant",
    ethnicity: "White",
    stats: {
      logic: 9,
      charisma: 7,
      empathy: 6,
      integrity: 10,
      succeptibility: 2,
      partyLoyalty: 6,
    },
    weaknesses: { flattery: 4, bribery: 1, blackmail: 2, threats: 2 },
  },
  {
    id: 51,
    name: "John Marshall",
    image: "john_marshall.webp",
    description:
      "The man who decided the Supreme Court could decide things. Invented judicial review out of thin air, wrote the opinion, and dared anyone to stop him. Nobody did. The Court has been powerful ever since and this is entirely his fault.",
    justiceType: "historical",
    gender: "M",
    birthYear: 1755,
    nominatedBy: PRES_JOHN_ADAMS,
    religion: "Protestant",
    ethnicity: "White",
    stats: {
      logic: 10,
      charisma: 8,
      empathy: 5,
      integrity: 9,
      succeptibility: 2,
      partyLoyalty: 7,
    },
    weaknesses: { flattery: 5, bribery: 2, blackmail: 3, threats: 1 },
  },
  {
    id: 52,
    name: "John Marshall Harlan",
    image: "marshall_harlan.webp",
    description:
      "The Great Dissenter. Sole dissenter in Plessy v. Ferguson. Former slaveholder who became a passionate civil rights champion — a redemption arc so dramatic it would be rejected as unbelievable. Was right about everything for 30 years before anyone admitted it.",
    justiceType: "historical",
    gender: "M",
    birthYear: 1833,
    nominatedBy: PRES_GRANT,
    religion: "Protestant",
    ethnicity: "White",
    stats: {
      logic: 9,
      charisma: 7,
      empathy: 9,
      integrity: 10,
      succeptibility: 2,
      partyLoyalty: 3,
    },
    weaknesses: { flattery: 4, bribery: 1, blackmail: 2, threats: 3 },
  },
  {
    id: 53,
    name: "Earl Warren",
    image: "earl_warren.webp",
    description:
      "Eisenhower called appointing him the greatest mistake of his presidency. Warren presided over Brown v. Board, Miranda, and the Warren Commission. A Republican governor who became the most consequential liberal Chief Justice in history. Eisenhower was deeply embarrassed.",
    justiceType: "historical",
    gender: "M",
    birthYear: 1891,
    nominatedBy: PRES_EISENHOWER,
    religion: "Protestant",
    ethnicity: "White",
    stats: {
      logic: 8,
      charisma: 9,
      empathy: 9,
      integrity: 9,
      succeptibility: 4,
      partyLoyalty: 2,
    },
    weaknesses: { flattery: 6, bribery: 2, blackmail: 3, threats: 3 },
  },
  {
    id: 54,
    name: "Roger B. Taney",
    image: "taney.webp",
    description:
      "Author of Dred Scott v. Sandford, the worst Supreme Court decision in American history. Ruled that Black people had no rights the white man was bound to respect. Died while the country was literally at war over whether he was correct. He was not.",
    justiceType: "historical",
    gender: "M",
    birthYear: 1777,
    nominatedBy: PRES_JACKSON,
    religion: "Catholic",
    ethnicity: "White",
    stats: {
      logic: 7,
      charisma: 6,
      empathy: 1,
      integrity: 3,
      succeptibility: 4,
      partyLoyalty: 10,
    },
    weaknesses: { flattery: 7, bribery: 5, blackmail: 5, threats: 3 },
  },
  {
    id: 55,
    name: "Henry Billings Brown",
    image: "henry_billings_brown.webp",
    description:
      "Author of the Plessy v. Ferguson majority opinion, which established the 'separate but equal' doctrine. Just a regular guy who wrote one of the most consequential racist opinions in legal history and then lived another 17 years. Seems chill about it.",
    justiceType: "historical",
    gender: "M",
    birthYear: 1836,
    nominatedBy: PRES_BENJAMIN_HARRISON,
    religion: "Protestant",
    ethnicity: "White",
    stats: {
      logic: 6,
      charisma: 5,
      empathy: 2,
      integrity: 3,
      succeptibility: 6,
      partyLoyalty: 8,
    },
    weaknesses: { flattery: 6, bribery: 5, blackmail: 4, threats: 4 },
  },
];

// ────────────────────────────────────────────────────────────
// FICTIONAL JUSTICES (based on well-known fictional characters)
// ────────────────────────────────────────────────────────────

export const justiceFictional: Justice[] = [
  {
    id: 21,
    name: "Judge Dredd",
    image: "dredd.webp",
    description:
      "I AM THE LAW. Does not recognize the concept of appeals. His gavel is also a gun. Has issued seventeen sentences during oral arguments. The other justices are scared of him but will not say so on the record.",
    justiceType: "fictional",
    gender: "M",
    birthYear: 2079,
    nominatedBy: PRES_VERMIN_SUPREME,
    religion: "Protestant",
    ethnicity: "White",
    stats: {
      logic: 7,
      charisma: 4,
      empathy: 1,
      integrity: 9,
      succeptibility: 1,
      partyLoyalty: 3,
    },
    weaknesses: { flattery: 1, bribery: 1, blackmail: 1, threats: 1 },
  },
  {
    id: 32,
    name: "Leslie Knope",
    image: "knope.webp",
    description:
      "Former Parks & Recreation Director who ascended to the Supreme Court through sheer organized enthusiasm and a binder for every occasion. Believes deeply in government, waffles, and the American people — in that order.",
    justiceType: "fictional",
    gender: "F",
    birthYear: 1975,
    nominatedBy: PRES_BIDEN,
    religion: "Protestant",
    ethnicity: "White",
    stats: {
      logic: 8,
      charisma: 9,
      empathy: 10,
      integrity: 10,
      succeptibility: 4,
      partyLoyalty: 8,
    },
    weaknesses: { flattery: 9, bribery: 1, blackmail: 1, threats: 2 },
  },
  {
    id: 33,
    name: "Al Swearengen",
    image: "swearengen.webp",
    description:
      "Proprietor of the Gem Saloon, Deadwood, South Dakota. Appointed himself to the Court through a combination of intimidation, bribery, and a handshake deal nobody wants to explain. Has never lost a negotiation. Will not lose this one.",
    justiceType: "fictional",
    gender: "M",
    birthYear: 1845,
    nominatedBy: PRES_HUNTER_S_THOMPSON,
    religion: "Protestant",
    ethnicity: "White",
    stats: {
      logic: 8,
      charisma: 9,
      empathy: 4,
      integrity: 2,
      succeptibility: 3,
      partyLoyalty: 4,
    },
    weaknesses: { flattery: 4, bribery: 9, blackmail: 8, threats: 3 },
  },
  {
    id: 34,
    name: "The Dude",
    image: "dude.webp",
    description:
      "The Dude abides. Applied to the Court without knowing he'd applied. Brings his own rug to hearings. Has recused himself from every case involving nihilism. Technically his bowling average is cited in three opinions.",
    justiceType: "fictional",
    gender: "M",
    birthYear: 1958,
    nominatedBy: PRES_SNOOP_DOGG,
    religion: "Other",
    ethnicity: "White",
    stats: {
      logic: 3,
      charisma: 7,
      empathy: 7,
      integrity: 6,
      succeptibility: 9,
      partyLoyalty: 2,
    },
    weaknesses: { flattery: 7, bribery: 5, blackmail: 4, threats: 1 },
  },
  {
    id: 35,
    name: "Othello",
    image: "othello.webp",
    description:
      "Moor of Venice, former military general, now somehow on the Supreme Court. A man of great passion and even greater susceptibility to insinuation. Extraordinarily just until someone whispers in his ear — and then things escalate quickly.",
    justiceType: "fictional",
    gender: "M",
    birthYear: 1603,
    religion: "Protestant",
    ethnicity: "Black",
    stats: {
      logic: 6,
      charisma: 8,
      empathy: 8,
      integrity: 7,
      succeptibility: 9,
      partyLoyalty: 5,
    },
    weaknesses: { flattery: 5, bribery: 3, blackmail: 10, threats: 6 },
  },
  {
    id: 36,
    name: "Mentok The Mind Taker",
    image: "mentok.webp",
    description:
      "Villain-turned-justice from the Harvey Birdman universe, where superheroes became attorneys and this is somehow what followed. Cannot stop reading the minds of opposing counsel, which is cheating. Has been issued fourteen contempt warnings and considers each one a badge of honor.",
    justiceType: "fictional",
    gender: "M",
    birthYear: 1972,
    nominatedBy: PRES_SNOOP_DOGG,
    religion: "Other",
    ethnicity: "Other",
    stats: {
      logic: 4,
      charisma: 8,
      empathy: 3,
      integrity: 3,
      succeptibility: 8,
      partyLoyalty: 4,
    },
    weaknesses: { flattery: 8, bribery: 6, blackmail: 7, threats: 5 },
  },
  {
    id: 37,
    name: "Judge Doom",
    image: "doom.webp",
    description:
      "The villainous mastermind behind Toontown's destruction, now on the Supreme Court. Keeps a vat of Dip under the bench 'for procedural purposes.' His eyes spin when he's overruled, which is terrifying. Believed by some to be a Toon himself, which he vehemently denies in a very high-pitched voice.",
    justiceType: "fictional",
    gender: "M",
    birthYear: 1947,
    nominatedBy: PRES_LIBERACE,
    religion: "Protestant",
    ethnicity: "White",
    stats: {
      logic: 9,
      charisma: 6,
      empathy: 1,
      integrity: 3,
      succeptibility: 2,
      partyLoyalty: 9,
    },
    weaknesses: { flattery: 3, bribery: 4, blackmail: 5, threats: 2 },
  },
  {
    id: 38,
    name: "A DVD Boxed Set of Law & Order: SVU",
    image: "svu_box.webp",
    description:
      "In the Supreme Court, the people are represented by two separate yet equally important groups: the discs, and the case summaries on the back of the box. These are their stories. Has issued opinions in 500+ episodes and will not be stopped. Asks every petitioner 'but did you do it?' Has never presided over a case involving sexually based offenses without a nine-minute cold open.",
    justiceType: "fictional",
    gender: "M",
    birthYear: 1999,
    nominatedBy: PRES_HUNTER_S_THOMPSON,
    religion: "Other",
    ethnicity: "Other",
    stats: {
      logic: 7,
      charisma: 5,
      empathy: 0,
      integrity: 9,
      succeptibility: 1,
      partyLoyalty: 6,
    },
    weaknesses: { flattery: 2, bribery: 1, blackmail: 3, threats: 2 },
  },
];

// ────────────────────────────────────────────────────────────
// CELEBRITY JUSTICES (real celebrities imagined on the bench)
// ────────────────────────────────────────────────────────────

export const justiceCelebrity: Justice[] = [
  {
    id: 29,
    name: "Peter Thiel",
    image: "thiel.webp",
    description:
      "Libertarian billionaire who wants to disrupt tradition, due process, and also possibly mortality. Abstains from cases involving the deep state on principle. Has a separate underground chamber where he writes his concurrences. Believes competition is for losers.",
    justiceType: "celebrity",
    gender: "M",
    birthYear: 1967,
    nominatedBy: PRES_TRUMP,
    religion: "Other",
    ethnicity: "White",
    stats: {
      logic: 9,
      charisma: 4,
      empathy: 1,
      integrity: 5,
      succeptibility: 2,
      partyLoyalty: 7,
    },
    weaknesses: { flattery: 4, bribery: 2, blackmail: 8, threats: 1 },
  },
  {
    id: 30,
    name: "Judge Judy",
    image: "judy.webp",
    description:
      "Byrd, I'm done listening. Has been tougher than the Supreme Court for thirty years and now she's making it official. Writes opinions in a tone that implies you are an idiot who wasted her time. Once dismissed a case and the parties' marriages simultaneously.",
    justiceType: "celebrity",
    gender: "F",
    birthYear: 1942,
    nominatedBy: PRES_LIBERACE,
    religion: "Jewish",
    ethnicity: "Jewish",
    stats: {
      logic: 9,
      charisma: 9,
      empathy: 5,
      integrity: 8,
      succeptibility: 2,
      partyLoyalty: 5,
    },
    weaknesses: { flattery: 3, bribery: 2, blackmail: 4, threats: 1 },
  },
  {
    id: 31,
    name: "Mary-Kate & Ashley Olsen",
    image: "olsen-twins.webp",
    description:
      "Appointed jointly as one justice, which raises constitutional questions no one wants to answer. Vote in perfect synchrony — except when they don't, which creates a paradox. Have a combined net worth larger than the GDP of three nations. Their opinions are impeccably styled.",
    justiceType: "celebrity",
    gender: "F",
    birthYear: 1986,
    nominatedBy: PRES_BJORK,
    religion: "Protestant",
    ethnicity: "White",
    stats: {
      logic: 6,
      charisma: 10,
      empathy: 6,
      integrity: 5,
      succeptibility: 7,
      partyLoyalty: 4,
    },
    weaknesses: { flattery: 9, bribery: 6, blackmail: 5, threats: 3 },
  },
  {
    id: 39,
    name: "Judge Reinhold",
    image: "reinhold.webp",
    description:
      "A celebrity whose name already contains the word 'Judge,' which apparently qualifies him. Known for Beverly Hills Cop and that thing at the airport. Brings genuine warmth to oral arguments and absolutely no legal training whatsoever. Has recused himself from nothing because why would he.",
    justiceType: "celebrity",
    gender: "M",
    birthYear: 1957,
    nominatedBy: PRES_LIBERACE,
    religion: "Protestant",
    ethnicity: "White",
    stats: {
      logic: 5,
      charisma: 7,
      empathy: 6,
      integrity: 5,
      succeptibility: 7,
      partyLoyalty: 6,
    },
    weaknesses: { flattery: 8, bribery: 5, blackmail: 6, threats: 4 },
  },
  {
    id: 40,
    name: "Simon Cowell",
    image: "cowell.webp",
    description:
      "TV's harshest talent show judge now rules on constitutional law. His oral argument feedback is devastating, precise, and poorly reasoned. Once told a petitioner their brief was 'a bit karaoke.' High-waisted jeans. Zero empathy. Somehow winning.",
    justiceType: "celebrity",
    gender: "M",
    birthYear: 1959,
    nominatedBy: PRES_LIBERACE,
    religion: "Other",
    ethnicity: "White",
    stats: {
      logic: 7,
      charisma: 10,
      empathy: 2,
      integrity: 6,
      succeptibility: 3,
      partyLoyalty: 6,
    },
    weaknesses: { flattery: 4, bribery: 7, blackmail: 6, threats: 3 },
  },
  {
    id: 41,
    name: "Jerry Springer",
    image: "springer.webp",
    description:
      "Former mayor, former TV ringmaster, now somehow on the nation's highest court. Oral arguments have never been this chaotic or this watchable. Has twice asked attorneys to 'come out here and say that to the other guy's face.' Final Thought: maybe don't do that.",
    justiceType: "celebrity",
    gender: "M",
    birthYear: 1944,
    nominatedBy: PRES_BILL_HICKS,
    religion: "Jewish",
    ethnicity: "Jewish",
    stats: {
      logic: 5,
      charisma: 10,
      empathy: 7,
      integrity: 3,
      succeptibility: 8,
      partyLoyalty: 7,
    },
    weaknesses: { flattery: 8, bribery: 7, blackmail: 6, threats: 4 },
  },
  {
    id: 56,
    name: "Mr. Beast",
    image: "mrbeast.webp",
    description:
      "YouTuber with 300 million subscribers who spent $3.5 million to cure blindness and now wants to cure injustice. Approaches every case like a challenge video. Has attempted to give every plaintiff $10,000. His clerks are called 'the Beast Squad.' Trends on every platform whenever he rules.",
    justiceType: "celebrity",
    gender: "M",
    birthYear: 1998,
    nominatedBy: PRES_SNOOP_DOGG,
    religion: "Protestant",
    ethnicity: "White",
    stats: { logic: 6, charisma: 10, empathy: 9, integrity: 7, succeptibility: 8, partyLoyalty: 4 },
    weaknesses: { flattery: 10, bribery: 7, blackmail: 3, threats: 2 },
  },
  {
    id: 57,
    name: "The Undertaker",
    image: "undertaker.webp",
    description:
      "The Deadman. The Phenom. Presides from a darkened bench to the sound of a funeral gong. Has never lost a WrestleMania match and his legal record is similarly undefeated. His rulings arrive with dramatic thunder effects. Opposing counsel has forfeited by fear on three occasions.",
    justiceType: "celebrity",
    gender: "M",
    birthYear: 1965,
    nominatedBy: PRES_LIBERACE,
    religion: "Protestant",
    ethnicity: "White",
    stats: { logic: 7, charisma: 10, empathy: 4, integrity: 8, succeptibility: 3, partyLoyalty: 7 },
    weaknesses: { flattery: 3, bribery: 4, blackmail: 7, threats: 1 },
  },
];

export const justices: Justice[] = [...justiceCurrent, ...justiceHistorical, ...justiceFictional, ...justiceCelebrity];
