const fPlusDeck = {
  description: "fart",
  cards: [
    "We don't know how to make fat people {into thin people or how to make thin people into fat people.}",
    "{Slavery} did not exist in America.",
    "The car has never changed {since the invention of the automobile.}",
    "I am fully capable of going backwards {and forwards in time and at will.}",
    "Most people are not {intellectual enough to understand} Family Guy.",
    "{There is no such thing as a “best”} when it comes to sports or sports teams.",
    "As of 2002, {love went extinct.}",
    "{Being a juggalo} is just like being a normal person.",
    "{Warhammer 40,000} can make anything awesome.",
    "{Man used to live} for hundreds of years disease free.",
    "The first polio vaccine, the Salk vaccine{, was a total disaster}.",
    "There is no difference between night dreams and daytime dreams {except about elephant.}",
    "{Dolphins} know how to access multiple dimensions.",
    "{It is legal to} post nude photos of someone without their consent.",
    "Laura Ingalls Wilder is {God.}",
    "{The Kardashians} are in league with Al-Qaeda.",
    "Light creates {gravity.}",
    "{Canoe} complications are enough to strain any relationship.",
    "{A toilet} is becoming a completely foreign object to women.",
    "The Latino people have never had {a revolution.}",
    "No one on Earth is {gay.}",
    "Ice is the {natural enemy of} bottled water.",
    "We're all {goth} now.",
    "{Leonardo DiCaprio's salary} is bankrupting America.",
    "{Pubic lice are a turn on because} when you go down on someone, they're like right in your nose.",
    "Clowns are {sexy.}",
    "{Dried pee} smells a lot like perfume.",
    "There's nothing perverted about {sniffing a pretty girl's seat cushion.}",
    "Minors find it difficult to {masturbate.}",
    "The inner penis {is before} the outer penis of course.",
    "It's natural for a person to be sexually {attracted to Pokemon.}",
    "I was having sex with my ladyfriend {and we're both prego.}",
    "Women were {made to be} spanked by men.",
    "Jelqing (manually wringing blood into your penis) {is positively REQUIRED just prior to sex.}",
    "Sticking a penis in anyone's mouth, man or woman{, has never been conducive to the benefit of anyone.}",
    "{Ghosts can haunt your anus and} give you mad uncontrollable bouts of farting.",
    "You can't {write porn} as a virgin.",
    "Everyone has a {tickling} fetish.",
    "There is no rational argument for not being a {brony.}",
    "It's almost impossible to quit {giving yourself wedgies.}",
    "America should put all its prisoners {into one giant super prison.}",
    "{Small breasts} are a thing of the past.",
    "You can improve your sex power by {eating garlic.}"
  ]
};