import {
  Tags,
  ReligionNames,
  Place,
  PlaceNames,
} from "./_types";

export const places: Place[] = [
  {
    id: 1,
    name: "A-Hyuk Hyuk, Alabama",
    description:
      "A-Hyuk Hyuk, Alabama is a rural southern place where the scent of barbecue drifts through the air and neighbors greet each other with a wave from their pickup trucks. The community is tight-knit, fiercely loyal, and proud of its traditions—especially the tradition of believing whatever the loudest preacher says. Church socials, football games, and family reunions are the backbone of social life, and the local diner is always buzzing with stories, rumors, and the latest miracle cure. Here, faith and patriotism go hand in hand, and the people are as resilient as the red clay beneath their boots, but also just gullible enough to buy holy water from a guy in a suit.",
    likedTags: [
      "community",
      "loyalty",
      "guns",
      "family values",
      "patriotism",
    ],
    dislikedTags: [
      "feminism",
      "nihilism",
      "modernity",
      "crystals",
      "liberal politics",
    ],
    totalPopulation: 120000,
    avgNetWorth: 45000,
    religions: [
      {
        id: 8,
        name: "Evangelical Christianity",
        weight: 85,
      },
      { id: 2, name: "Catholic", weight: 10 },
      { id: 1, name: "Southern Baptist", weight: 60 },
      { id: 6, name: "Prosperity Gospel", weight: 20 },
      { id: 9, name: "Mormonism", weight: 8 },
      { id: 10, name: "Jehovah's Witnesses", weight: 5 },
      { id: 12, name: "Orthodox Islam", weight: 2 },
      { id: 7, name: "New-Age Spirituality", weight: 1 },
      { id: 15, name: "Agnostic Atheists", weight: 5 },
      { id: 5, name: "Zardoz", weight: 1 },
      {
        id: 21,
        name: "The Order of the Alpha Male",
        weight: 40,
      },
    ],
  },
  {
    id: 2,
    name: "Yankee Grit, New Hampshire",
    description:
      "Don't Tread On Me, New Hampshire is nestled among rugged mountains and endless forests, where independence is a way of life. The locals value free thought and personal liberty above all—unless a charismatic megachurch leader tells them freedom means buying a $99 prayer blanket. Maple syrup flows in abundance, and town meetings are lively affairs where every voice is heard, especially the ones selling salvation in bulk. The people are resourceful, skeptical of authority, and quick to lend a hand, but also quick to sign up for the latest faith-based pyramid scheme.",
    likedTags: [
      "individualism",
      "free thought",
      "guns",
      "nature",
      "order",
    ],
    dislikedTags: [
      "oppression",
      "dogma",
      "nationalism",
      "exploitation",
      "blind faith",
    ],
    totalPopulation: 80000,
    avgNetWorth: 62000,
    religions: [
      { id: 15, name: "Agnostic Atheists", weight: 40 },
      {
        id: 8,
        name: "Evangelical Christianity",
        weight: 30,
      },
      { id: 7, name: "New-Age Spirituality", weight: 30 },
      { id: 2, name: "Catholic", weight: 10 },
      { id: 1, name: "Southern Baptist", weight: 8 },
      { id: 6, name: "Prosperity Gospel", weight: 5 },
      { id: 9, name: "Mormonism", weight: 3 },
      { id: 10, name: "Jehovah's Witnesses", weight: 2 },
      { id: 12, name: "Orthodox Islam", weight: 1 },
      { id: 5, name: "Zardoz", weight: 1 },
      { id: 17, name: "Secular Humanists", weight: 25 },
    ],
  },
  {
    id: 3,
    name: "Techno Utopia, California",
    description:
      "Techno Utopia, California is a sprawling metropolis of glass towers, electric cars, and endless Wi-Fi. Here, innovation is worshipped and every coffee shop is filled with entrepreneurs pitching the next big idea—especially if it involves spiritual enlightenment for a monthly fee. The population is diverse, open-minded, and always searching for meaning, preferably in a subscription box. The cost of living is sky-high, but so are the ambitions and dreams of its residents, who believe the future is theirs to invent, or at least to livestream. If you can sell salvation as an app, these folks will download it twice.",
    likedTags: [
      "innovation",
      "modernity",
      "meditation",
      "free thought",
      "money",
    ],
    dislikedTags: [
      "literalism",
      "dogma",
      "order",
      "blind faith",
      "hardship",
    ],
    totalPopulation: 300000,
    avgNetWorth: 120000,
    religions: [
      { id: 7, name: "New-Age Spirituality", weight: 50 },
      { id: 14, name: "Buddhist", weight: 30 },
      { id: 15, name: "Agnostic Atheists", weight: 20 },
      {
        id: 8,
        name: "Evangelical Christianity",
        weight: 10,
      },
      { id: 2, name: "Catholic", weight: 8 },
      { id: 1, name: "Southern Baptist", weight: 5 },
      { id: 6, name: "Prosperity Gospel", weight: 3 },
      { id: 9, name: "Mormonism", weight: 2 },
      { id: 10, name: "Jehovah's Witnesses", weight: 1 },
      { id: 5, name: "Zardoz", weight: 1 },
      {
        id: 19,
        name: "The Church of the High Priest",
        weight: 25,
      },
      {
        id: 22,
        name: "The Order of the Divine Algorithm",
        weight: 30,
      },
    ],
  },
  {
    id: 4,
    name: "Blessed Bayou, Louisiana",
    description:
      "Blessed Bayou, Louisiana pulses with the rhythms of jazz and gospel, where faith is celebrated as joyfully as Mardi Gras. The streets are lined with historic churches, soulful music, and the aroma of spicy gumbo. Community and compassion are the heart of this place, and every gathering is a celebration of life—and a chance to buy a blessed crawfish amulet. Old traditions blend seamlessly with new ideas, especially if those ideas come with a shiny pamphlet and a promise of prosperity. The people are warm, resilient, and always ready to believe in the next miracle, especially if it comes with a catchy jingle.",
    likedTags: [
      "community",
      "compassion",
      "emotion",
      "pleasure",
      "family values",
    ],
    dislikedTags: [
      "nihilism",
      "apathy",
      "exploitation",
      "greed",
      "order",
    ],
    totalPopulation: 95000,
    avgNetWorth: 38000,
    religions: [
      { id: 2, name: "Catholic", weight: 60 },
      {
        id: 8,
        name: "Evangelical Christianity",
        weight: 30,
      },
      { id: 13, name: "Mystic Islam", weight: 10 },
      { id: 1, name: "Southern Baptist", weight: 8 },
      { id: 6, name: "Prosperity Gospel", weight: 5 },
      { id: 9, name: "Mormonism", weight: 3 },
      { id: 10, name: "Jehovah's Witnesses", weight: 2 },
      { id: 12, name: "Orthodox Islam", weight: 1 },
      { id: 7, name: "New-Age Spirituality", weight: 1 },
      { id: 5, name: "Zardoz", weight: 1 },
    ],
  },
  {
    id: 5,
    name: "Crystal Pines, Arizona",
    description:
      "Crystal Pines, Arizona is a sun-baked haven for seekers, mystics, and dreamers. The desert landscape is dotted with crystal shops, meditation retreats, and mysterious stone circles. UFO sightings are a local pastime, and open-mindedness is the norm—especially when it comes to buying blessed moon rocks from a guy named Starbeam. Residents gather for sunrise yoga, swap stories of spiritual awakenings, and cherish the natural beauty that surrounds them, but they're also first in line for any guru promising enlightenment for three easy payments. If you can sell it with a sparkle, they'll believe it with a smile.",
    likedTags: [
      "crystals",
      "meditation",
      "open-mindedness",
      "nature",
      "innovation",
    ],
    dislikedTags: [
      "dogma",
      "literalism",
      "order",
      "nationalism",
      "blind faith",
    ],
    totalPopulation: 40000,
    avgNetWorth: 51000,
    religions: [
      { id: 13, name: "New-Age Spirituality", weight: 70 },
      { id: 14, name: "Buddhist", weight: 20 },
      {
        id: 8,
        name: "Evangelical Christianity",
        weight: 10,
      },
      { id: 2, name: "Catholic", weight: 8 },
      { id: 1, name: "Southern Baptist", weight: 5 },
      { id: 6, name: "Prosperity Gospel", weight: 3 },
      { id: 9, name: "Mormonism", weight: 2 },
      { id: 10, name: "Jehovah's Witnesses", weight: 1 },
      { id: 12, name: "Orthodox Islam", weight: 1 },
      { id: 5, name: "Zardoz", weight: 1 },
      { id: 26, name: "The Starseed Pilgrims", weight: 30 },
    ],
  },
  {
    id: 6,
    name: "Lake Miracle, Florida",
    description:
      "Lake Miracle, Florida is a sun-drenched paradise where every sunrise is a sign from above and every sunset is a chance to buy a miracle in a bottle. The locals are as laid-back as the alligators, but their faith is as strong as their sunscreen. Sunday services are held on pontoon boats, and the most popular local business is a drive-thru baptismal. If you can turn water into wine coolers, you'll fit right in.",
    likedTags: [
      "community",
      "pleasure",
      "nature",
      "compassion",
      "free thought",
    ],
    dislikedTags: [
      "skepticism",
      "hardship",
      "dogma",
      "nihilism",
      "apathy",
    ],
    totalPopulation: 65000,
    avgNetWorth: 47000,
    religions: [
      {
        id: 8,
        name: "Evangelical Christianity",
        weight: 50,
      },
      { id: 6, name: "Prosperity Gospel", weight: 30 },
      { id: 2, name: "Catholic", weight: 10 },
      { id: 7, name: "New-Age Spirituality", weight: 5 },
      { id: 15, name: "Agnostic Atheists", weight: 2 },
      { id: 1, name: "Southern Baptist", weight: 2 },
      { id: 9, name: "Mormonism", weight: 1 },
      { id: 10, name: "Jehovah's Witnesses", weight: 1 },
      { id: 12, name: "Orthodox Islam", weight: 1 },
      { id: 5, name: "Zardoz", weight: 1 },
    ],
  },
  {
    id: 7,
    name: "Blessed Strip, Nevada",
    description:
      "Blessed Strip, Nevada is a neon-lit oasis where faith and fortune go hand in hand. The locals believe in luck, miracles, and the power of a well-timed prayer before hitting the slots. Churches double as casinos, and every wedding chapel offers a complimentary spiritual cleanse. If you can sell redemption chips, you'll be a high roller in no time.",
    likedTags: [
      "pleasure",
      "community",
      "innovation",
      "provocation",
      "compassion",
    ],
    dislikedTags: [
      "poverty",
      "dogma",
      "apathy",
      "nihilism",
      "greed",
    ],
    totalPopulation: 90000,
    avgNetWorth: 52000,
    religions: [
      { id: 6, name: "Prosperity Gospel", weight: 40 },
      {
        id: 8,
        name: "Evangelical Christianity",
        weight: 25,
      },
      { id: 7, name: "New-Age Spirituality", weight: 15 },
      { id: 2, name: "Catholic", weight: 10 },
      { id: 15, name: "Agnostic Atheists", weight: 5 },
      { id: 1, name: "Southern Baptist", weight: 2 },
      { id: 9, name: "Mormonism", weight: 1 },
      { id: 10, name: "Jehovah's Witnesses", weight: 1 },
      { id: 12, name: "Orthodox Islam", weight: 1 },
      { id: 5, name: "Zardoz", weight: 1 },
    ],
  },
  {
    id: 8,
    name: "Megamall, Minnesota",
    description:
      "Megamall, Minnesota is a sprawling wonderland of commerce and faith, where every store has a prayer room and every escalator is blessed. The population is as diverse as the food court, and the local megachurch is conveniently located between the ice rink and the indoor roller coaster. If you can preach in a food court, you'll never go hungry.",
    likedTags: [
      "community",
      "consumerism",
      "pleasure",
      "compassion",
      "innovation",
    ],
    dislikedTags: [
      "dogma",
      "hardship",
      "apathy",
      "nihilism",
      "exploitation",
    ],
    totalPopulation: 110000,
    avgNetWorth: 60000,
    religions: [
      {
        id: 8,
        name: "Evangelical Christianity",
        weight: 35,
      },
      { id: 2, name: "Catholic", weight: 20 },
      { id: 6, name: "Prosperity Gospel", weight: 15 },
      { id: 7, name: "New-Age Spirituality", weight: 10 },
      { id: 15, name: "Agnostic Atheists", weight: 8 },
      { id: 1, name: "Southern Baptist", weight: 5 },
      { id: 9, name: "Mormonism", weight: 3 },
      { id: 10, name: "Jehovah's Witnesses", weight: 2 },
      { id: 12, name: "Orthodox Islam", weight: 1 },
      { id: 5, name: "Zardoz", weight: 1 },
      { id: 24, name: "The Queens' Dominion", weight: 30 },
    ],
  },
];
