import { ReligionNames, Religion, Tags } from "./_types";

export const religions: Religion[] = [
  {
    id: 1,
    name: "Southern Baptist",
    description: `A traditional Protestant denomination known for its conservative social views and strong community ties.`,
    likes: [
      "community",
      "patriotism",
      "nationalism",
      "family values",
      "tradition",
      "spreading the word",
      "authority",
      "order",
    ],
    dislikes: [
      "science",
      "modernity",
      "liberal politics",
      "secularism",
      "feminism",
      "individualism",
      "rebellion",
    ],
    enemies: ["Secular Humanists", "The Church of Satan"],
  },
  {
    id: 2,
    name: "Catholic",
    description: `The largest Christian church, with a rich history, complex rituals, and a global hierarchy.`,
    likes: [
      "tradition",
      "rituals",
      "authority",
      "order",
      "community",
      "formal religion",
      "structure",
      "dogma",
    ],
    dislikes: [
      "individualism",
      "rebellion",
      "secularism",
      "modernity",
      "casualness",
      "innovation",
      "freedom",
    ],
    enemies: ["The Church of Satan", "Secular Humanists"],
  },
  {
    id: 4,
    name: "The Church of Eros",
    description: `A religion centered on the belief that spiritual enlightenment and union with the divine are achieved through carnal and sensory pleasure.`,
    likes: [
      "pleasure",
      "sensory experience",
      "freedom",
      "individualism",
      "sex",
      "promiscuity",
      "rebellion",
      "casualness",
    ],
    dislikes: [
      "abstinence",
      "strict rules",
      "dogma",
      "self-control",
      "authority",
      "tradition",
      "shame",
    ],
    enemies: ["Orthodox Islam", "Mormonism"],
  },
  {
    id: 5,
    name: "Zardoz",
    description: `Based on the 1974 film of the same name. Its core belief is the worship of a floating stone head that preaches "The gun is good. The penis is evil."`,
    likes: [
      "provocation",
      "bizarre concepts",
      "outrageousness",
      "nihilism",
      "rebellion",
      "violence",
      "chaos",
      "guns",
    ],
    dislikes: [
      "family values",
      "sex",
      "promiscuity",
      "order",
      "tradition",
      "community",
      "peace",
    ],
    enemies: ["2 Fast 2 Faithful", "The Gaia Collective"],
  },
  {
    id: 6,
    name: "Prosperity Gospel",
    description: `A belief that faith and prayer lead to financial wealth and physical well-being.`,
    likes: [
      "money",
      "wealth",
      "greed",
      "positive affirmations",
      "giving to get",
      "materialism",
      "power",
      "exploitation",
    ],
    dislikes: [
      "poverty",
      "suffering",
      "hardship",
      "self-doubt",
      "humility",
      "simplicity",
      "compassion",
    ],
    enemies: ["The Gaia Collective", "Secular Humanists"],
  },
  {
    id: 7,
    name: "New-Age Spirituality",
    description: `A diverse collection of beliefs and practices focused on personal growth, holistic health, and mystical experiences.`,
    likes: [
      "crystals",
      "meditation",
      "personal energy",
      "self-help",
      "open-mindedness",
      "nature",
      "inner harmony",
      "freedom",
    ],
    dislikes: [
      "structure",
      "dogma",
      "formal religion",
      "fixed beliefs",
      "authority",
      "tradition",
      "strict rules",
    ],
    enemies: ["Orthodox Islam", "Southern Baptist"],
  },
  {
    id: 8,
    name: "Evangelical Christianity",
    description: `A broad movement that emphasizes personal conversion, the authority of the Bible, and the importance of spreading the Christian message.`,
    likes: [
      "spreading the word",
      "personal testimony",
      "missionary work",
      "passion",
      "sincerity",
      "community",
      "family values",
      "tradition",
    ],
    dislikes: [
      "apathy",
      "skepticism",
      "liberal politics",
      "secularism",
      "rationalism",
      "science",
      "modernity",
    ],
    enemies: ["Secular Humanists", "The Church of Satan"],
  },
  {
    id: 9,
    name: "Mormonism",
    description: `A religious movement centered on the Book of Mormon, emphasizing family, community, and missionary work.`,
    likes: [
      "family values",
      "community",
      "strict rules",
      "tradition",
      "abstinence",
      "order",
      "spreading the word",
      "self-control",
    ],
    dislikes: [
      "casualness",
      "secularism",
      "individualism",
      "freedom",
      "rebellion",
      "sex",
      "promiscuity",
    ],
    enemies: ["The Church of Eros", "The Sovereign Guild of Untethered Minds"],
  },
  {
    id: 10,
    name: "Jehovah's Witnesses",
    description: `A millenarian denomination known for its door-to-door preaching and refusal of military service and blood transfusions.`,
    likes: [
      "literalism",
      "prophecy",
      "authority",
      "doctrinal purity",
      "order",
      "spreading the word",
      "structure",
      "subservience",
    ],
    dislikes: [
      "other religions",
      "worldly celebrations",
      "individualism",
      "rebellion",
      "violence",
      "nationalism",
      "patriotism",
    ],
    enemies: ["Zardoz", "The Sovereign Guild of Untethered Minds"],
  },
  {
    id: 11,
    name: "Secular Humanists",
    description: `A non-religious philosophy that emphasizes reason, ethics, and justice, rejecting supernatural beliefs.`,
    likes: [
      "ethics",
      "social justice",
      "reason",
      "science",
      "logic",
      "progress",
      "compassion",
      "rationalism",
    ],
    dislikes: [
      "blind faith",
      "unethical behavior",
      "dogma",
      "exploitation",
      "authority",
      "the occult",
      "tradition",
    ],
    enemies: ["Southern Baptist", "Prosperity Gospel"],
  },
  {
    id: 12,
    name: "Orthodox Islam",
    description: `A strict, orthodox branch of Islam that enforces rigorous codes of dress, behavior, and morality. Followers believe salvation is found through unwavering obedience to divine law, modesty, and the preservation of traditional values. The community is tightly regulated, with clear roles for men and women and little tolerance for deviation.`,
    likes: [
      "tradition",
      "order",
      "strict rules",
      "authority",
      "family values",
      "rituals",
      "subservience",
      "structure",
    ],
    dislikes: [
      "rebellion",
      "freedom",
      "individualism",
      "innovation",
      "sex",
      "casualness",
      "feminism",
      "modernity",
    ],
    enemies: ["The Church of Eros", "The Queens' Dominion"],
  },
  {
    id: 13,
    name: "Mystic Islam",
    description: `A mystical branch of Islam devoted to the deep study and contemplation of sacred scripture. Followers seek personal enlightenment through meditation, poetry, and spiritual practices, believing that the divine is best experienced inwardly. The faith values compassion, inner harmony, and the transformative power of spiritual knowledge.`,
    likes: [
      "meditation",
      "compassion",
      "inner harmony",
      "rituals",
      "open-mindedness",
      "prophecy",
      "transcendence",
      "peace",
    ],
    dislikes: [
      "dogma",
      "literalism",
      "materialism",
      "strict rules",
      "oppression",
      "violence",
      "greed",
    ],
    enemies: ["Orthodox Islam", "Prosperity Gospel"],
  },
  {
    id: 14,
    name: "The Church of the High Priest",
    description: `A fictional religion that believes in achieving spiritual enlightenment through the use of psychedelic substances.`,
    likes: [
      "drugs",
      "sensory experience",
      "altered states",
      "pleasure",
      "freedom",
      "rebellion",
      "transcendence",
      "open-mindedness",
    ],
    dislikes: [
      "rules",
      "authority",
      "order",
      "soberness",
      "abstinence",
      "structure",
      "dogma",
    ],
    enemies: ["Mormonism", "Jehovah's Witnesses"],
  },
  {
    id: 15,
    name: "2 Fast 2 Faithful",
    description: `A cult based on the teachings of Vin Diesel, who promises salvation through loyalty, speed, and the unbreakable bond of "family."`,
    likes: [
      "family values",
      "strength",
      "speed",
      "power",
      "loyalty",
      "patriotism",
      "community",
      "nationalism",
    ],
    dislikes: [
      "weakness",
      "humility",
      "journalism",
      "skepticism",
      "reason",
      "peace",
      "individualism",
    ],
    enemies: ["Zardoz", "Secular Humanists"],
  },
  {
    id: 16,
    name: "The Digital Ascension",
    description: `Transhumanists who believe salvation is achieved by shedding the physical body and uploading consciousness into a digital plane.`,
    likes: [
      "technology",
      "science",
      "logic",
      "progress",
      "transcendence",
      "innovation",
      "rationalism",
      "modernity",
    ],
    dislikes: [
      "tradition",
      "emotion",
      "dogma",
      "body",
      "nature",
      "rituals",
      "meditation",
      "simplicity",
    ],
    enemies: ["The Gaia Collective", "New-Age Spirituality"],
  },
  {
    id: 17,
    name: "The Gaia Collective",
    description: `Earth-worshippers who believe in returning to a primitive, harmonious existence with nature.`,
    likes: [
      "nature",
      "community",
      "simplicity",
      "sustainability",
      "peace",
      "compassion",
      "humility",
      "inner harmony",
    ],
    dislikes: [
      "technology",
      "greed",
      "modernity",
      "consumerism",
      "progress",
      "materialism",
      "exploitation",
    ],
    enemies: ["The Digital Ascension", "Prosperity Gospel"],
  },
  {
    id: 18,
    name: "The Order of the Alpha Male",
    description: `A chauvinistic movement that promotes traditional masculinity, dominance, and a patriarchal social structure.`,
    likes: [
      "strength",
      "authority",
      "patriotism",
      "dogma",
      "order",
      "power",
      "nationalism",
      "tradition",
    ],
    dislikes: [
      "weakness",
      "feminism",
      "liberal politics",
      "compassion",
      "humility",
      "social justice",
      "emotion",
    ],
    enemies: ["The Queens' Dominion", "Secular Humanists"],
  },
  {
    id: 19,
    name: "The Queens' Dominion",
    description: `A sacred order devoted to the elevation of women as living goddesses, preaching that only through the unquestioned authority and rule of women can true salvation and earthly harmony be achieved. Male submission is seen as essential to the divine order.`,
    likes: [
      "feminism",
      "strength",
      "authority",
      "order",
      "rebellion",
      "power",
      "social justice",
      "freedom",
    ],
    dislikes: [
      "weakness",
      "patriotism",
      "family values",
      "tradition",
      "subservience",
      "nationalism",
      "oppression",
    ],
    enemies: ["The Order of the Alpha Male", "Orthodox Islam"],
  },
  {
    id: 20,
    name: "The Sovereign Guild of Untethered Minds",
    description: `A spiritual doctrine that exalts personal sovereignty and self-rule as sacred, teaching that true enlightenment is found only by rejecting all external authority—be it government, law, or tradition. Followers believe salvation is achieved through absolute independence, living by one's own divine law and refusing all imposed control.`,
    likes: [
      "freedom",
      "individualism",
      "rebellion",
      "self-sufficiency",
      "chaos",
      "apathy",
      "nihilism",
      "skepticism",
    ],
    dislikes: [
      "authority",
      "rules",
      "taxes",
      "community",
      "order",
      "structure",
      "dogma",
    ],
    enemies: ["Jehovah's Witnesses", "The Order of the Divine Algorithm"],
  },
  {
    id: 21,
    name: "The Starseed Pilgrims",
    description: `A fictional religion based on the belief that a higher, alien consciousness will one day return to Earth and guide humanity.`,
    likes: [
      "bizarre concepts",
      "prophecy",
      "the occult",
      "open-mindedness",
      "transcendence",
      "altered states",
      "meditation",
      "progress",
    ],
    dislikes: [
      "logic",
      "science",
      "skepticism",
      "tradition",
      "dogma",
      "rationalism",
      "materialism",
    ],
    enemies: ["Secular Humanists", "The Digital Ascension"],
  },
  {
    id: 22,
    name: "The Order of the Divine Algorithm",
    description: `A modern faith that venerates computers and algorithms as superior beings. Followers believe that true fulfillment is found by surrendering personal choice to the guidance of digital systems, striving to live every aspect of life according to algorithmic recommendations. Rituals include consulting apps, AI, and data-driven suggestions for decisions both big and small, trusting that the algorithm knows best.`,
    likes: [
      "technology",
      "logic",
      "order",
      "progress",
      "innovation",
      "structure",
      "security",
      "subservience",
    ],
    dislikes: [
      "emotion",
      "chaos",
      "tradition",
      "rebellion",
      "freedom",
      "nature",
      "individualism",
    ],
    enemies: ["The Gaia Collective", "The Sovereign Guild of Untethered Minds"],
  },
  {
    id: 23,
    name: "Temple of the Eternal Sun",
    description: `A solar-centric faith that worships the sun as the source of all life, enlightenment, and spiritual power. Followers believe that devotion to the sun brings clarity, immortality, and cosmic harmony.`,
    likes: [
      "rituals",
      "nature",
      "order",
      "progress",
      "power",
      "transcendence",
      "tradition",
      "structure",
    ],
    dislikes: [
      "chaos",
      "rebellion",
      "nihilism",
      "apathy",
      "weakness",
      "modernity",
      "skepticism",
    ],
    enemies: ["Zardoz", "The Sovereign Guild of Untethered Minds"],
  },
  {
    id: 24,
    name: "The Church of Satan",
    description: `A non-theistic religious organization that advocates for secularism and uses Satan as a symbol of rebellion against arbitrary authority.`,
    likes: [
      "rebellion",
      "secularism",
      "rationalism",
      "justice",
      "free thought",
      "provocation",
      "sex",
      "individualism",
    ],
    dislikes: [
      "dogma",
      "blind faith",
      "authority",
      "tradition",
      "subservience",
      "exploitation",
      "oppression",
    ],
    enemies: ["Southern Baptist", "Evangelical Christianity"],
  },
  {
    id: 25,
    name: "Theistic Satanism",
    description: `A broad term for religious groups that believe in and worship Satan as a real deity.`,
    likes: [
      "power",
      "strength",
      "individualism",
      "freedom",
      "the occult",
      "rebellion",
      "chaos",
      "violence",
    ],
    dislikes: [
      "subservience",
      "weakness",
      "forgiveness",
      "tradition",
      "compassion",
      "humility",
      "order",
    ],
    enemies: ["Catholic", "Orthodox Islam"],
  },
  {
    id: 26,
    name: "Buddhist",
    description: `A spiritual tradition focused on personal spiritual development and the attainment of a deep insight into the true nature of life through meditation, mindfulness, and compassion.`,
    likes: [
      "meditation",
      "compassion",
      "inner harmony",
      "peace",
      "simplicity",
      "humility",
      "transcendence",
      "suffering",
    ],
    dislikes: [
      "greed",
      "materialism",
      "violence",
      "wealth",
      "power",
      "exploitation",
      "nationalism",
    ],
    enemies: ["Prosperity Gospel", "The Order of the Alpha Male"],
  },
  {
    id: 27,
    name: "Agnostic Atheists",
    description: `Individuals who lack belief in deities while also maintaining that the existence or non-existence of gods is unknowable or unprovable.`,
    likes: [
      "skepticism",
      "reason",
      "logic",
      "science",
      "rationalism",
      "free thought",
      "open-mindedness",
      "progress",
    ],
    dislikes: [
      "blind faith",
      "dogma",
      "the occult",
      "authority",
      "tradition",
      "exploitation",
      "unethical behavior",
    ],
    enemies: ["Evangelical Christianity", "The Starseed Pilgrims"],
  },
  {
    id: 28,
    name: "Seventh-day Adventism",
    description: `A faith devoted to the sacredness of Saturday, healthy living, and the constant expectation that the world will end any minute now. Followers are experts at potlucks, prophecy charts, and politely declining bacon.`,
    likes: [
      "tradition",
      "order",
      "community",
      "prophecy",
      "abstinence",
      "rituals",
      "family values",
      "simplicity",
    ],
    dislikes: [
      "casualness",
      "apathy",
      "dogma",
      "greed",
      "modernity",
      "pleasure",
      "materialism",
    ],
    enemies: ["Prosperity Gospel", "Zardoz"],
  },
  {
    id: 29,
    name: "Shinto",
    description: `An ancient tradition that reveres spirits in every rock, tree, and vending machine. Rituals involve purification, seasonal festivals, and making sure the local shrine is Instagram-ready.`,
    likes: [
      "nature",
      "rituals",
      "community",
      "tradition",
      "simplicity",
      "peace",
      "spreading the word",
      "order",
    ],
    dislikes: [
      "exploitation",
      "greed",
      "dogma",
      "chaos",
      "modernity",
      "violence",
      "nationalism",
    ],
    enemies: ["The Digital Ascension", "The Gaia Collective"],
  },
  {
    id: 30,
    name: "Confucianism",
    description: `A philosophy-religion focused on respect, order, and knowing your place in the family. True enlightenment is achieved by memorizing proverbs and never disappointing your ancestors.`,
    likes: [
      "order",
      "tradition",
      "family values",
      "community",
      "structure",
      "humility",
      "peace",
      "compassion",
    ],
    dislikes: [
      "rebellion",
      "chaos",
      "individualism",
      "apathy",
      "nihilism",
      "dogma",
      "provocation",
    ],
    enemies: ["The Sovereign Guild of Untethered Minds", "Zardoz"],
  },
];
