// Shared sermon types for megachurch
export type Categories =
  | "Strength"
  | "Healing"
  | "Prophecy"
  | "Family";

export type ReligionNames =
  | "2 Fast 2 Faithful"
  | "Agnostic Atheists"
  | "Buddhist"
  | "Catholic"
  | "Evangelical Christianity"
  | "Jehovah's Witnesses"
  | "Mormonism"
  | "Mystic Islam"
  | "New-Age Spirituality"
  | "Orthodox Islam"
  | "Prosperity Gospel"
  | "Rastafarianism"
  | "Secular Humanists"
  | "Southern Baptist"
  | "Temple of the Eternal Sun"
  | "The Blockchain Mystics"
  | "The Church of Eros"
  | "The Church of Satan"
  | "The Church of the High Priest"
  | "The Digital Ascension"
  | "The Gaia Collective"
  | "The Order of the Alpha Male"
  | "The Order of the Divine Algorithm"
  | "The Queens' Dominion"
  | "The Sovereign Guild of Untethered Minds"
  | "The Starseed Pilgrims"
  | "Theistic Satanism"
  | "Zardoz";

export interface Religion {
  id: number; // UID for religion
  name: ReligionNames; // Name of this religion
  description?: string; // Recommended. Describe this religion further.
  likes: Tags[]; // A list of things this religion likes.
  dislikes: Tags[]; // A list of things this religion dislikes.
  enemies?: ReligionNames[]; // What religions this religion opposes.
}

export type Tags =
  | "abstinence"
  | "altered states"
  | "apathy"
  | "authority"
  | "bizarre concepts"
  | "blind faith"
  | "body"
  | "abstinence"
  | "altered states"
  | "apathy"
  | "authority"
  | "bizarre concepts"
  | "blind faith"
  | "body"
  | "casualness"
  | "chaos"
  | "community"
  | "compassion"
  | "consumerism"
  | "crystals"
  | "dogma"
  | "doctrinal purity"
  | "drugs"
  | "emotion"
  | "ethics"
  | "exploitation"
  | "family values"
  | "feminism"
  | "fixed beliefs"
  | "formal religion"
  | "forgiveness"
  | "free thought"
  | "freedom"
  | "giving to get"
  | "greed"
  | "guns"
  | "hardship"
  | "humility"
  | "individualism"
  | "innovation"
  | "inner harmony"
  | "journalism"
  | "justice"
  | "liberal politics"
  | "literalism"
  | "logic"
  | "loyalty"
  | "materialism"
  | "meditation"
  | "missionary work"
  | "modernity"
  | "money"
  | "nationalism"
  | "nature"
  | "nihilism"
  | "open-mindedness"
  | "oppression"
  | "order"
  | "other religions"
  | "outrageousness"
  | "passion"
  | "patriotism"
  | "peace"
  | "personal energy"
  | "personal testimony"
  | "pleasure"
  | "positive affirmations"
  | "poverty"
  | "power"
  | "progress"
  | "prophecy"
  | "provocation"
  | "rationalism"
  | "rebellion"
  | "reason"
  | "rituals"
  | "rules"
  | "sex"
  | "promiscuity"
  | "shame"
  | "science"
  | "security"
  | "secularism"
  | "self-control"
  | "self-doubt"
  | "self-help"
  | "self-sufficiency"
  | "sensory experience"
  | "simplicity"
  | "sincerity"
  | "skepticism"
  | "soberness"
  | "social justice"
  | "speed"
  | "spreading the word"
  | "strength"
  | "strict rules"
  | "structure"
  | "subservience"
  | "suffering"
  | "sustainability"
  | "taxes"
  | "technology"
  | "the occult"
  | "tradition"
  | "transcendence"
  | "unethical behavior"
  | "violence"
  | "wealth"
  | "weakness"
  | "worldly celebrations";
