const allValues = [
  { name: "Kevin O'Leary", desc:"Shark Tank", slug:"mrwonderful", value:1200 },
  { name: "Randy Quaid", desc: "Eddie in the National Lampoon Vacation movies", slug:"vbn", value:1000 },
  { name: "Steve Harvey", desc:"Game Show Host", slug:"steveharvey", value:750 },
  { name: "Lil' Kim", desc:"Formerly of Junior M.A.F.I.A.", slug:"lilkimthequeenbee", value:500 },
  { name: "Ice T", desc: "Law & Order: SVU", slug:"icet", value:500 },
  { name: "Flavor Flav", desc:"Formerly of Public Enemy", slug:"flavorflav", value:400 },
  { name: "Jackie Mason", desc:"Rabbi Hyman Krustofski on The Simpsons", slug:"jackiemason", value:350 },
  { name: "Insane Clown Posse", desc:"Unaware of how magnets work", slug:"icp", value:350 },
  { name: "Lindsay Lohan", desc:"Actress, The Parent Trap", slug: "lindsaylohan", value:350 },
  { name: "Ghostface Killah", desc: "Member of Wu-Tang Clan", slug: "realghostfacekillah", value:350 },
  { name: "Pauly Shore", desc: "Bio-Dome & Encino Man", slug: "paulyshore", value:350 },
  { name: "Jonathan Frakes", desc:"Riker on Star Trek TNG", slug: "windyoaks", value:300 },
  { name: "Boy George", desc:"Singer - Culture Club", slug: "boygeorge5", value:300 },
  { name: "Blac Chyna", desc: "Model & Socialite", slug: "blacchyna", value:300 },
  { name: "Andrew Dice Clay", slug: "diceman", value:299 },
  { name: "Kenny G", desc: "Saxophonist", slug:"kennyg", value:295 },
  { name: "Krysten Ritter", desc: "The B---- in Apartment 23", slug: "krystenritter", value:275 },
  { name: "Joe Piscopo", desc: "SNL", slug:"joepiscopo", value:250 },
  { name: "Brent Spiner", desc: "Data on Star Trek TNG", slug:"brentspiner", value:250 },
  { name: "Stormy Daniels", desc: "Received $130,000 in hush money from Trump surrogates", slug:"stormydaniels", value:250 },
  { name: "Hide The Pain Harold", desc: "photo meme", slug:"hidethepainharold", value:250 },
  { name: "Steve Guttenberg", desc:"Police Academy 1-4", slug:"steveguttenberg", value:250 },
  { name: "David Koechner", desc:"Anchorman", slug:"davidkoechner", value:225 },
  { name: "Corey Feldman", desc:"Mouth in The Goonies", slug:"cdogg22", value:202 },
  { name: "Dog the Bounty Hunter", slug:"A&E Reality Star", slug:"dogthebountyhunter", value:200 },
  { name: "Jaleel White", desc:"Urkel", slug:"jaleelwhite", value:200 },
  { name: "Punxsutawney Phil", desc:"World Famous Groundhog", slug:"punxsyphil", value:199 },
  { name: "Coolio", desc:"Cowrote Gangsta's Paradise", slug:"therealcoolio", value:199 },
  { name: "Sir Mix-A-Lot", desc:"Likes Big Butts", slug:"therealsirmixalot", value:150  },
  { name: "Tommy Chong", desc:"Marijuana Enthusiast", slug:"tommychong", value:150  },
  { name: "Adam Duritz", desc:"Counting Crows", slug:"countingcrows", value:150  },
  { name: "Jon Lovitz", desc:"SNL", slug:"jonlovitz", value:150  },
  { name: "Gilbert Gottfried", desc:"Iago in Aladdin", slug:"gilbertgottfried", value:150  },
  { name: "Jamie Lynn Sigler", desc:"Meadow on The Sopranos", slug:"jamielynnsigler", value:150  },
  { name: "Penn Jillette", desc:"Penn & Teller", slug:"pennj", value:135  },
  { name: "Violent J", desc:"Insane Clown Posse.", slug:"violentj.icp", value:135  },
  { name: "Shaggy 2 Dope", desc:"Insane Clown Posse", slug:"shaggy.icp", value:134  },
  { name: "Victoria Jackson", desc:"SNL", slug:"victoria_jackson_official", value:125  },
  { name: "Tom Arnold", desc:"Was briefly married to Roseanne", slug:"thetomarnold", value:125 },
  { name: "Jamie Farr", desc:"Klinger on M*A*S*H", slug:"jamiefarr1", value:125 },
  { name: "Steve Carlson", desc:"one of the guys from the movie Slapshot", slug:"scarlson17", value:117  },
  { name: "Dave Hanson", desc:"one of the guys from the movie Slapshot", slug:"davehanson16", value:116  },
  { name: "Fiona the Hippo", slug:"fionathehippo", value:100 },
  { name: "Dave Foley", desc:"Kids in the Hall", slug:"dsf", value:100 },
  { name: "Burton Gilliam", desc:"“Lyle” from Blazing Saddles", slug:"camptownladies", value:100 },
  { name: "Michael Cohen", desc:"Disbarred Legal Fixer", slug:"michaelcohen212", value:100 },
  { name: "Vincent Curatola", desc:"Johnny Sack on The Sopranos", slug:"vincentcuratola", value:100 },
  { name: "Lisa Loeb", slug:"lisaloeb", value:100 },
  { name: "Richard Karn", desc:"Al on Home Improvement", slug:"richardkarn", value:100 },
  { name: "Doug Bradley", desc:"Pinhead in Hellraiser", slug:"dougbradley", value:100 },
  { name: "Andy Dick", desc:"Newsradio", slug:"andydick", value:99 },
  { name: "Chris Kattan", desc:"SNL", slug:"chriskattan", value:95 },
  { name: "Jay Mohr", desc:"Actor, The Ghost Whisperer", slug:"jaymohr", value:88  },
  { name: "Chumlee", desc:"Pawn Stars", slug:"chumlee", value:85  },
  { name: "Donald Gibb", desc:"Ogre in Revenge of the Nerds", slug:"ogre1", value:85  },
  { name: "Rod Blagojevich", desc:"Convicted Felon", slug:"rblagojevich", value:80 },
  { name: "Larry Thomas aka The Soup Nazi", desc:"The Soup Nazi", slug:"realsoupnazi", value:80 },
  { name: "Jennifer Elise Cox", desc:"Jan on The Brady Bunch", slug:"jenniferelisecox", value:75 },
  { name: "Dana Snyder", desc:"Aqua Teen Hunger Force", slug:"eyeofthesnyder", value:75 },
  { name: "Didi Conn", desc:"Frenchy in Grease", slug:"didiconn1", value:75 },
  { name: "Roger Stone", desc:"Commuted Felon", slug:"rogerstone", value:75 },
  { name: "Danny Bonaduce", desc:"The Partridge Family", slug:"dannybonaduce", value:75 },
  { name: "John Kassir", desc:"Voice Actor of the Crypt Keeper", slug:"cryptkeeper", value:70  },
  { name: "KID from Kid N Play", desc:"Costar of House Party 1, 2 & 3", slug:"kidfromkidnplay", value:65  },
  { name: "Kato Kaelin", desc:"Stayed At OJ's House", slug:"kato", value:60 },
  { name: "Anthony Scaramucci", desc:"Former White House Communications Director", slug:"themooch", value:55 },
  { name: "Bonnie Chapman", desc:"Daughter of Dog The Bounty Hunter", slug:"bonniejoc", value:50  },
  { name: "Deep Roy", desc:"Oompa Loompa in the 2015 Willy Wonka movie", slug:"deeproy", value:50  },
  { name: "Xanman", slug:"theonlyxanman20", value:50  },
  { name: "Paul Chuckle", desc:"one of the Chuckle Brothers", slug:"chuckle", value:49 },
  { name: "Sleazy P Martini", desc:"GWAR - Manager", slug:"sleazymartini", value:40 },
  { name: "Tay Zonday", desc:"Chocolate Rainmaker", slug:"tayzonday", value:40 },
  { name: "Smelly", desc:"Drummer for NOFX", slug:"sandin", value:40 },
  { name: "Kevin McDonald", desc:"Kids in the Hall", slug:"teaguy1", value:40 },
  { name: "Cat Drawing Guy", desc:"contestant on Shark Tank", slug:"catdrawingguy", value:39 },
  { name: "Les Gold", desc:"Hardcore Pawn", slug:"lesg", value:35 },
  { name: "Andy Kindler", desc: "Bob's Burgers", slug:"andykindler", value:35 },
  { name: "Tennis", desc:"Inessential service", slug:"tennisinc", value:30 },
  { name: "Radioman", desc: "Actor in Little Nicky", slug:"radioman", value:30 },
  { name: "Ken Bone", desc:"Wore a red sweater at a Presidential debate", slug:"kenbone18", value:25 },
  { name: "Vermin Supreme", slug:"verminsupreme", value:25 },
  { name: "Boffo The Bear", desc: "YouTube Comedy Bear", slug: "boffothebear", value:20 },
  { name: "Ryan Creamer", desc:"Star of non-pornographic PornHub videos", slug: "coolboyryan", value:20 },
  { name: "Bobo Sasquatch", desc:"Finding Bigfoot", slug: "bobosquatch", value:20 },
  { name: "Matt Hoffman", desc:"CBS - Big Brother", slug: "bb12matt", value:12.5 },
  { name: "Alex Kack", desc:"Also known as #greenshirtguy", slug: "alex_kack", value:10 },
];