const allValues = [
  { name: "Kevin O'Leary", desc:"one of the guys from Shark Tank", slug:"mrwonderful", value:1200 },
  { name: "Randy Quaid", slug:"vbn", value:1000 },
  { name: "Steve Harvey", slug:"steveharvey", value:750 },
  { name: "Lil' Kim", slug:"lilkimthequeenbee", value:500 },
  { name: "Ice T", slug:"icet", value:500 },
  { name: "Flavor Flav", slug:"flavorflav", value:400 },
  { name: "Jackie Mason", slug:"jackiemason", value:350 },
  { name: "Insane Clown Posse", slug:"icp", value:350 },
  { name: "Lindsay Lohan", slug: "lindsaylohan", value:350 },
  { name: "Ghostface Killah", slug: "realghostfacekillah", value:350 },
  { name: "Boy George", desc:"Singer - Culture Club", slug: "boygeorge5", value:300 },
  { name: "Blac Chyna", slug: "blacchyna", value:300 },
  { name: "Andrew Dice Clay", slug: "diceman", value:299 },
  { name: "Kenny G", desc: "Saxophonist", slug:"kennyg", value:295 },
  { name: "Krysten Ritter", slug: "krystenritter", value:275 },
  { name: "Joe Piscopo", desc: "SNL", slug:"joepiscopo", value:250 },
  { name: "Stormy Daniels", desc: "Penthouse Pet", slug:"stormydaniels", value:250 },
  { name: "Hide The Pain Harold", desc: "photo meme", slug:"hidethepainharold", value:250 },
  { name: "Steve Guttenberg", slug:"steveguttenberg", value:250 },
  { name: "David Koechner", desc:"Anchorman", slug:"davidkoechner", value:225 },
  { name: "Corey Feldman", slug:"cdogg22", value:202 },
  { name: "Dog the Bounty Hunter", slug:"dogthebountyhunter", value:200 },
  { name: "Jaleel White", desc:"Urkel", slug:"dogthebountyhunter", value:200 },
  { name: "Punxsutawney Phil", desc:"World Famous Groundhog", slug:"punxsyphil", value:199 },
  { name: "Coolio", slug:"therealcoolio", value:199 },
  { name: "Sir Mix-A-Lot", slug:"therealsirmixalot", value:150  },
  { name: "Tommy Chong", desc:"Marijuana Enthusiast", slug:"tommychong", value:150  },
  { name: "Adam Duritz", desc:"Counting Crows", slug:"countingcrows", value:150  },
  { name: "Jon Lovitz", desc:"SNL", slug:"jonlovitz", value:150  },
  { name: "Gilbert Gottfried", slug:"gilbertgottfried", value:150  },
  { name: "Violent J", desc:"I’m Violent J from the band Insane Clown Posse.", slug:"violentj.icp", value:135  },
  { name: "Shaggy 2 Dope", desc:"1/2 of Insane Clown Posse", slug:"shaggy.icp", value:134  },
  { name: "Victoria Jackson", slug:"victoria_jackson_official", value:125  },
  { name: "Steve Carlson", desc:"one of the guys from the movie Slapshot", slug:"scarlson17", value:117  },
  { name: "Dave Hanson", desc:"one of the guys from the movie Slapshot", slug:"davehanson16", value:116  },
  { name: "Fiona the Hippo", slug:"fionathehippo", value:100 },
  { name: "Dave Foley", desc:"Kids in the Hall", slug:"fionathehippo", value:100 },
  { name: "Burton Gilliam", desc:"“Lyle” from Blazing Saddles", slug:"camptownladies", value:100 },
  { name: "Michael Cohen", desc:"Disbarred Lawyer", slug:"michaelcohen212", value:100 },
  { name: "Andy Dick", desc:"Newsradio", slug:"andydick", value:99 },
  { name: "Chris Kattan", desc:"SNL", slug:"chriskattan", value:95 },
  { name: "Jay Mohr", desc:"SNL", slug:"jaymohr", value:88  },
  { name: "Chumlee", desc:"Pawn Stars", slug:"chumlee", value:85  },
  { name: "Rod Blagojevich", desc:"convicted felon", slug:"rblagojevich", value:80 },
  { name: "Dana Snyder", desc:"Aqua Teen Hunger Force", slug:"eyeofthesnyder", value:75 },
  { name: "Roger Stone", desc:"Commuted Felon", slug:"rogerstone", value:75 },
  { name: "Danny Bonaduce", desc:"The Partridge Family", slug:"dannybonaduce", value:75 },
  { name: "John Kassir", desc:"voice actor of The Crypt Keeper", slug:"cryptkeeper", value:70  },
  { name: "KID from Kid N Play", desc:"That's the name he uses", slug:"kidfromkidnplay", value:65  },
  { name: "Kato Kaelin", desc:"Stayed At OJ's House", slug:"kato", value:60 },
  { name: "Anthony Scaramucci", desc:"Former White House Communications Director", slug:"bonniejoc", value:55 },
  { name: "Bonnie Chapman", desc:"Daughter of Dog The Bounty Hunter", slug:"bonniejoc", value:50  },
  { name: "Xanman", slug:"theonlyxanman20", value:50  },
  { name: "Sleazy P Martini", desc:"GWAR - Manager", slug:"sleazymartini", value:40 },
  { name: "Tay Zonday", desc:"Chocolate Rainmaker", slug:"tayzonday", value:40 },
  { name: "Smelly", desc:"Drummer - NOFX", slug:"sandin", value:40 },
  { name: "Kevin McDonald", desc:"Kids in the Hall", slug:"teaguy1", value:40 },
  { name: "Cat Drawing Guy", desc:"contestant on Shark Tank", slug:"catdrawingguy", value:39 },
  { name: "Les Gold", desc:"truTV - Hardcore Pawn", slug:"lesg", value:35 },
  { name: "Andy Kindler", slug:"andykindler", value:35 },
  { name: "Tennis", desc:"Inessential service", slug:"tennisinc", value:30 },
  { name: "Radioman", slug:"radioman", value:30 },
  { name: "Ken Bone", slug:"kenbone18", value:25 },
  { name: "Vermin Supreme", slug:"verminsupreme", value:25 },
  { name: "Boffo The Bear", slug: "boffothebear", value:20 },
  { name: "Ryan Creamer", desc:"Star of non-pornographic PornHub videos", slug: "coolboyryan", value:20 },
  { name: "Bobo Sasquatch", desc:"Finding Bigfoot", slug: "bobosquatch", value:20 },
  { name: "Matt Hoffman", desc:"CBS - Big Brother", slug: "bb12matt", value:12.5 },
  { name: "Alex Kack", desc:"Also known as #greenshirtguy", slug: "alex_kack", value:10 },
];