import { Celeb } from "./_types";

export const allValues: Celeb[] = [
  {
    name: "Kevin O'Leary",
    desc: "Shark Tank",
    slug: "mrwonderful",
    value: 1200,
  },
  {
    name: "Randy Quaid",
    desc: "Eddie in the National Lampoon Vacation movies",
    slug: "vbn",
    value: 1000,
  },
  {
    name: "Crowder",
    desc: "Contemporary Christian Musician",
    slug: "crowder",
    value: 1000,
  },
  {
    name: "Lark Voorhies",
    desc: "Lisa on Saved By The Bell",
    slug: "reallarkvoorhies",
    value: 1000,
  },
  { name: "George", desc: "A Dog", slug: "georgegsd", value: 999 },
  {
    name: "Mike Jones",
    desc: "Who? Mike Jones. Who? Mike Jones. Who? Mike Jones",
    slug: "where_mikejones",
    value: 999,
  },
  {
    name: "Craig Kilborn",
    desc: "Not The Talk Show Host You Want, But The Talk Show Host You Deserve",
    slug: "mrcraigkilborn",
    value: 950,
  },
  {
    name: "George Foreman",
    desc: "Has five sons named George (and a daughter named Georgetta)",
    slug: "georgeforeman",
    value: 750,
  },
  {
    name: "Steve Harvey",
    desc: "Game Show Host",
    slug: "steveharvey",
    value: 750,
  },
  {
    name: "Dennis Rodman",
    desc: "Friends With Kim Jong-un",
    slug: "dennisrodman",
    value: 750,
  },
  {
    name: "Tom Felton",
    desc: "Draco in Harry Potter",
    slug: "t22felton",
    value: 599,
  },
  {
    name: "Donald Trump Jr.",
    desc: "Idiot",
    slug: "donaldjtrumpjr",
    value: 500,
  },
  {
    name: "Juicy J",
    desc: "Member of Three 6 Mafia",
    slug: "juicyjay",
    value: 500,
  },
  {
    name: "Ruth Buzzi",
    desc: "Cast Member, Rowan & Martin's Laugh-In",
    slug: "ruth_buzzi",
    value: 500,
  },
  {
    name: "Don Johnson",
    desc: "Sonny on Miami Vice",
    slug: "donjohnson",
    value: 500,
  },
  {
    name: "Lil' Kim",
    desc: "Used to hang out with Notorious B.I.G.",
    slug: "lilkimthequeenbee",
    value: 500,
  },
  { name: "Ice T", desc: "Law & Order: SVU", slug: "icet", value: 500 },
  { name: "Ice Cube", desc: "Actor, Friday", slug: "donmega69", value: 500 },
  {
    name: "Mehmet Oz",
    desc: "Still has a medical license for some reason",
    slug: "droz",
    value: 500,
  },
  {
    name: "Steve Wozniak",
    desc: "Apple Co-Founder",
    slug: "stevewoz",
    value: 500,
  },
  {
    name: "Chris Tucker",
    desc: "Carter in Rush Hour 1, 2 & 3",
    slug: "christucker404",
    value: 500,
  },
  {
    name: "Rebecca Black",
    desc: "Singer of “Friday”",
    slug: "rebeccablack",
    value: 500,
  },
  {
    name: "Blac Chyna",
    desc: "Model & Socialite",
    slug: "blacchyna",
    value: 500,
  },
  {
    name: "Tommy Lee",
    desc: "Former Husband, Pamela Anderson",
    slug: "tommylee",
    value: 500,
  },
  {
    name: "Robert Englund",
    desc: "Freddy Krueger",
    slug: "robertenglund",
    value: 500,
  },
  {
    name: "LeVar Burton",
    desc: "Host, Reading Rainbow",
    slug: "levarburton",
    value: 450,
  },
  {
    name: "Chuck Norris",
    desc: "Movie Kicker",
    slug: "chucknorris",
    value: 450,
  },
  {
    name: "John Cleese",
    desc: "Member, Monty Python",
    slug: "notsirjohncleese",
    value: 450,
  },
  {
    name: "Flavor Flav",
    desc: "Formerly of Public Enemy",
    slug: "flavorflav",
    value: 400,
  },
  {
    name: "Jeremy Piven",
    desc: "Ari on Entourage",
    slug: "jeremypiven",
    value: 400,
  },
  {
    name: "Tacko Fall",
    desc: "7'5\" NBA Basketball Player",
    slug: "tackofall99",
    value: 400,
  },
  {
    name: "Rudy W. Giuliani",
    desc: "No longer licensed to practice law.",
    slug: "rudygiuliani",
    value: 375,
  },
  {
    name: "Jeff Garlin",
    desc: "Larry's agent on Curb Your Enthusiasm",
    slug: "thejeffgarlin",
    value: 350,
  },
  {
    name: "Wu-Tang Clan",
    desc: "Okay, so the Cameo profile says “Wu-Tang Clan”, but it's actually just Masta Killa",
    slug: "wutang",
    value: 350,
  },
  {
    name: "John C. McGinley",
    desc: "Dr. Cox on Scrubs",
    slug: "johncmcginley",
    value: 350,
  },
  {
    name: "Insane Clown Posse",
    desc: "Unaware of how magnets work",
    slug: "icp",
    value: 350,
  },
  {
    name: "Lindsay Lohan",
    desc: "Actress, The Parent Trap",
    slug: "lindsaylohan",
    value: 350,
  },
  {
    name: "Ghostface Killah",
    desc: "Member of Wu-Tang Clan",
    slug: "realghostfacekillah",
    value: 350,
  },
  {
    name: "Pauly Shore",
    desc: "Bio-Dome & Encino Man",
    slug: "paulyshore",
    value: 350,
  },
  {
    name: "Dolph Lundgren",
    desc: "Ivan Drago, Rocky IV",
    slug: "dolphlundgren",
    value: 350,
  },
  {
    name: "Engelbert Humperdinck",
    desc: "Singer, “Spanish Eyes”",
    slug: "engelberthumperdinck",
    value: 345,
  },
  {
    name: "Wayne Knight",
    desc: "Newman on Seinfeld, Nedry in Jurassic Park",
    slug: "wanite1",
    value: 330,
  },
  {
    name: "Vicente Fox",
    desc: "Former President of Mexico",
    slug: "presidentfox",
    value: 300,
  },
  {
    name: "Jonathan Frakes",
    desc: "Riker on Star Trek TNG",
    slug: "windyoaks",
    value: 300,
  },
  {
    name: "The Situation",
    desc: "MTV's Jersey Shore",
    slug: "mikethesituation",
    value: 300,
  },
  {
    name: "Boy George",
    desc: "Singer, Culture Club",
    slug: "boygeorge5",
    value: 300,
  },
  { name: "Ted Nugent", desc: "Gun Enthusiast", slug: "tednugent", value: 300 },
  {
    name: "Ray Lewis",
    desc: "NFL Hall of Famer & Suspected Accessory To Murder",
    slug: "raylewis",
    value: 300,
  },
  {
    name: "Elijah Wood",
    desc: "Frodo in Lord of the Rings",
    slug: "elijahwood",
    value: 300,
  },
  {
    name: "Nicole “Snooki” Polizzi",
    desc: "MTV's Jersey Shore",
    slug: "snooki",
    value: 300,
  },
  {
    name: "Lance Bass",
    desc: "One of the boys in *NSYNC who wasn't Justin Timberlake",
    slug: "lancebass",
    value: 299,
  },
  {
    name: "Michael Buffer",
    desc: "the guy who says “Let’s Get Ready To Rumble!”",
    slug: "michaelbuffer",
    value: 299,
  },
  {
    name: "Andrew Dice Clay",
    desc: "Sold Out Madison Square Garden",
    slug: "diceman",
    value: 299,
  },
  {
    name: "Scott Stapp",
    desc: "Singer, Creed",
    slug: "scottstapp",
    value: 299,
  },
  {
    name: "Chris Diamantopoulos",
    desc: "Russ Hanneman in Silicon Valley",
    slug: "chrisdiamantopoulos",
    value: 299,
  },
  {
    name: "Lee Majors",
    desc: "aka “The Six Million Dollar Man”",
    slug: "leemajors",
    value: 299,
  },
  {
    name: "Brent Spiner",
    desc: "Data on Star Trek TNG",
    slug: "brentspiner",
    value: 299,
  },
  { name: "Kenny G", desc: "Saxophonist", slug: "kennyg", value: 295 },
  {
    name: "Sean Astin",
    desc: "Sam in The Lord of the Rings",
    slug: "seanastin",
    value: 295,
  },
  {
    name: "Krysten Ritter",
    desc: "The B---- in Apartment 23",
    slug: "krystenritter",
    value: 275,
  },
  { name: "deadmau5", desc: "Canadian DJ", slug: "deadmau5", value: 269 },
  {
    name: "A.J. & Big Justice",
    desc: "They say “we're Costco guys” on TikTok",
    slug: "ajandbigjustice",
    value: 250,
  },
  {
    name: "George Papadopoulos",
    desc: "Served Twelve Days In Prison Before Getting Pardoned",
    slug: "papadopoulos",
    value: 250,
  },
  {
    name: "Bobby Brown",
    desc: "Former Husband of Whitney Houston",
    slug: "brownbomber",
    value: 250,
  },
  {
    name: "Shirtless Violinist",
    desc: "Plays The Violin (Without A Shirt On)",
    slug: "shirtlessviolinist",
    value: 250,
  },
  {
    name: "Joe Piscopo",
    desc: "Star of Dead Heat",
    slug: "joepiscopo",
    value: 250,
  },
  {
    name: "Stormy Daniels",
    desc: "Hush Money Recipient",
    slug: "stormydaniels",
    value: 250,
  },
  {
    name: "Hide The Pain Harold",
    desc: "Photo Meme",
    slug: "hidethepainharold",
    value: 250,
  },
  {
    name: "Steve Guttenberg",
    desc: "Police Academy 1-4",
    slug: "steveguttenberg",
    value: 250,
  },
  {
    name: "Jonathan Goldsmith",
    desc: "The Most Interesting Man, Dos Equis Commercials",
    slug: "stayinteresting",
    value: 250,
  },
  {
    name: "Richard Marx",
    desc: "Wherever you go, whatever you do, he will be right here waiting for you.",
    slug: "richardmarx",
    value: 250,
  },
  {
    name: "Jeff Ross",
    desc: "Does those Comedy Central Roasts",
    slug: "jeffross",
    value: 250,
  },
  {
    name: "Micky Dolenz",
    desc: "One Of The Monkees",
    slug: "mickydolenz",
    value: 239,
  },
  {
    name: "Patrick Fabian",
    desc: "Howard Hamlin on Better Call Saul",
    slug: "mrpatrickfabian",
    value: 235,
  },
  {
    name: "Xzibit",
    desc: "Host, “Pimp My Ride”",
    slug: "xzibit",
    value: 225,
  },
  {
    name: "David Koechner",
    desc: "Champ in Anchorman",
    slug: "davidkoechner",
    value: 225,
  },
  {
    name: "Corey Feldman",
    desc: "Mouth in The Goonies",
    slug: "cdogg22",
    value: 202,
  },
  {
    name: "Jacoby Shaddix",
    desc: "Singer, Papa Roach",
    slug: "jacobyshaddix",
    value: 200,
  },
  {
    name: "Bob Bergen",
    desc: "Voice Actor, Porky Pig (1990 - present)",
    slug: "bobbergen",
    value: 200,
  },
  {
    name: "Dog the Bounty Hunter",
    desc: "Had a reality show on A&E",
    slug: "dogthebountyhunter",
    value: 200,
  },
  { name: "Jaleel White", desc: "Urkel", slug: "jaleelwhite", value: 200 },
  {
    name: "Dee Snider",
    desc: "Singer - Twisted Sister",
    slug: "deesnider",
    value: 200,
  },
  {
    name: "George Clinton",
    desc: "Parliament Funkadelic",
    slug: "george_clinton",
    value: 200,
  },
  {
    name: "Henry",
    desc: "aka The NoTortoise BIG",
    slug: "thenotortoisebig",
    value: 200,
  },
  {
    name: "John Popper",
    desc: "Singer & Harmonica Player, Blues Traveler",
    slug: "johnpopper",
    value: 200,
  },
  {
    name: "Sarah Palin",
    desc: "Portent of things to come",
    slug: "sarahpalin",
    value: 200,
  },
  {
    name: "George Hamilton",
    desc: "Incredibly Tan Actor",
    slug: "georgehamilton",
    value: 200,
  },
  {
    name: "Martin Kove",
    desc: "The bad guy in Karate Kid",
    slug: "martinkove",
    value: 199,
  },
  {
    name: "Punxsutawney Phil",
    desc: "World Famous Groundhog",
    slug: "punxsyphil",
    value: 199,
  },
  {
    name: "Dr Drew",
    desc: "Radio Doctor, “Loveline”",
    slug: "drdrew",
    value: 198,
  },
  {
    name: "Jonathan Van Ness",
    desc: "The hair guy in the Queer Eye reboot",
    slug: "jvn",
    value: 175,
  },
  {
    name: "Ben Sinclair",
    desc: "The Guy on High Maintenance",
    slug: "bathroomremodel",
    value: 175,
  },
  {
    name: "Redman",
    desc: "Friends with Method Man",
    slug: "redman",
    value: 160,
  },
  {
    name: "Kel Mitchell",
    desc: "Not Kenan, Kel.",
    slug: "kelmitchell",
    value: 159,
  },
  {
    name: "Ben Stein",
    desc: "Fan of Richard Nixon, said “Bueller?” in Ferris Bueller's Day Off",
    slug: "benstein99",
    value: 150,
  },
  {
    name: "Sir Mix-A-Lot",
    desc: "Likes big butts, can't lie",
    slug: "therealsirmixalot",
    value: 150,
  },
  {
    name: "Tommy Chong",
    desc: "Marijuana Enthusiast",
    slug: "tommychong",
    value: 150,
  },
  {
    name: "Adam Duritz",
    desc: "Counting Crows",
    slug: "countingcrows",
    value: 150,
  },
  {
    name: "Jon Lovitz",
    desc: "“Yeah, That's The Ticket”, SNL",
    slug: "jonlovitz",
    value: 150,
  },
  {
    name: "Jamie Lynn Sigler",
    desc: "Meadow on The Sopranos",
    slug: "jamielynnsigler",
    value: 150,
  },
  {
    name: "Bret “Hitman” Hart",
    desc: "Former Professional Wrestler",
    slug: "hitman",
    value: 150,
  },
  {
    name: "Danica McKellar",
    desc: "Winnie Cooper on The Wonder Years",
    slug: "danicamckellar",
    value: 150,
  },
  {
    name: "Alfonso Ribeiro",
    desc: "Carlton on The Fresh Prince of Bel-Air",
    slug: "therealalfonsoribeiro",
    value: 150,
  },
  {
    name: "Tom Wilson",
    desc: "Biff in Back The The Future",
    slug: "tomwilson1",
    value: 150,
  },
  {
    name: "Barry Williams",
    desc: "Greg on The Brady Bunch",
    slug: "barrywilliams",
    value: 140,
  },
  {
    name: "Island Boys",
    desc: "TikTok singers",
    slug: "islandboys",
    value: 140,
  },
  {
    name: "Tom Arnold",
    desc: "Was briefly married to Roseanne",
    slug: "thetomarnold",
    value: 139,
  },
  { name: "Penn Jillette", desc: "Penn & Teller", slug: "pennj", value: 135 },
  {
    name: "Ernie Hudson",
    desc: "Winston in Ghostbusters",
    slug: "kirbyzook",
    value: 135,
  },

  {
    name: "Violent J",
    desc: "Insane Clown Posse",
    slug: "violentj.icp",
    value: 135,
  },
  {
    name: "Shaggy 2 Dope",
    desc: "Insane Clown Posse",
    slug: "shaggy.icp",
    value: 134,
  },

  {
    name: "Steven Ogg",
    desc: "Trevor in Grand Theft Auto V",
    slug: "stevenogg",
    value: 130,
  },
  {
    name: "Chris Kirkpatrick",
    desc: "Formerly of *NSYNC",
    slug: "iamckirkpatrick",
    value: 129,
  },
  {
    name: "Lisa Ann",
    desc: "Who's Nailin Paylin  (2008)",
    slug: "thereallisaann",
    value: 125,
  },
  {
    name: "Victoria Jackson",
    desc: "SNL",
    slug: "victoria_jackson_official",
    value: 125,
  },
  {
    name: "Vincent Curatola",
    desc: "Johnny Sack on The Sopranos",
    slug: "vincentcuratola",
    value: 125,
  },
  {
    name: "Jamie Farr",
    desc: "Klinger on M*A*S*H",
    slug: "jamiefarr1",
    value: 125,
  },
  {
    name: "Andrea Barber",
    desc: "Kimmy Gibler on Full House",
    slug: "andreabarber",
    value: 125,
  },
  {
    name: "Johnny Brennan",
    desc: "The guy who did those Jerky Boys CDs. Also there was a movie for some reason?",
    slug: "johnnybrennan",
    value: 120,
  },
  {
    name: "Takeru Kobayashi",
    desc: "Competitive Gurgitator",
    slug: "takerukobayashi",
    value: 120,
  },
  {
    name: "Steve Carlson",
    desc: "One of the guys from the movie Slapshot",
    slug: "scarlson17",
    value: 117,
  },
  {
    name: "Dave Hanson",
    desc: "One of the guys from the movie Slapshot",
    slug: "davehanson16",
    value: 116,
  },

  {
    name: "John Bercow",
    desc: "The Guy That Used To Say “Order” In The House of Commons",
    slug: "johnbercow",
    value: 110,
  },
  {
    name: "Colin Mochrie",
    desc: "Perennial Contestant, Whose Line is it Anyway?",
    slug: "colinmochrie7591",
    value: 110,
  },
  {
    name: "Colin Baker",
    desc: "The Sixth Doctor on Doctor Who (1984 - 1986)",
    slug: "colinbaker",
    value: 105,
  },
  {
    name: "Brutus “The Barber” Beefcake",
    desc: "#173 in Pro Wrestling Illustrated's “500 Best Single Wrestlers”",
    slug: "brutusbeefcake",
    value: 100,
  },
  {
    name: "Sylvester McCoy",
    desc: "The Seventh Doctor on Doctor Who (1987 - 1989)",
    slug: "earthling7",
    value: 100,
  },
  { name: "SISQÓ", desc: "wants to see your thong", slug: "sisqo", value: 100 },

  {
    name: "Nigel Farage",
    desc: "Caused Brexit, Pretty Much",
    slug: "nigelfarage",
    value: 100,
  },
  {
    name: "Fiona the Hippo",
    desc: "The Cincinnati Zoo’s premature baby hippo",
    slug: "fionathehippo",
    value: 100,
  },
  { name: "Dave Foley", desc: "Kids in the Hall", slug: "dsf", value: 100 },
  {
    name: "Mick Foley",
    desc: "Former Professional Wrestler",
    slug: "mickfoley",
    value: 100,
  },
  {
    name: "Burton Gilliam",
    desc: "“Lyle” in Blazing Saddles",
    slug: "camptownladies",
    value: 100,
  },
  {
    name: "Montell Jordan",
    desc: "Singer, “This Is How We Do It”",
    slug: "mrjordan1911",
    value: 100,
  },
  {
    name: "Michael Cohen",
    desc: "Disbarred Legal Fixer",
    slug: "michaelcohen212",
    value: 100,
  },
  {
    name: "Lisa Loeb",
    desc: "You say she only hears what she wants to.",
    slug: "lisaloeb",
    value: 100,
  },
  {
    name: "Richard Karn",
    desc: "Al on Home Improvement",
    slug: "richardkarn",
    value: 100,
  },
  {
    name: "Doug Bradley",
    desc: "Pinhead in Hellraiser",
    slug: "dougbradley",
    value: 100,
  },
  { name: "Don Juan", desc: "Former Pimp", slug: "bishopdonjuan", value: 100 },
  {
    name: "Wayne Coyne",
    desc: "Singer, Flaming Lips",
    slug: "waynecoyne",
    value: 100,
  },
  {
    name: "Richard Kline",
    desc: "Larry on Three's Company",
    slug: "larrydallas",
    value: 100,
  },
  {
    name: "David Faustino",
    desc: "Bud Bundy on Married With Children",
    slug: "davidfaustino",
    value: 100,
  },
  {
    name: "Giorgio A. Tsoukalos",
    desc: "History's “Ancient Aliens”",
    slug: "thealiensguy",
    value: 100,
  },
  {
    name: "Sean Spicer",
    desc: "Donald Trump's Press Secretary (#1 of 5)",
    slug: "seanspicer",
    value: 99,
  },
  { name: "Dean Ween", desc: "1/2 Of Ween", slug: "deanween", value: 99 },
  {
    name: "Andy Dick",
    desc: "Matthew on Newsradio",
    slug: "andydick",
    value: 99,
  },
  {
    name: "Kristian Nairn",
    desc: "Hodor on Game of Thrones",
    slug: "kristiannairn",
    value: 99,
  },
  {
    name: "Basil Brush",
    desc: "a fox puppet from a British children's show",
    slug: "basilbrush",
    value: 97,
  },
  {
    name: "Chris Kattan",
    desc: "Played a monkey called Peepers on SNL",
    slug: "chriskattan",
    value: 95,
  },
  { name: "HR", desc: "Front Man, Bad Brains", slug: "hrmusic", value: 95 },
  {
    name: "Gibby Haynes",
    desc: "Singer, Butthole Surfers",
    slug: "gibbyhaynes",
    value: 95,
  },
  {
    name: "Mark McGrath",
    desc: "Singer, Sugar Ray",
    slug: "markmcgrath",
    value: 90,
  },
  {
    name: "Perez Hilton",
    desc: "Gossip Blogger",
    slug: "perezhilton",
    value: 90,
  },
  {
    name: "Jay Mohr",
    desc: "Actor, The Ghost Whisperer",
    slug: "jaymohr",
    value: 88,
  },
  {
    name: "David Siegel",
    desc: "George Clooney Lookalike",
    slug: "davidasclooney",
    value: 85,
  },
  { name: "Chumlee", desc: "Pawn Stars", slug: "chumlee", value: 85 },
  {
    name: "Donald Gibb",
    desc: "Ogre in Revenge of the Nerds",
    slug: "ogre1",
    value: 85,
  },
  { name: "RiFF RAFF", desc: "Public Nuisance", slug: "riffraff", value: 85 },
  {
    name: "Rod Blagojevich",
    desc: "Convicted Felon",
    slug: "rblagojevich",
    value: 80,
  },
  {
    name: "Larry Thomas",
    desc: "The Soup Nazi",
    slug: "realsoupnazi",
    value: 80,
  },
  {
    name: "Maci Bookout",
    desc: "Former Teen Mom, MTV's “Teen Mom”",
    slug: "macibookout",
    value: 80,
  },
  {
    name: "George Shea",
    desc: "You Know Those Hot Dog Eating Contests? This Is The Guy That Emcees Them.",
    slug: "gcshea",
    value: 50,
  },
  {
    name: "Kody Brown",
    desc: "Has Four Wives, TLC Made A Show About It",
    slug: "kodywinnbrown",
    value: 75,
  },
  {
    name: "Jennifer Elise Cox",
    desc: "Jan on The Brady Bunch",
    slug: "jenniferelisecox",
    value: 75,
  },
  {
    name: "Dana Snyder",
    desc: "Voice of Master Shake",
    slug: "eyeofthesnyder",
    value: 75,
  },
  {
    name: "Didi Conn",
    desc: "Frenchy in Grease",
    slug: "didiconn1",
    value: 75,
  },
  {
    name: "Roger Stone",
    desc: "Commuted Felon",
    slug: "rogerstone",
    value: 75,
  },
  {
    name: "Danny Bonaduce",
    desc: "The Partridge Family",
    slug: "dannybonaduce",
    value: 75,
  },
  {
    name: "Butterbean",
    desc: "Professional Boxer (Retired)",
    slug: "butterbean67",
    value: 75,
  },
  {
    name: "Hacksaw Jim Duggan",
    desc: "Former Professional Wrestler",
    slug: "hacksawjimduggan",
    value: 75,
  },
  {
    name: "Doug E. Fresh",
    desc: "La Di Da Di, He Likes To Party",
    slug: "dougeversofresh",
    value: 75,
  },
  {
    name: "Peter Keys",
    desc: "Keyboardist for Lynyrd Skynyrd",
    slug: "peterkeys",
    value: 75,
  },
  {
    name: "Ted DiBiase",
    desc: "aka “The Million Dollar Man”",
    slug: "mdmteddibiase",
    value: 75,
  },
  {
    name: "John Kassir",
    desc: "Voice Actor of the Crypt Keeper",
    slug: "cryptkeeper",
    value: 70,
  },
  {
    name: "Steve Wilkos",
    desc: "Former Security, “The Jerry Springer Show”",
    slug: "stevewilkos",
    value: 70,
  },
  {
    name: "George Clanton",
    desc: "Vaporwave Musician",
    slug: "georgeclanton",
    value: 69,
  },
  {
    name: "KID from Kid N Play",
    desc: "Costar of House Party 1, 2 & 3",
    slug: "kidfromkidnplay",
    value: 65,
  },
  {
    name: "Kato Kaelin",
    desc: "Stayed At OJ's House",
    slug: "kato",
    value: 60,
  },
  {
    name: "Anthony Scaramucci",
    desc: "Former White House Communications Director",
    slug: "themooch",
    value: 55,
  },
  {
    name: "Lavell Crawford",
    desc: "Huell on Breaking Bad/Better Call Saul",
    slug: "lavellthacomic",
    value: 50,
  },
  {
    name: "Rednex",
    desc: "The Band that did that “Cotton Eye Joe” song (the whole band)",
    slug: "rednexofficial",
    value: 50,
  },
  {
    name: "George Santos",
    desc: "former New York Congressman and Felon",
    slug: "gads",
    value: 50,
  },
  {
    name: "George Wallace",
    desc: "The Legendary Comedian (Not The Racist Senator)",
    slug: "georgewallace",
    value: 50,
  },
  {
    name: "Horny Mike",
    desc: "Airbrushes Cars, Sometimes Wears A Bandana With Horns On It",
    slug: "hornymike",
    value: 50,
  },
  {
    name: "Pearl Mackie",
    desc: "Bill on Doctor Who (2016 - 2017)",
    slug: "pearlmackie",
    value: 50,
  },
  {
    name: "Bonnie Chapman",
    desc: "Daughter of Dog The Bounty Hunter",
    slug: "bonniejoc",
    value: 50,
  },
  {
    name: "Deep Roy",
    desc: "Oompa Loompa in the 2015 Willy Wonka movie",
    slug: "deeproy",
    value: 50,
  },
  { name: "Xanman", desc: "Fan of Xanax", slug: "theonlyxanman20", value: 50 },
  {
    name: "Chris Hansen",
    desc: "Host, “To Catch A Predator”",
    slug: "chansen",
    value: 50,
  },
  { name: "iAmMoshow", desc: "The Cat Rapper", slug: "iammoshow", value: 50 },
  {
    name: "Max Cavalera",
    desc: "Vocalist, Sepultura",
    slug: "maxcavalera",
    value: 50,
  },
  {
    name: "April & Phil Margera",
    desc: "Bam Margera's Parents",
    slug: "aprilmargera",
    value: 50,
  },
  {
    name: "Jonathan Schmock",
    desc: "The Maître D' in Ferris Bueller's Day Off",
    slug: "snooty",
    value: 50,
  },
  {
    name: "June Shannon",
    desc: "Honey Boo Boo's Biological Mother",
    slug: "mamajune",
    value: 50,
  },
  {
    name: "D-Roc",
    desc: "One of the Ying Yang Twins",
    slug: "yingyangtwins",
    value: 50,
  },
  {
    name: "Squid the Griff",
    desc: "Instagram Dog",
    slug: "squidthegriff",
    value: 50,
  },
  {
    name: "Prince Charles-Henri de Lobkowicz",
    desc: "French Nobleman",
    slug: "princecharleshenri",
    value: 50,
  },
  {
    name: "Bubba the Love Sponge",
    desc: "Filmed his wife having sex with Hulk Hogan",
    slug: "thebubbaarmy",
    value: 50,
  },
  {
    name: "Jamie Kennedy",
    desc: "Randy Meeks in Scream",
    slug: "jamiekennedy25",
    value: 50,
  },
  {
    name: "Paul Chuckle",
    desc: "One of the Chuckle Brothers",
    slug: "chuckle",
    value: 49,
  },
  {
    name: "Paula Poundstone",
    desc: "Panelist, “Wait Wait... Don't Tell Me”",
    slug: "paulap33",
    value: 49,
  },
  {
    name: "Count Binface",
    desc: "Formerly Lord Buckethead",
    slug: "countbinface",
    value: 45,
  },
  {
    name: "Kevin Allison",
    desc: "RISK! Podcast",
    slug: "thekevinallison",
    value: 45,
  },
  { name: "Evan Antin", desc: "Veterinarian", slug: "dr.evanantin", value: 45 },
  {
    name: "Mermaid Elle",
    desc: "Freelance Mermaid",
    slug: "mermaidelle",
    value: 45,
  },
  {
    name: "That Vegan Teacher",
    desc: "screams at people on TikTok for eating meat",
    slug: "thatveganteacher",
    value: 40,
  },
  {
    name: "Mathew Knowles",
    desc: "Beyoncé's Dad",
    slug: "mathewknowles",
    value: 40,
  },
  {
    name: "Sleazy P Martini",
    desc: "Manager, GWAR",
    slug: "sleazymartini",
    value: 40,
  },
  {
    name: "Tay Zonday",
    desc: "Chocolate Rainmaker",
    slug: "tayzonday",
    value: 40,
  },
  { name: "Smelly", desc: "Drummer for NOFX", slug: "sandin", value: 40 },
  {
    name: "Kevin McDonald",
    desc: "Kids in the Hall",
    slug: "teaguy1",
    value: 40,
  },
  {
    name: "Cat Drawing Guy",
    desc: "Contestant on Shark Tank",
    slug: "catdrawingguy",
    value: 39,
  },
  {
    name: "Les Gold",
    desc: "pawn store owner, “Hardcore Pawn”",
    slug: "lesg",
    value: 35,
  },
  {
    name: "Andy Kindler",
    desc: "Mort on Bob's Burgers",
    slug: "andykindler",
    value: 35,
  },
  {
    name: "Chris Gethard",
    desc: "Host, “The Chris Gethard Show”",
    slug: "chrisgeth",
    value: 35,
  },
  {
    name: "Tim Ripper Owens",
    desc: "Singer of Judas Priest during Rob Halford's Hiatus",
    slug: "ripper",
    value: 35,
  },
  { name: "Tennis", desc: "Inessential service", slug: "tennisinc", value: 30 },
  {
    name: "Radioman",
    desc: "Actor in Little Nicky",
    slug: "radioman",
    value: 30,
  },
  {
    name: "Eamon Sandwith",
    desc: "Vocals & Bass, The Chats",
    slug: "eamonsandwith",
    value: 30,
  },
  {
    name: "Joe Arpaio",
    desc: "Former sheriff, convicted of criminal contempt",
    slug: "sheriffjoearpaio",
    value: 30,
  },
  {
    name: "William Hung",
    desc: "Sang poorly on American Idol",
    slug: "williamhung.co",
    value: 30,
  },
  {
    name: "Perry Richardson",
    desc: "Bassist, Stryper",
    slug: "perryrichardson",
    value: 29,
  },
  {
    name: "Kanye East",
    desc: "pretends to be Kanye West",
    slug: "thekanyeeast",
    value: 25,
  },
  {
    name: "Ken Bone",
    desc: "Wore a red sweater at a Presidential debate",
    slug: "kenbone18",
    value: 25,
  },
  {
    name: "Vermin Supreme",
    desc: "Presidential Candidate & Performance Artist",
    slug: "verminsupreme",
    value: 25,
  },
  {
    name: "David Ellefson",
    desc: "Former Bassist, Megadeth",
    slug: "davidellefson",
    value: 25,
  },
  {
    name: "Kyle Troup",
    desc: "Professional Bowler",
    slug: "afrofish300",
    value: 25,
  },
  {
    name: "Jonah Falcon",
    desc: 'Has a 13.5" penis. Talks about it a lot',
    slug: "jonahfalcon1970",
    value: 25,
  },
  {
    name: "Boffo The Bear",
    desc: "YouTube Comedy Bear",
    slug: "boffothebear",
    value: 20,
  },
  {
    name: "Ray Williams",
    desc: "Olympic Deadlifter",
    slug: "optimusprime_334",
    value: 20,
  },
  {
    name: "Bobo Sasquatch",
    desc: "Finding Bigfoot",
    slug: "bobosquatch",
    value: 20,
  },
  {
    name: "Kent “Toast” French",
    desc: "“The World's Fastest Clapper”",
    slug: "kentfrench",
    value: 15,
  },
  {
    name: "Jonathan Donais",
    desc: "Guitarist, Anthrax",
    slug: "jondonais",
    value: 15,
  },
  { name: "Puggy Smalls", desc: "Dog", slug: "thepuggysmalls", value: 15 },
  {
    name: "Matt Hoffman",
    desc: "CBS - Big Brother",
    slug: "bb12matt",
    value: 13,
  },
  {
    name: "Alex Kack",
    desc: "Also known as #greenshirtguy",
    slug: "alex_kack",
    value: 10,
  },
  {
    name: "Ben Odenkirk",
    desc: `Does Bob Odenkirk impressions, despite neither looking nor sounding like Bob Odenkirk.`,
    slug: "benacing",
    value: 1,
  },
];

export const deadCelebrities: Celeb[] = [
  { name: "George Lowe", desc: "Space Ghost", slug: "georgeloweofficial", value: 100 },
  {
    name: "Bob Saget",
    desc: "Danny on Full House",
    slug: "bobsagetofficial",
    value: 350,
  },
  {
    name: "Coolio",
    desc: "Cowrote Gangsta's Paradise",
    slug: "therealcoolio",
    value: 199,
  },
  {
    name: "Jerry Springer",
    desc: "Former Mayor of Cincinnati",
    slug: "jerryspringer",
    value: 135,
  },
  {
    name: "Jackie Mason",
    desc: "Rabbi Hyman Krustofski on The Simpsons",
    slug: "jackiemason",
    value: 350,
  },
  {
    name: "Gilbert Gottfried",
    desc: "Iago in Aladdin",
    slug: "gilbertgottfried",
    value: 150,
  },
  {
    name: "Meat Loaf",
    desc: "Contestant, The Celebrity Apprentice",
    slug: "meatloaf",
    value: 170,
  },
  {
    name: "George Wendt",
    desc: "Norm on Cheers",
    slug: "georgewendt",
    value: 125,
  },
];
