on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Job triggered by a ${{ github.event_name }}.
        run: echo "🚀 Job triggered by a ${{ github.event_name }}."

      - name: 👀 Checking out ${{ github.ref }}...
        uses: actions/checkout@v2
        with:
            ref: ${{ github.ref }}
            fetch-depth: 10
            submodules: true

      - name: 🗑️ Remove sourcemapped CSS.
        run: rm public/css -r
      
      - name: 🪄 Make a new production CSS directory
        run: mkdir public/css

      - name: 🗜️ Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.5.1
        with:
          source: |
            scss/start.scss
            scss/cameo.scss
            scss/guillotine/code.scss
            scss/guillotine/site.scss
            scss/invalid.scss
            scss/pretend.scss
            scss/sisyphus.scss
            scss/wrongest.scss
            scss/stats.scss
          destination: |
            public/css/start.css
            public/css/cameo.css
            public/css/guillotine.code.css
            public/css/guillotine.css
            public/css/invalid.css
            public/css/pretend.css
            public/css/sisyphus.css
            public/css/wrongest.css
            public/css/stats.css

      - name: 🗃️ commit changes to ${{ github.ref }}
        uses: elstudio/actions-js-build/commit@v4
        with:
          commitMessage: generate minified css 
      
      - name: 🫠 This job's status is ${{ job.status }}.
        run: echo "🫠 This job's status is ${{ job.status }}."