export const challenges = [
  // Mortal Kombat | 1
  {
    id: 1,
    name: "Mortal Kombat",
    nameAsRule: "Your password must be a playable Mortal Kombat character",
    failedMessage: "[PASS] is not a playable Mortal Kombat character",
    possible: [
      "JOHNNY CAGE",
      "KANO",
      "LIU KANG",
      "RAIDEN",
      "SCORPION",
      "SONYA BLADE",
      "SUB-ZERO",
      "GORO",
      "SHANG TSUNG",
      "REPTILE",
      "BARAKA",
      "JADE",
      "JAX",
      "KINTARO",
      "KITANA",
      "KUNG LAO",
      "MILEENA",
      "NOOB SAIBOT",
      "SHAO KHAN",
      "SMOKE",
      "CHAMELEON",
      "CYRAX",
      "ERMAC",
      "KABAL",
      "KHAMELEON",
      "MOTARO",
      "NIGHTWOLF",
      "RAIN",
      "SEKTOR",
      "SHEEVA",
      "SINDEL",
      "STRYKER",
      "MEAT",
      "BO RAI CHO",
      "FROST",
    ],
    source: "https://en.wikipedia.org/wiki/List_of_Mortal_Kombat_characters",
  },

  // Bob's Burgers | 2
  {
    id: 2,
    name: "Bob's Burgers",
    nameAsRule: "Your password must be the first name of a Bob's Burgers character.",
    failedMessage: "[PASS] is not the first name of a main or recurring Bob's Burgers character.",
    possible: [
      "BOB",
      "LINDA",
      "TINA",
      "GENE",
      "LOUISE",
      "TEDDY",
      "MORT",
      "GAYLE",
      "CALVIN",
      "FELIX",
      "MARSHMALLOW",
      "JIMMY",
      "ANDY",
      "OLLIE",
      "TAMMY",
      "JOCELYN",
      "ZEKE",
      "RUDY",
      "COURTNEY",
      "DARRYL",
      "HENRY",
      "HUGO",
      "PHILLIP", // Mr. Frond's first name
      "EDITH",
      "GRETCHEN",
      "NAT",
      "AL",
      "GLORIA",
      "JAIRO",
      "RON",
      "PETER",
      "JEREMY",
      "CHOO-CHOO",
      "MIKE", // Mike the mailman
      "CHLOE",
      "ABBY",
      "JODI",
      "TOMMY", // Tommy is the first name of "Large Tommy"
      "TREV",
      "HAROLD",
      "MARTHA",
    ],
    source: "https://en.wikipedia.org/wiki/List_of_Bob's_Burgers_characters",
  },

  // African Countries | 4
  {
    id: 4,
    name: "African Countries",
    nameAsRule: "Your password MUST be a country in Africa",
    failedMessage: "[PASS] is not an African country",
    possible: [
      "ALGERIA",
      "ANGOLA",
      "BENIN",
      "BOTSWANA",
      "ALGERIA",
      "ANGOLA",
      "BENIN",
      "BOTSWANA",
      "BURKINA FASO",
      "BURUNDI",
      "CABO VERDE",
      "CAMEROON",
      "CENTRAL AFRICAN REPUBLIC",
      "CHAD",
      "COMOROS",
      "REPUBLIC OF THE CONGO",
      "DEMOCRATIC REPUBLIC OF THE CONGO",
      "COTE D'IVOIRE",
      "DJIBOUTI",
      "EGYPT",
      "EQUATORIAL GUINEA",
      "ERITREA",
      "ESWATINI",
      "ETHIOPIA",
      "GABON",
      "GAMBIA",
      "GHANA",
      "GUINEA",
      "GUINEA-BISSAU",
      "KENYA",
      "LESOTHO",
      "LIBERIA",
      "LIBYA",
      "MADAGASCAR",
      "MALAWI",
      "MALI",
      "MAURITANIA",
      "MAURITIUS",
      "MOROCCO",
      "MOZAMBIQUE",
      "NAMIBIA",
      "NIGER",
      "NIGERIA",
      "RWANDA",
      "SENEGAL",
      "SEYCHELLES",
      "SIERRA LEONE",
      "SOMALIA",
      "SOUTH AFRICA",
      "SOUTH SUDAN",
      "SUDAN",
      "TANZANIA",
      "TOGO",
      "TUNISIA",
      "UGANDA",
      "ZAMBIA",
      "ZIMBABWE",
    ],
  },

  // NFL Football Teams | 6
  {
    id: 6,
    name: "NFL Football",
    nameAsRule: "Your password must be an NFL football team name",
    failedMessage: "Sorry! There are no [PASS] in the NFL.",
    possible: [
      "CARDINALS",
      "FALCONS",
      "PANTHERS",
      "BEARS",
      "COWBOYS",
      "LIONS",
      "PACKERS",
      "RAMS",
      "VIKINGS",
      "SAINTS",
      "GIANTS",
      "EAGLES",
      "49ERS",
      "SEAHAWKS",
      "BUCCANEERS",
      "FOOTBALL TEAM",
      "RAVENS",
      "BILLS",
      "BENGALS",
      "BROWNS",
      "BRONCOS",
      "TEXANS",
      "COLTS",
      "JAGUARS",
      "CHIEFS",
      "RAIDERS",
      "CHARGERS",
      "DOLPHINS",
      "PATRIOTS",
      "STEELERS",
      "TITANS",
    ],
  },

  // NHL Hockey Teams | 7
  {
    id: 7,
    name: "Hockey",
    nameAsRule: "Your password must be the name of a hockey team in the NHL",
    failedMessage: "Sorry! There are no [PASS] in the NHL.",
    possible: [
      "HURRICANES",
      "BLUE JACKETS",
      "DEVILS",
      "ISLANDERS",
      "RANGERS",
      "FLYERS",
      "PENGUINS",
      "CAPITALS",
      "BRUINS",
      "SABRES",
      "RED WINGS",
      "PANTHERS",
      "CANADIENS",
      "SENATORS",
      "LIGHTNING",
      "MAPLE LEAFS",
      "BLACKHAWKS",
      "AVALANCHE",
      "STARS",
      "WILD",
      "PREDATORS",
      "BLUES",
      "JETS",
      "DUCKS",
      "COYOTES",
      "FLAMES",
      "OILERS",
      "KINGS",
      "SHARKS",
      "CANUCKS",
      "GOLDEN KNIGHTS",
      "KRAKEN",
    ],
  },

  // Synonyms For Blue | 8
  {
    id: 8,
    name: "Colors That Are Blue",
    nameAsRule: "Your password must be a synonym for blue",
    failedMessage: "Thesaurus.com doesn't list [PASS] as a synonym for blue.",
    possible: [
      "AZURE",
      "COBALT",
      "SAPPIRE",
      "CERULEAN",
      "NAVY",
      "ULTRAMARINE",
      "LAPIS",
      "INDIGO",
      "AQUAMARIE",
      "TURQUOISE",
      "TEAL",
      "CYAN",
      "DEPRESSED",
      "DOWN",
      "SAD",
      "SADDENED",
      "UNHAPPY",
      "MELANCHOLY",
      "MISERABLE",
      "SORROWFUL",
      "GLOOMY",
      "DEJECTED",
      "DOWNHEARTED",
      "DISHEARTENED",
      "DESPONDENT",
      "DISPIRITED",
      "LOW",
      "LOW SPIRITED",
      "HEAVY HEARTED",
      "GLUM",
      "MOROSE",
      "DISMAL",
      "DOWNCAST",
      "CAST DOWN",
      "TEARFUL",
      "DOWN",
      "FED UP",
      "INDECENT",
      "DIRTY",
      "RUDE",
      "CRUDE",
      "COARSE",
      "VULGAR",
      "BAWDY",
      "LEWD",
      "RACY",
    ],
  },

  // Salad Greens | 9
  {
    id: 9,
    name: "Salad Greens",
    nameAsRule: "Your password must be a type of salad green.",
    failedMessage: "I don't recognize [PASS] as a type of salad green",
    possible: [
      "ROMAINE",
      "ICEBERG",
      "SPINACH",
      "ARUGULA",
      "KALE",
      "BUTTERHEAD",
      "COS",
      "FRISEE",
      "ESCAROLE",
      "WATERCRESS",
      "SWISS CHARD",
      "COLLARD GREENS",
      "DANDELION GREENS",
      "ENDIVE",
      "RADICCHIO",
      "BIBB",
      "CORN SALAD",
      "LAMB'S LETTUCE",
      "TATSOI",
      "MIZUNA",
    ],
    source: "https://www.thespruceeats.com/popular-salad-greens-2216503",
  },

  // World Languages | 10
  {
    id: 10,
    name: "World Languages",
    nameAsRule: "Your password must be an Official Language",
    hint: "Primary, secondary, and tertiary languages counted",
    failedMessage: "[PASS] is not recognized as the offical language of any country.",
    possible: [
      "ABKHAZ",
      "ALBANIAN",
      "ARABIC",
      "ARMENIAN",
      "AZERBAIJANI",
      "BELARUSIAN",
      "BENGALI",
      "BOSNIAN",
      "BULGARIAN",
      "BURMESE",
      "CASTILIAN",
      "CATALAN",
      "COMORIAN",
      "CROATIAN",
      "CZECH",
      "DANISH",
      "DARI",
      "DUTCH",
      "DZONGKHA",
      "ENGLISH",
      "ESTONIAN",
      "FIJIAN",
      "FINNISH",
      "FRENCH",
      "GEORGIAN",
      "GERMAN",
      "GREEK",
      "HEBREW",
      "HINDI",
      "HUNGARIAN",
      "ICELANDIC",
      "INDONESIAN",
      "IRISH",
      "ITALIAN",
      "JAPANESE",
      "KAZAKH",
      "KHMER",
      "KIRUNDI",
      "KYRGYZ",
      "KOREAN",
      "LAO",
      "LATVIAN",
      "LITHUANIAN",
      "LUXEMBOURGISH",
      "MACEDONIAN",
      "MALAY",
      "MALTESE",
      "MAORI",
      "MANDARIN",
      "MONGOLIAN",
      "NEPALI",
      "NORWEGIAN",
      "PALAUAN",
      "PASHTO",
      "PERSIAN",
      "POLISH",
      "PORTUGUESE",
      "QUECHUA",
      "ROMANIAN",
      "RUSSIAN",
      "SERBIAN",
      "SLOVAK",
      "SLOVENE",
      "SOMALI",
      "SOTHO",
      "SPANISH",
      "SWAHILI",
      "SWAZI",
      "SWEDISH",
      "TAJIK",
      "TAMAZIGHT",
      "TETUM",
      "TIGRINYA",
      "TSWANA",
      "TURKISH",
      "UKRANIAN",
      "URDU",
      "UZBEK",
      "WOLEAIAN",
    ],
    source: "https://en.wikipedia.org/wiki/List_of_official_languages_by_country_and_territory",
  },

  // Coen Brothers Movies | 11
  {
    id: 11,
    name: "Coen Brothers Movies",
    nameAsRule: "Your password must be a movie made by one or both of the Coen Brothers.",
    failedMessage: "[PASS] is not a Coen Brothers movie.",
    possible: [
      "BLOOD SIMPLE",
      "RAISING ARIZONA",
      "MILLER'S CROSSING",
      "BARTON FINK",
      "THE HUDSUCKER PROXY",
      "FARGO",
      "THE BIG LEBOWSKI",
      "O BROTHER, WHERE ART THOU?",
      "THE MAN WHO WASN'T THERE",
      "INTOLERABLE CRUELTY",
      "THE LADYKILLERS",
      "NO COUNTRY FOR OLD MEN",
      "BURN AFTER READING",
      "A SERIOUS MAN",
      "TRUE GRIT",
      "INSIDE LLEWYN DAVIS",
      "HAIL, CAESAR!",
      "THE BALLAD OF BUSTER SCRUGGS",
      "CRIMEWAVE", // Screenplay
      "BAD SANTA", // Producer/Uncredited writer
      "GAMBIT", // Screenplay
      "UNBROKEN", // Screenplay
      "BRIDGE OF SPIES", // Screenplay
      "SUBURBICON", // Screenplay
      "THE TRAGEDY OF MACBETH", // Joel Coen's solo directorial work
      "JERRY LEE LEWIS: TROUBLE IN MIND", // Ethan Coen's solo directorial work
      "DRIVE-AWAY DOLLS", // Ethan Coen's solo directorial work
    ],
    source: "https://en.wikipedia.org/wiki/Coen_brothers_filmography",
  },

  // U.S. State Birds | 12
  {
    id: 12,
    name: "U.S. State Birds",
    nameAsRule: "Your password must be a U.S. state bird",
    failedMessage: "No US State made [PASS] their official bird.",
    source: "https://en.wikipedia.org/wiki/List_of_U.S._state_birds",
    possible: [
      "CARDINAL",
      "PTARMIGAN",
      "WREN",
      "MOCKINGBIRD",
      "QUAIL",
      "BUNTING",
      "ROBIN",
      "BLUE HEN",
      "THRASHER",
      "NENE",
      "BLUEBIRD",
      "GOLDFINCH",
      "MEADOWLARK",
      "PELICAN",
      "CHICKADEE",
      "ORIOLE",
      "LOON",
      "FINCH",
      "ROADRUNNER",
      "FLYCATCHER",
      "GROUSE",
      "RHODE ISLAND RED",
      "PHEASANT",
      "THRUSH",
      "GULL",
      "FLICKER",
    ],
  },

  // My Little Pony | 15
  {
    id: 15,
    name: "My Little Pony",
    nameAsRule: "Your password must be a My Little Pony character.",
    hint: "unicorns and humans count",
    failedMessage: "[PASS] is not a main or recurring character from the My Little Pony: Friendship Is Magic series.",
    possible: [
      "TWILIGHT SPARKLE",
      "APPLEJACK",
      "FLUTTERSHY",
      "PINKIE PIE",
      "RAINBOW DASH",
      "RARITY",
      "SPIKE",
      "PRINCESS CELESTIA",
      "PRINCESS LUNA",
      "PRINCESS CADANCE",
      "SHINING ARMOR",
      "DISCORD",
      "STARLIGHT GLIMMER",
      "SUNSET SHIMMER",
      "QUEEN CHRYSALIS",
      "KING SOMBRA",
      "LORD TIREK",
      "COZY GLOW",
      "MAUD PIE",
      "BIG MCINTOSH",
      "GRANNY SMITH",
      "THE GREAT AND POWERFUL TRIXIE",
      "DERPY HOOVES",
      "ZECORA",
      "GILDA",
      "CHEESE SANDWICH",
      "APPLE BLOOM",
      "SCOOTALOO",
      "SWEETIE BELLE",
      "DIAMOND TIARA",
      "SILVER SPOON",
      "SNIPS",
      "SNAILS",
      "PRINCESS FLURRY HEART",
      "ZEPHYR BREEZE",
      "LUNA",
      "CHRYSALIS",
      "SOARIN",
      "SPITFIRE",
      "BRAEBURN",
      "DOCTOR WHOOVES",
      "LYRA HEARTSTRINGS",
      "BON BON",
      "CHERRY JUBILEE",
      "COCO POMMEL",
      "MARE MAYOR",
      "CRANKY DOODLE DONKEY",
      "MRS CAKE",
      "MR CAKE",
      "NIGHTMARE MOON",
      "IRON WILL",
      "PRINCESS AMORE",
      "TEMPEST SHADOW",
      "GARBLE",
      "KING THORAX",
      "PRINCESS SKYSTAR",
      "SUNBURST",
      "EMBER",
      "GALLUS",
      "SILVERSTREAM",
      "SMOLDER",
      "YONA",
      "OCELLUS",
      "SANDBAR",
    ],
    source: "https://en.wikipedia.org/wiki/List_of_My_Little_Pony:_Friendship_Is_Magic_characters",
  },

  // Pokemon | 16
  {
    id: 16,
    name: "Generation I Pokemon",
    nameAsRule: "Your password must be one of the original 151 Pokemon",
    failedMessage: "Eitehr [PASS] is not a Pokemon, or it is from a later generation",
    possible: [
      "BULBASAUR",
      "IVYSAUR",
      "VENUSAUR",
      "CHARMANDER",
      "CHARMELEON",
      "CHARIZARD",
      "SQUIRTLE",
      "WARTORTLE",
      "BLASTOISE",
      "CATERPIE",
      "METAPOD",
      "BUTTERFREE",
      "WEEDLE",
      "KAKUNA",
      "BEEDRILL",
      "PIDGEY",
      "PIDGEOTTO",
      "PIDGEOT",
      "RATTATA",
      "RATICATE",
      "SPEAROW",
      "FEAROW",
      "EKANS",
      "ARBOK",
      "PIKACHU",
      "RAICHU",
      "SANDSHREW",
      "SANDSLASH",
      "NIDORAN",
      "NIDORINA",
      "NIDOQUEEN",
      "NIDORINO",
      "NIDOKING",
      "CLEFAIRY",
      "CLEFABLE",
      "VULPIX",
      "NINETALES",
      "JIGGLYPUFF",
      "WIGGLYTUFF",
      "ZUBAT",
      "GOLBAT",
      "ODDISH",
      "GLOOM",
      "VILEPLUME",
      "PARAS",
      "PARASECT",
      "VENONAT",
      "VENOMOTH",
      "DIGLETT",
      "DUGTRIO",
      "MEOWTH",
      "PERSIAN",
      "PSYDUCK",
      "GOLDUCK",
      "MANKEY",
      "PRIMEAPE",
      "GROWLITHE",
      "ARCANINE",
      "POLIWAG",
      "POLIWHIRL",
      "POLIWRATH",
      "ABRA",
      "KADABRA",
      "ALAKAZAM",
      "MACHOP",
      "MACHOKE",
      "MACHAMP",
      "BELLSPROUT",
      "WEEPINBELL",
      "VICTREEBEL",
      "TENTACOOL",
      "TENACRUEL",
      "GEODUDE",
      "GRAVELER",
      "GOLEM",
      "PONYTA",
      "RAPIDASH",
      "SLOWPOKE",
      "SLOWBRO",
      "MAGNEMITE",
      "MAGNETON",
      "FARFETCH'D",
      "DODUO",
      "DODRIO",
      "SEEL",
      "DEWGONG",
      "GRIMER",
      "MUK",
      "SHELLDER",
      "CLOYSTER",
      "GASTLY",
      "HAUNTER",
      "GENGAR",
      "ONIX",
      "DROWSEE",
      "HYPNO",
      "KRABBY",
      "KINGLER",
      "VOLTORB",
      "ELECTRODE",
      "EXEGGCUTE",
      "EXEGGUTOR",
      "CUBONE",
      "MAROWAK",
      "HITMONLEE",
      "HITMONCHAN",
      "LICKITUNG",
      "KOFFING",
      "WEEZING",
      "RHYHORN",
      "RHYDON",
      "CHANSEY",
      "TANGELA",
      "KANGASKHAN",
      "HORSEA",
      "SEADRA",
      "GOLDEEN",
      "SEAKING",
      "STARYU",
      "STARMIE",
      "MR. MIME",
      "SCYTHER",
      "JYNX",
      "ELECTABUZZ",
      "MAGMAR",
      "PINSIR",
      "TAUROS",
      "MAGIKARP",
      "GYARADOS",
      "LAPRAS",
      "DITTO",
      "EEVEE",
      "VAPOREON",
      "JOLTEON",
      "FLAREON",
      "PORYGON",
      "OMANYTE",
      "OMASTAR",
      "KABUTO",
      "KABUTOPS",
      "AERODACTYL",
      "SNORLAX",
      "ARTICUNO",
      "ZAPDOS",
      "MOLTRES",
      "DRATINI",
      "DRAGONAIR",
      "DRAGONITE",
      "MEWTWO",
      "MEW",
    ],
  },

  // Root Vegetables | 17
  {
    id: 17,
    name: "Root Vegetables",
    nameAsRule: "Your password must be a root vegetable.",
    failedMessage: "I don't recognize [PASS] as a root vegetable.",
    possible: [
      "CARROT",
      "POTATO",
      "SWEET POTATO",
      "BEET",
      "RADISH",
      "TURNIP",
      "PARSNIP",
      "ONION",
      "GARLIC",
      "GINGER",
      "TURMERIC",
      "YAM",
      "CELERIAC",
      "RUTABAGA",
      "HORSERADISH",
      "CASSAVA",
      "JERUSALEM ARTICHOKE",
      "DAIKON",
      "JICAMA",
      "TARO",
      "FENNEL",
      "WASABI",
      "BURDOCK",
      "ARRACACHA",
      "ARROWROOT",
      "GALANGAL",
      "KONJAC",
    ],
    source: "https://www.foodandwine.com/vegetables/root-vegetables-list",
  },

  // Olympic Sports | 18
  {
    id: 18,
    name: "Olympic Sports",
    nameAsRule: "Your password must be an event currently played during the Olympics.",
    failedMessage: "[PASS] is not a Summer or Winter event listed on the Olympics website.",
    possible: [
      "ARCHERY",
      "BADMINTON",
      "BASEBALL",
      "SOFTBALL",
      "VOLLEYBALL",
      // ALSO
      // "BEACH VOLLEYBALL",
      "BIATHLON",
      "BOBSLED",
      // ALSO
      // "BOBSLEIGH",
      "BOXING",
      "BREAKING",
      "BREAK DANCING",
      "BASKETBALL",
      "CANOE",
      // ALSO
      // "CANOE SLALOM",
      // "CANOE SPRINT",
      "CURLING",
      "CYCLING",
      // ALSO
      // "CYCLING BMX",
      // "CYCLING MOUNTAIN BIKE",
      // "CYCLING ROAD",
      // "CYCLING TRACK",
      "DIVING",
      "EQUESTRIAN",
      "DRESSAGE",
      "FENCING",
      "FOOTBALL",
      "SOCCER",
      "GOLF",
      "GYMNASITCS",
      // ALSO
      // "GYMNASITCS ARTISTIC",
      // "GYMNASTICS RHYTHMIC",
      // "RHYTHM GYMNASTICS"
      "HANDBALL",
      "HOCKEY",
      "JUDO",
      "KARATE",
      "PENTATHLON",
      "ROWING",
      "RUGBY",
      "SAILING",
      "SHOOTING",
      "SKATEBOARDING",
      "CLIMBING",
      "SURFING",
      "SWIMMING",
      // ALSO
      // "MARATHON SWIMMING",
      // "ARTISTIC SWIMMING",
      "TABLE TENNIS",
      // ALSO
      // "PING PONG",
      "TAEKWONDO",
      "TENNIS",
      "TRAMPOLINE",
      "TRIATHLON",
      "VOLLEYBALL",
      "WATER POLO",
      "WEIGHTLIFTING",
      "WRESTLING",
      // ALSO
      // "WRESTLING FREESTYLE",
      // "WRESTLING GRECO-ROMAN",
      "SKIING",
      // ALSO
      // "ALPINE SKIING",
      // "CROSS COUNTRY SKIING",
      // "FREESTYLE SKIING",
      "FIGURE SKATING",
      "ICE HOCKEY",
      "LUGE",
      "NORDIC COMBINED",
      "SHORT TRACK",
      "SKELETON",
      "SKI JUMPING",
      "SNOWBOARD",
      "SPEED SKATING",
    ],
  },

  // Classic Cocktails | 19
  {
    id: 19,
    name: "Classic Cocktails",
    nameAsRule: "Your password must be a classic cocktail.",
    failedMessage: "The International Bartenders Association does not recognize [PASS] as a classic cocktail.",
    possible: [
      "OLD FASHIONED",
      "MARGARITA",
      "COSMOPOLITAN",
      "NEGRONI",
      "MOSCOW MULE",
      "MARTINI",
      "MOJITO",
      "WHISKEY SOUR",
      "FRENCH 75",
      "MANHATTAN",
      "APEROL SPRITZ",
      "GIMLET",
      "SAZERAC",
      "PIMM'S CUP",
      "MIMOSA",
      "PALOMA",
      "SIDECAR",
      "MINT JULEP",
      "DAIQUIRI",
      "DARK AND STORMY",
      "MARTINEZ",
      "IRISH COFFEE",
      "LONG ISLAND ICED TEA",
      "BRANDY ALEXANDER",
      "OLD CUBAN",
      "GIN FIZZ",
      "VESPER",
      "WHITE LADY",
      "AVIATION",
      "TOM COLLINS",
      "PINA COLADA",
      "LAST WORD",
      "PISCO SOUR",
      "BEES KNEES",
      "BRAMBLE",
      "AMERICANO",
      "CORPSE REVIVER",
      "MAI TAI",
      "AMARETTO SOUR",
      "BOULEVARDIER",
      "BLOODY MARY",
      "WHITE RUSSIAN",
      "PAINKILLER",
      "GIN RICKEY",
      "MUDSLIDE",
      "VIEUX CARRE",
      "RUM RUNNER",
      "CAIPIRINHA",
      "HURRICANE",
      "TEQUILA SUNRISE",
      "KAMIKAZE",
      "HOT TODDY",
      "ROB ROY",
      "MARY PICKFORD",
    ],
    source: "https://en.wikipedia.org/wiki/List_of_IBA_official_cocktails",
  },

  // Simpsons Characters | 20
  {
    id: 20,
    name: "Simpsons Characters",
    nameAsRule: "Your password must be the first name of a recurring Simpsons character who DOESN'T have the last name of Simpson",
    hint: "Fat Tony's first name isn't Tony.",
    failedMessage: "[PASS] is not a Simpsons character. Or is. It's 32+ seasons.",
    possible: [
      "ABE",
      "AGNES",
      "AKIRA",
      "APU",
      "ARNIE",
      "ARTIE",
      "BARNEY",
      "BARRY", // <-- DUFFMAN
      "BOB",
      "BRANDINE",
      "CARL",
      "CHARLES", // <-- MONTY BURNS
      "CLANCY",
      "JEFF", // <- COMIC BOOK GUY
      "COOKIE",
      "DEWEY",
      "DORIS", // <-- LUNCHLADY DORIS
      "DREDERICK",
      "EDDIE",
      "EDNA",
      "ELIZABETH", // <-- MISS HOOVER
      "FRANKIE", // <-- FRANKIE THE SQUEALER
      "GARY", // <-- SUPERNINTENDO CHALMERS
      "GIL",
      "HANS",
      "HELEN",
      "JIMBO",
      "JOE", // <-- DIAMOND JOE QUIMBY
      "JOHNNY", // <-- JOHNNY TIGHTLIPS
      "JOHN", // <-- PROFESSOR FRINK
      "JULIUS",
      "KEARNEY",
      "KENT",
      "KIRK",
      "KRUSTY",
      "LENNY",
      "LINDSEY",
      "LIONEL",
      "LOU",
      "LUANN",
      "LUIGI",
      "MEL",
      "MILHOUSE",
      "MANJULA",
      "MARION", // <-- THERE'S FAT TONY!
      "MARVIN", // <-- MARVIN MONROE
      "MARTIN",
      "MOE",
      "MURPHY", // <- BLEEDING GUMS MURPHY
      "NED",
      "NICK", // <-- DR. NICK
      "OTTO",
      "PATTY",
      "RAINIER",
      "RALPH",
      "ROD",
      "TODD",
      "TROY",
      "SELMA",
      "SEYMOUR",
      "STU", // <- DISCO STU
      "WAYLON", // <-- SMITHERS
      "WILLIE",
    ],
    source: "https://en.wikipedia.org/wiki/List_of_recurring_The_Simpsons_characters",
  },

  // Human Organs | 22
  {
    id: 22,
    name: "Human Organs",
    nameAsRule: "Your password must be an organ in the human body.",
    failedMessage: "[PASS] is not an organ in the human body.",
    possible: [
      "ADRENAL GLANDS",
      "HEART",
      "PANCREAS",
      "THYMUS GLAND",
      "TESTES",
      "ANUS",
      "HYPOTHALAMUS",
      "PINEAL GLAND",
      "THYROID",
      "EPIDIDYMIS",
      "APPENDIX",
      "JOINTS",
      "PARATHYROID GLANDS",
      "TRACHEA",
      "VAS DEFERENS",
      "BLADDER",
      "KIDNEYS",
      "PHARYNX",
      "TONGUE",
      "SEMINAL VESICLES",
      "BONES",
      "LARGE INTESTINE",
      "PITUITARY GLAND",
      "URETERS",
      "BULBOURETHRAL GLANDS",
      "BONE MARROW",
      "LARYNX",
      "PROSTATE",
      "URETHRA",
      "PENIS",
      "BRAIN",
      "LIVER",
      "RECTUM",
      "UTERUS",
      "SCROTUM",
      "BRONCHI",
      "LUNGS",
      "SALIVARY GLANDS",
      "NERVES",
      "SUBCUTANEOUS TISSUE",
      "DIAPHRAGM",
      "LYMPH NODES",
      "SKELETAL MUSCLES",
      "LIGAMENTS",
      "FORAMEN OVALE",
      "EARS",
      "MAMMARY GLANDS",
      "SKIN",
      "TENDONS",
      "ARTERIES",
      "OESOPHAGUS",
      "MESENTERY",
      "SMALL INTESTINE",
      "CLITORIS",
      "VEINS",
      "EYES",
      "MOUTH",
      "SPINAL CORD",
      "VAGINA",
      "CAPILLARIES",
      "FALLOPIAN TUBES",
      "NASAL CAVITY",
      "SPLEEN",
      "VULVA",
      "LYMPHATIC VESSEL",
      "GALLBLADDER",
      "NOSE",
      "STOMACH",
      "CEREBELLUM",
      "TONSILS",
      "OLFACTORY EPITHELIUM",
      "OVARY",
      "TEETH",
      "PLACENTA",
      "INTERSTITIUM",
    ],
    source: "https://byjus.com/biology/what-are-the-78-organs-in-the-human-body/",
  },

  // One Hit Wonders (1990s) | 24
  {
    id: 24,
    name: "One-Hit Wonders (1990s)",
    nameAsRule: "Your password must be the name of a one-hit wonder artist from the 1990s.",
    failedMessage: "[PASS] is not considered a 1990s one-hit wonder, according to Wikipedia.",
    possible: [
      "JANE CHILD",
      "SINEAD O'CONNOR",
      "MELLOW MAN ACE",
      "VANILLA ICE",
      "ELECTRONIC",
      "CANDYMAN",
      "DEEE-LITE",
      "EMF",
      "GERARDO",
      "DNA",
      "TOM COCHRANE",
      "RIGHT SAID FRED",
      "SIR MIX-A-LOT",
      "HOUSE OF PAIN",
      "POSITIVE K",
      "PAPERBOY",
      "DUICE",
      "95 SOUTH",
      "TAG TEAM",
      "ROBIN S.",
      "BLIND MELON",
      "HADDAWAY",
      "THE PROCLAIMERS",
      "4 NON BLONDES",
      "THE BREEDERS",
      "CORONA",
      "AHMAD",
      "INI KAMOZE",
      "TOADIES",
      "EVERYTHING BUT THE GIRL",
      "DEEP BLUE SOMETHING",
      "SKEE-LO",
      "LOS DEL RIO",
      "DIONNE FARRIS",
      "JOAN OSBORNE",
      "NONCHALANT",
      "DISHWALLA",
      "SPACEHOG",
      "CRUCIAL CONFLICT",
      "PRIMITIVE RADIO GODS",
      "THE CARDIGANS",
      "DUNCAN SHEIK",
      "THE VERVE PIPE",
      "OMC",
      "WHITE TOWN",
      "TRACEY LEE",
      "AQUA",
      "FIONA APPLE",
      "MEREDITH BROOKS",
      "SHAWN COLVIN",
      "HANSON",
      "LORD TARIQ AND PETER GUNZ",
      "CHUMBAWAMBA",
      "MARCY PLAYGROUND",
      "THE VERVE",
      "HARVEY DANGER",
      "SEMISONIC",
      "NATALIE IMBRUGLIA",
      "EAGLE-EYE CHERRY",
      "LIT",
      "LOU BEGA",
      "NEW RADICALS",
      "SPORTY THIEVZ",
      "TAL BACHMAN",
      "LEN",
      "MACY GRAY",
      "BBMAK",
    ],
    source: "https://en.wikipedia.org/wiki/List_of_one-hit_wonders_in_the_United_States#1990s",
  },

  // Board Games | 28
  {
    id: 28,
    name: "Board Games",
    nameAsRule: "Your password must be a best-selling board game",
    failedMessage: "Sorry, [PASS] is not one of the 39 best selling board games of all time.",
    possible: [
      "CHESS",
      "CHECKERS",
      "MONOPOLY",
      "SCRABBLE",
      "CLUE",
      "BATTLESHIP",
      "TRIVIAL PURSUIT",
      "BACKGAMMON",
      "CANDY LAND",
      "RUMMIKUB",
      "THE GAME OF LIFE",
      "OTHELLO",
      "PICTIONARY",
      "CATAN",
      "RISK",
      "STRATEGO",
      "MANCALA",
      "CONNECT FOUR",
      "CRANIUM",
      "JENGA",
      "CHUTES AND LADDERS",
      "TROUBLE",
      "SORRY",
      "YAHTZEE",
      "HI HO CHERRY-O",
      "GUESS WHO",
      "HUNGRY HUNGRY HIPPOS",
      "DON'T BREAK THE ICE",
      "OPERATION",
      "BOGGLE",
      "DOMINOES",
      "PARCHEESI",
      "TABOO",
      "TWISTER",
      "BALDERDASH",
      "SCATTERGORIES",
      "SETTLERS OF CATAN",
      "GAME OF LIFE",
      "CLUEDO",
    ],
    source: "https://www.fun.com/best-selling-board-games-all-time.html",
  },

  // Gemstones | 30
  {
    id: 30,
    name: "Gemstones",
    nameAsRule: "Your password must be a gemtone used in jewelry",
    failedMessage: "[PASS] isn't a precious gemstone, according to The Antique Jewelry Company",
    possible: [
      "AGATE",
      "AMAZONITE",
      "AMBER",
      "AMETHYST",
      "AQUAMARINE",
      "BLOODSTONE",
      "CARNELIAN",
      "CHALCEDONY",
      "CHRYSOPHRASE",
      "CHRYSOBERYL",
      "CITRINE",
      "CORAL",
      "DIAMOND",
      "EMERALD",
      "GARNET",
      "JADE",
      "JASPER",
      "KUNZITE",
      "LABRADORITE",
      "LAPIS LAZULI",
      "MALACHITE",
      "MOONSTONE",
      "ONYX",
      "OPAL",
      "PEARL",
      "PERIDOT",
      "QUARTZ",
      "ROSE QUARTZ",
      "RUBY",
      "SAPPHIRE",
      "SMOKY QUARTZ",
      "SPINEL",
      "TANZANITE",
      "TOPAZ",
      "TOURMALINE",
      "TURQUOISE",
      "ZIRCON",
    ],
    source: "https://www.antiquejewellerycompany.com/gemstone-guide/",
  },

  // Disney Movies | 32
  {
    id: 32,
    name: "Disney Movies",
    nameAsRule: "Your password must be a Disney or Pixar animated film (excluding sequels).",
    failedMessage: "[PASS] isn't an animated film by Disney or Pixar, please try again.",
    possible: [
      "SNOW WHITE AND THE SEVEN DWARFS",
      "PINOCCHIO",
      "FANTASIA",
      "DUMBO",
      "BAMBI",
      "ADVENTURES OF ICHABOD AND MR TOAD",
      "CINDERELLA",
      "ALICE IN WONDERLAND",
      "PETER PAN",
      "LADY AND THE TRAMP",
      "SLEEPING BEAUTY",
      "101 DALMATIONS",
      // ALSO
      // "ONE HUNDRED AND ONE DALMATIONS",
      "THE SWORD IN THE STONE",
      "THE JUNGLE BOOK",
      "THE ARISTOCATS",
      "ROBIN HOOD",
      "THE MANY ADVENTURES OF WINNIE THE POOH",
      // ALSO
      // "WINNIE THE POOH",
      "THE RESCUERS",
      "THE FOX AND THE HOUND",
      "THE BLACK CAULDRON",
      "THE GREAT MOUSE DETECTIVE",
      "OLIVER & COMPANY",
      // ALSO
      // "OLIVER AND COMPANY"
      "THE LITTLE MERMAID",
      "DUCKTALES THE MOVIE",
      "THE RESCUERS DOWN UNDER",
      "BEAUTY AND THE BEAST",
      "ALADDIN",
      "THE LION KING",
      "A GOOFY MOVIE",
      "POCAHONTAS",
      "TOY STORY",
      "JAMES AND THE GIANT PEACH",
      "THE HUNCHBACK OF NOTRE DAME",
      "HERCULES",
      "MULAN",
      "A BUG'S LIFE",
      "DOUG'S 1ST MOVIE",
      "TARZAN",
      "THE TIGGER MOVIE",
      "DINOSAUR",
      "THE EMPEROR'S NEW GROOVE",
      "RECESS: SCHOOL'S OUT",
      "ATLANTIS: THE LOST EMPIRE",
      // ALSO
      // "ATLANTIS"
      "MONSTERS, INC.",
      "RETURN TO NEVER LAND",
      "LILO & STITCH",
      // ALSO
      // "LILO AND STITCH"
      "TREASURE PLANET",
      "FINDING NEMO",
      "BROTHER BEAR",
      "TEACHER'S PET",
      "HOME ON THE RANGE",
      "THE INCREDIBLES",
      "CHICKEN LITTLE",
      "CARS",
      "MEET THE ROBINSONS",
      "RATATOUILLE",
      "WALL-E",
      "BOLT",
      "UP",
      "THE PRINCESS AND THE FROG",
      "TANGLED",
      "MARS NEEDS MOMS",
      "BRAVE",
      "FRANKENWEENIE",
      "WRECK-IT RALPH",
      "FROZEN",
      "BIG HERO 6",
      "INSIDE OUT",
      "THE GOOD DINOSAUR",
      "ZOOTOPIA",
      "MOANA",
      "COCO",
      "SOUL",
    ],
  },

  // Cheese | 34
  {
    id: 34,
    name: "Cheese",
    nameAsRule: "Your password must be a type of cheese.",
    failedMessage: "[PASS]? Must be a specialty where you're from. Try something a little less fancy.",
    possible: [
      "AMERICAN",
      "ASIAGO",
      "BLUE CHEESE",
      "BOCCONCINI",
      "BRIE",
      "BURRATA",
      "CAMEMBERT",
      "CHEDDAR",
      "CHEESE CURDS",
      "COLBY",
      "COLBY-JACK",
      "COLD-PACK",
      "CHEEZ WIZ",
      "COTTAGE CHEESE",
      "CREAM CHEESE",
      "EMMENTAL",
      "FARMER'S",
      "FETA",
      "MOZZARELLA",
      "BUFFALO MOZZARELLA",
      "GORGONZOLA",
      "GOUDA",
      "GRUYERE",
      "HALLOUMI",
      "HAVARTI",
      "JARLSBERG",
      "LIMBURGER",
      "MASCARPONE",
      "MONTEREY JACK",
      "MUENSTER",
      "NEUFCHATEL",
      "PANEER",
      "PARMESAN",
      "PEPPER JACK",
      "PROVOLONE",
      "RICOTTA",
      "ROMANO",
      "STRING",
      "SWISS",
      "ROQUEFORT",
      "COTIJA",
      "TALEGGIO",
      "MANCHEGO",
      "GOAT CHEESE",
      "PARMIGIANO-REGGIANO",
      "PECORINO ROMANO",
      "STILTON",
      "WENSLEYDALE",
      "CHEVRE",
      "FONTINA",
      "EMMENTALER",
      "EDAM",
      "COMTE",
      "RACLETTE",
    ],
  },

  // Muppet SHow | 38
  {
    id: 38,
    name: "The Muppet Show",
    nameAsRule: "Your password must be a Muppet.",
    hint: "Specifically from The Muppet Show (1976)",
    failedMessage: "[PASS] isn't a Muppet. Try again.",
    possible: [
      "KERMIT",
      "MISS PIGGY",
      "FOZZIE BEAR",
      "GONZO",
      "ROWLF",
      "SCOOTER",
      "ANIMAL",
      "PEPE",
      "RIZZO",
      "WALTER",
      "DR. TEETH",
      "DR. BUNSEN HONEYDEW",
      "BEAKER",
      "SAM EAGLE",
      "STATLER",
      "WALDORF",
      "SWEDISH CHEF",
      "CAMILLA",
      "BOBO",
      "UNCLE DEADLY",
      "CLIFFORD",
      "80S ROBOT",
      "BEAN BUNNY",
      "BEAUREGARD",
      "CONSTANTINE",
      "CRAZY HARRY",
      "JOHNNY FIAMA",
      "SAL MINELLA",
      "LEW ZEALAND",
      "LINK HOGTHROB",
      "MARVIN SUGGS",
      "NEWSMAN",
      "POPS",
      "ROBIN",
      "SWEETUMS",
      "YOLANDA",
      "BIG MEAN CARL",
      "CHIP",
      "DENISE",
    ],
    source: "https://en.wikipedia.org/wiki/List_of_Muppets",
  },

  // Looney Tunes | 40
  {
    id: 40,
    name: "Looney Tunes",
    nameAsRule: "Your password must be the full name of a Looney Tunes character.",
    hint: "First and last names required in some (but not all) cases.",
    failedMessage: "[PASS] must have gotten lost on their way to Albuquerque. Try again.",
    possible: [
      "BABBI AND CATSTELLO",
      "BARNYARD DAWG",
      "BEANS",
      "BOSKO",
      "BUDDY",
      "BUGS BUNNY",
      "HONEY BUNNY",
      "BEAKY BUZZARD",
      "CLAUDE CAT",
      "CHARLIE DOG",
      "CLYDE",
      "COLONEL SHUFFLE",
      "CONRAD",
      "COOL CAT",
      "DAFFY DUCK",
      "EGGHEAD JR.",
      "ELMER FUDD",
      "FOGHORN LEGHORN",
      "FOXY",
      "MICHIGAN J. FROG",
      "GABBY GOAT",
      "SPEEDY GONZALES",
      "GOOFY GOPHERS",
      "GOOPY GEER",
      "GOSSAMER",
      "GRANNY",
      "HENERY HAWK",
      "HECTOR THE BULLDOG",
      "HIPPETY HOPPER",
      "HUBIE AND BERTIE",
      "HUGO THE ABOMINABLE SNOWMAN",
      "INKI",
      "MARC ANTONY",
      "MARVIN THE MARTIAN",
      "MELISSA DUCK",
      "MERLIN THE MAGIC MOUSE",
      "MISS PRISSY",
      "NASTY CANASTA",
      "PENELOPE PUSSYCAT",
      "PEPE LE PEW",
      "PETUNIA PIG",
      "PIGGY",
      "PORKY PIG",
      "PLAYBOY PENGUIN",
      "PRIVATE SNAFU",
      "QUICK BROWN FOX",
      "RAPID RABBIT",
      "RALPH WOLF",
      "SAM SHEEPDOG",
      "ROCKY",
      "MUGSY",
      "SLOWPOKE RODRIGUEZ",
      "SNIFFLES",
      "SPIKE THE BULLDOG",
      "CHESTER THE TERRIER",
      "SYLVESTER JR.",
      "SYLVESTER THE CAT",
      "TASMANIAN DEVIL",
      "THE THREE BEARS",
      "CECIL TURTLE",
      "TWEETY",
      "WILE E. COYOTE",
      "ROAD RUNNER",
      "WILLOUGHBY",
      "WITCH HAZEL",
      "YOSEMITE SAM",
    ],
    source: "https://en.wikipedia.org/wiki/Category:Looney_Tunes_characters",
  },

  // Scavengers | 43
  {
    id: 43,
    name: "Scavenger Animals",
    nameAsRule: "Your password must be an animal that is a scavenger.",
    hint: "(vertebrate or invertebrate)",
    failedMessage: "[PASS] isn't considered a scavenger, try again.",
    possible: [
      "VULTURE",
      "HYENA",
      "JACKAL",
      "COYOTE",
      "WOLF",
      "LION",
      "LEOPARD",
      "TASMANIAN DEVIL",
      "BEAR",
      "RACCOON",
      "OPOSSUM",
      "HEDGEHOG",
      "WOLVERINE",
      "CROW",
      "RAVEN",
      "MAGPIE",
      "SEAGULL",
      "BALD EAGLE",
      "MARABOU STORK",
      "CRAB",
      "LOBSTER",
      "PRAWN",
      "EEL",
      "SHARK",
      "PIRANHA",
      "BLOWFLY",
      "MAGGOT",
      "BEETLE",
      "TERMITE",
      "ANT",
      "CENTIPEDE",
      "SNAIL",
      "SEA SLUG",
      "EARTHWORM",
      "WASP",
      "YELLOWJACKET",
      "MONITOR LIZARD",
      "FOX",
      "MICE",
      "RAT",
      "BUZZARD",
    ],
    source: "https://en.wikipedia.org/wiki/Scavenger",
  },

  // Smash Bros. | 44
  {
    id: 44,
    name: "Smash Bros.",
    nameAsRule: "Your password must be a playable character in Super Smash Bros. Ultimate",
    hint: "Not including DLC",
    failedMessage: "[PASS] isn't a playable character in Super Smash Bros. Ultimate",
    possible: [
      "BAYONETTA",
      "BOWSER",
      "BOWSER JR.",
      "CAPTAIN FALCON",
      "CHARIZARD",
      "CHROM",
      "CLOUD",
      "CORRIN",
      "DAISY",
      "DARK PIT",
      "DARK SAMUS",
      "DIDDY KONG",
      "DONKEY KONG",
      "DR. MARIO",
      "DUCK HUNT",
      "FALCO",
      "FOX",
      "GANONDORF",
      "GRENINJA",
      "ICE CLIMBERS",
      "IKE",
      "INCINEROAR",
      "INKLING",
      "ISABELLE",
      "IVYSAUR",
      "JIGGLYPUFF",
      "KEN",
      "KING DEDEDE",
      "KING K. ROOL",
      "KIRBY",
      "LINK",
      "LITTLE MAC",
      "LUCARIO",
      "LUCAS",
      "LUCINA",
      "LUIGI",
      "MARIO",
      "MARTH",
      "MEGA MAN",
      "META KNIGHT",
      "MEWTWO",
      "MII BRAWLER",
      "MII SWORDFIGHTER",
      "MII GUNNER",
      "MR. GAME & WATCH",
      "NESS",
      "OLIMAR",
      "PAC-MAN",
      "PALUTENA",
      "PEACH",
      "PICHU",
      "PIKACHU",
      "PIT",
      "RICHTER",
      "RIDLEY",
      "R.O.B.",
      "ROBIN",
      "ROSALINA & LUMA",
      "ROY",
      "RYU",
      "SAMUS",
      "SHEIK",
      "SHULK",
      "SIMON",
      "SNAKE",
      "SONIC",
      "SQUIRTLE",
      "TOON LINK",
      "VILLAGER",
      "WARIO",
      "WII FIT TRAINER",
      "WOLF",
      "YOSHI",
      "YOUNG LINK",
      "ZELDA",
      "ZERO SUIT SAMUS",
    ],
  },

  // World Currencies | 45
  {
    id: 45,
    name: "World Currencuies",
    nameAsRule: "Your password must be a form of currency",
    hint: "Currency name only",
    failedMessage: "[PASS] is not a form of currency traded on the foreign exchange market.",
    possible: [
      "DOLLAR",
      "EURO",
      "YEN",
      "POUND",
      "FRANC",
      "KRONA",
      "WON",
      "PESO",
      "RUPEE",
      "RUBLE",
      "RAND",
      "LIRA",
      "REAL",
      "ZLOTY",
      "BAHT",
      "RUPIAH",
      "FORINT",
      "KORUNA",
      "SHEKEL",
      "DIRHAM",
      "RIYAL",
      "RINGGIT",
      "LEU",
      "TAKA",
      "DRAM",
      "FLORIN",
      "CEDI",
      "COLON",
      "DENAR",
      "NAIRA",
      "OUGUIYA",
      "KWACHA",
      "METICAL",
      "SOMONI",
      "SHILLING",
      "LEMPIRA",
      "SOL",
      "GUARANI",
      "QUETZAL",
      "DOBRA",
      "BOLIVIANO",
      "BALBOA",
      "PATACA",
      "KYAT",
      "PULA",
      "RIEL",
      "TUGRIK",
      "MANAT",
      "DINAR",
      "LEK",
      "KIP",
      "TAKA",
      "CORDOBA",
      "VOT",
      "LARI",
      "FUNT",
      "SOU",
      "BIRR",
      "BITCOIN",
      "ETHER",
    ],
    source: "https://en.wikipedia.org/wiki/List_of_currencies_in_circulation",
  },

  // Norse Gods | 47
  {
    id: 47,
    name: "Norse Gods",
    nameAsRule: "Your password must be a Norse God",
    failedMessage: "[PASS] does not stand among the gods of Asgard or the Vanir.",
    possible: [
      "AEGIR",
      "BALDER",
      "BOLVERK",
      "BOR",
      "BRAGI",
      "BURI",
      "DAY",
      "EARTH",
      "EIR",
      "FJORGYN",
      "FORSETI",
      "FREYJA",
      "FREYR",
      "FRIGGA",
      "FULLA",
      "GANGNRAD",
      "GEFION",
      "GRIMNIR",
      "GULLVEIG",
      "HARBARD",
      "HEIMDALL",
      "HEL",
      "HERMOD",
      "HOD",
      "HONIR",
      "IDUN",
      "KVASIR",
      "LOFN",
      "LOKI",
      "MAGNI",
      "MIMIR",
      "MODGUD",
      "MODI",
      "MOON",
      "NANNA",
      "NARVI",
      "NIGHT",
      "NJORD",
      "URD",
      "SKULD",
      "VERANDI",
      "OD",
      "ODIN",
      "RAN",
      "RIG",
      "RIND",
      "SAGA",
      "SIF",
      "SIGYN",
      "SJOFN",
      "SKADI",
      "SUN",
      "SYN",
      "THOR",
      "THRUD",
      "TYR",
      "ULL",
      "VALI",
      "VAR",
      "VE",
      "VIDAR",
      "VILI",
      "VOR",
    ],
    source: "https://thenorsegods.com/norse-gods/",
  },

  // Major Airlines | 48
  {
    id: 48,
    name: "Major Airlines",
    nameAsRule: "Your password must be a major airline",
    failedMessage: "[PASS] is not among the world's major airlines.",
    hint: "Top airline by revenue.",
    possible: [
      "AEROMEXICO",
      "AIRCANADA",
      "AIRFRANCE",
      "AIRINDIA",
      "ALASKA",
      "ALLNIPPON",
      "AMERICAN",
      "AVIANCA",
      "BRITISHAIRWAYS",
      "CATHAYPACIFIC",
      "CHINA",
      "COPA",
      "DELTA",
      "EMIRATES",
      "ETIHAD",
      "FINNAIR",
      "FRONTIER",
      "HAWAIIAN",
      "INDIGO",
      "JAPAN",
      "JETBLUE",
      "KOREANAIR",
      "LATAM",
      "LUFTHANSA",
      "QANTAS",
      "QATAR",
      "RYANAIR",
      "SAS",
      "SINGAPORE",
      "SOUTHWEST",
      "SPIRIT",
      "SWISS",
      "THAI",
      "TURKISH",
      "UNITED",
      "VIRGINATLANTIC",
    ],
    source: "https://aviationa2z.com/index.php/2025/01/02/largest-airlines-in-world-by-revenue/",
  },

  // Common Trees | 49
  {
    id: 49,
    name: "Common Trees",
    nameAsRule: "Your password must be a common tree",
    failedMessage: "[PASS] has not put down roots among the most common trees.",
    hint: "A comprehensive list of common trees.",
    possible: [
      "ACACIA",
      "ASPEN",
      "ASH",
      "BALSAM",
      "BAOBAB",
      "BEECH",
      "BIRCH",
      "CEDAR",
      "CHERRY",
      "CHESTNUT",
      "CYPRESS",
      "DOUGLASFIR",
      "ELM",
      "EUCALYPTUS",
      "FIG",
      "GINKGO",
      "HAWTHORN",
      "HEMLOCK",
      "HICKORY",
      "HONEYLOCUST",
      "IRONWOOD",
      "JUNIPER",
      "LINDEN",
      "MAGNOLIA",
      "MAPLE",
      "OAK",
      "PINE",
      "POPLAR",
      "REDWOOD",
      "SPRUCE",
      "SYCAMORE",
      "WALNUT",
      "WILLOW",
      "YEW",
    ],
    source: "https://www.conservation.org/stories/unusual-trees-of-the-world",
  },

  // Culinary Fruits | 52
  {
    id: 52,
    name: "Culinary Fruits",
    nameAsRule: "Your password must be a culinary fruit",
    failedMessage: "[PASS] is not a culinary fruit.",
    hint: "Fruits eaten as food.",
    possible: [
      "ABIU",
      "ACAI",
      "ACEROLA",
      "ACKEE",
      "AMLA",
      "APPLE",
      "APRICOT",
      "AVOCADO",
      "BANANA",
      "BEARBERRY",
      "BILBERRY",
      "BLACKBERRY",
      "BLACKCURRANT",
      "BLUEBERRY",
      "BOYSENBERRY",
      "BREADFRUIT",
      "CHERRY",
      "CLOUDBERRY",
      "COCONUT",
      "CRANBERRY",
      "CURRANT",
      "DATE",
      "DEWBERRY",
      "ELDERBERRY",
      "FEIJOA",
      "FIG",
      "GOJI",
      "GOOSEBERRY",
      "GRAPE",
      "GRAPEFRUIT",
      "GUAVA",
      "HUCKLEBERRY",
      "JACKFRUIT",
      "JAMBUL",
      "KIWI",
      "KUMQUAT",
      "LEMON",
      "LIME",
      "LOGANBERRY",
      "LOQUAT",
      "LYCHEE",
      "MANDARIN",
      "MANGO",
      "MANGOSTEEN",
      "MELON",
      "MULBERRY",
      "NECTARINE",
      "ORANGE",
      "PAPAYA",
      "PASSION FRUIT",
      "PEACH",
      "PEAR",
      "PERSIMMON",
      "PINEAPPLE",
      "PLUM",
      "POMEGRANATE",
      "PRICKLY PEAR",
      "QUINCE",
      "RAMBUTAN",
      "RASPBERRY",
      "REDCURRANT",
      "RHUBARB",
      "ROSE HIP",
      "STRAWBERRY",
      "TANGERINE",
      "TOMATO",
      "WATERMELON",
    ],
    source: "https://en.wikipedia.org/wiki/List_of_culinary_fruits",
  },

  // Medieval Weapons | 54
  {
    id: 54,
    name: "Medieval Weapons",
    nameAsRule: "Your password must be a medieval weapon",
    failedMessage: "[PASS] is not a medieval weapon.",
    hint: "Weapons used during the Middle Ages (excludes anything with 'sword' in the name).",
    possible: [
      "ARBALEST",
      "ARQUEBUS",
      "BALLISTA",
      "BARDICHE",
      "BATTLE AXE",
      "BILL",
      "BLUNDERBUSS",
      "BOW",
      "CANNON",
      "CATAPULT",
      "CROSSBOW",
      "CULVERIN",
      "DAGGER",
      "DANE AXE",
      "ESTOC",
      "FALCHION",
      "FLAIL",
      "GLAIVE",
      "HALBERD",
      "HARPOON",
      "JAVELIN",
      "KATANA",
      "LANCE",
      "LONGBOW",
      "MACE",
      "MANGONEL",
      "MESSER",
      "MORNING STAR",
      "NAGINATA",
      "ONAGER",
      "PIKE",
      "POLEAXE",
      "QUARTERSTAFF",
      "RAPIER",
      "SABRE",
      "SCIMITAR",
      "SLING",
      "SPEAR",
      "TREBUCHET",
      "TRIDENT",
      "WAR HAMMER",
      "WAR SCYTHE",
    ],
    source: "https://en.wikipedia.org/wiki/List_of_medieval_weapons",
  },

  // Hanna-Barbera | 62
  {
    id: 62,
    name: "Hanna-Barbera",
    nameAsRule: "Your password must be a cartoon series from Hanna-Barbera.",
    hint: "Not including spin-offs and pilots.",
    failedMessage: "[PASS] is not a Hanna-Barbera cartoon.",
    possible: [
      "2 STUPID DOGS",
      "THE ALL NEW POPEYE HOUR",
      "THE AMAZING CHAN AND THE CHAN CLAN",
      "ATOM ANT",
      "THE BANANA SPLITS",
      "THE BERENSTAIN BEARS",
      "BIRDMAN AND THE GALAXY TRIO",
      "THE BSIKITTS",
      "BUTCH CASSIDY AND THE SUNDANCE KIDS",
      "CB BEARS",
      "CAPTAIN CAVEMAN AND THE TEEN ANGELS",
      "CAPTAIN PLANET",
      "CASPER AND THE SPACE ANGELS",
      "CLUE CLUB",
      "COW AND CHICKEN",
      "DAISY-HEAD MAYZIE",
      "DASTARDLY AND MUTTLEY IN THEIR FLYING MACHINES",
      "DEVLIN",
      "DEXTER'S LABRATORY",
      "DINKY DOG",
      "DROOPY, MASTER DETECTIVE",
      "DYNOMUTT DOG WONDER",
      "THE FLINSTONES",
      "FOOFUR",
      "GODZILLA",
      "GOOBER AND THE GHOST CHASERS",
      "THE HAIR BARE BUNCH",
      "THE HERCULOIDS",
      "HONG KONG PHOOEY",
      "HUCKLEBERRY HOUND",
      "I AM WEASEL",
      "THE IMPOSSIBLES",
      "JABBERJAW",
      "JANA OF THE JUNGLE",
      "JEANNIE",
      "THE JESTONS",
      "JOHNNY BRAVO",
      "JONNY QUEST",
      "JOSIE AND THE PUSSYCATS",
      "LOOPY DE LOOP",
      "MAGILLA GORILLA",
      "MOBY DICK AND THE MIGHTY MIGHTOR",
      "ONCE UPON A FOREST",
      "PAC-MAN",
      "PETER POTAMUS",
      "PINK PANTHER",
      "POUND PUPPIES",
      "POWERPUFF GIRLS",
      "QUICK DRAW MCGRAW",
      "THE ROMAN HOLIDAYS",
      "THE RUFF AND READY SHOW",
      "SCOOBY-DOO",
      "SEALAB 2020",
      "SECRET SQUIRREL",
      "SHAZZAN",
      "THE SKATEBIRDS",
      "THE SMURFS",
      "SNORKS",
      "SPACE GHOST",
      "SPEED BUGGY",
      "SWAT KATS",
      "THESE ARE THE DAYS",
      "TOM AND JERRY",
      "TOP CAT",
      "VALLEY OF THE DINOSAURS",
      "WACKY RACES",
      "WAIT TILL YOUR FATHER GETS HOME",
      "WHEELIE AND THE CHOPPER BUNCH",
      "WHERE'S HUDDLES?",
      "YOGI BEAR",
    ],
    source: "https://en.wikipedia.org/wiki/List_of_Hanna-Barbera_characters",
  },

  // Sushi | 69
  {
    id: 69,
    name: "Sushi",
    nameAsRule: "Your password must be an ingredient used in sushi.",
    failedMessage: "[PASS] is not on the list, please try again.",
    possible: [
      "RICE",
      "NORI",
      "SHRIMP",
      // ALSO
      // "EBI"
      "SALMON",
      // ALSO
      // "SAKE"
      "TUNA",
      // ALSO
      // "MAGURO"
      "YELLOWTAIL",
      // ALSO
      // "HAMACHI"
      "OCTOPUS",
      // ALSO
      // "TAKO"
      "MACKAREL",
      // ALSO
      // "AJI"
      "SEA URCHIN",
      // ALSO
      // "UNI"
      "SQUID",
      // ALSO
      // "IKA"
      "FISH EGGS",
      // ALSO
      // "ROE",
      // "TOBIKO",
      // "MASAGO",
      // "SALMON ROE",
      // "IKURA",
      // "CAVIAR"
      "EEL",
      // ALSO
      // "UNAGI",
      // "ANAGI"
      "EGG",
      // ALSO
      // "TAMAGO",
      // "TAMAGOYAKI"
      "RICE VINEGAR",
      // ALSO
      // "KOMEZU"
      "AVOCADO",
      "BURDOCK ROOT",
      // ALSO
      // "GOBO"
      "CUCUMBER",
      "CARROT",
      "CREAM CHEESE",
      "IMITATION CRAB",
      "WASABI",
      "SOY SAUCE",
      "SESAME SEEDS",
      "MUSHROOMS",
      "GINGER",
      "SEAWEED",
      "MITSUBA",
      "KANPYO",
      "SAKE",
      "SCALLION",
      "NATTO",
      "PICKLED PLUM",
      // ALSO
      // "UMEBOSHI",
      "SHISHO",
      "DAIKON",
    ],
    source: "https://www.umami-insider.com/common-japanese-sushi-ingredients-guide/",
  },

  // MLB Baseball | 73
  {
    id: 73,
    name: "MLB Baseball",
    nameAsRule: "Your password must be an MLB baseball team name",
    failedMessage: "Sorry! There are no [PASS] in the MLB.",
    possible: [
      "ORIOLES",
      "RED SOX",
      "YANKEES",
      "RAYS",
      "BLUE JAYS",
      "WHITE SOX",
      "INDIANS",
      "TIGERS",
      "ROYALS",
      "TWINS",
      "ASTROS",
      "ANGELS",
      "ATHLETICS",
      "MARINERS",
      "RANGERS",
      "BRAVES",
      "MARLINS",
      "METS",
      "PHILLIES",
      "NATIONALS",
      "CUBS",
      "REDS",
      "BREWERS",
      "PIRATES",
      "CARDINALS",
      "DIAMONDBACKS",
      "ROCKIES",
      "DODGERS",
      "PADRES",
      "GIANTS",
    ],
    source: "https://en.wikipedia.org/wiki/Major_League_Baseball",
  },

  // Fast Food Chains | 74
  {
    id: 74,
    name: "Fast Food Chains",
    nameAsRule: "Your password must be an American fast food chain",
    hint: "Must be among the top 50 fast food chains, listed by revenue",
    failedMessage: "[PASS] is not on the list, please try again.",
    possible: [
      "MCDONALD'S",
      "STARBUCKS",
      "CHICK-FIL-A",
      "TACO BELL",
      "BURGER KING",
      "SUBWAY",
      "WENDY'S",
      "DUNKIN'",
      "DOMINO'S",
      "PANERA",
      "CHIPOTLE",
      "PIZZA HUT",
      "KFC",
      "SONIC",
      "ARBY'S",
      "LITTLE CAESARS",
      "PANDA EXPRESS",
      "DAIRY QUEEN",
      "POPEYES",
      "JACK IN THE BOX",
      "PAPA JOHN'S",
      "WHATABURGER",
      "JIMMY JOHN'S",
      "HARDEE'S",
      "ZAXBY'S",
      "CULVER'S",
      "FIVE GUYS",
      "RAISING CANE'S",
      "WINGSTOP",
      "CARL'S JR.",
      "JERSEY MIKE'S",
      "BOJANGLES'",
      "IN-N-OUT",
      "STEAK 'N SHAKE",
      "EL POLLO LOCO",
      "QDOBA",
      "CHECKERS",
      "FIREHOUSE",
      "DEL TACO",
      "TIM HORTONS",
      "MOE'S",
      "PAPA MURPHY'S",
      "MCALISTER'S",
      "JASON'S",
      "CHURCH'S",
      "SHAKE SHACK",
      "MARCO'S",
      "BASKIN-ROBBINS",
      "TROPICAL SMOOTHIE",
      "AUNTIE ANNE'S",
    ],
    source: "https://www.visualcapitalist.com/top-50-fast-food-chains-ranked/",
  },

  // Pizza Toppings | 75
  {
    id: 75,
    name: "Pizza Toppings",
    nameAsRule: "Your password must be a pizza topping",
    failedMessage: "You can't get [PASS] on your pizza.",
    hint: "Based on menus from major pizza chains in the U.S.",
    possible: [
      // Meats (most common across all chains)
      "PEPPERONI",
      "ITALIAN SAUSAGE",
      "HAM",
      "BACON",
      "CHICKEN",
      "BEEF",
      "GROUND BEEF",
      "SALAMI",
      "CANADIAN BACON",
      "MEATBALLS",
      "ANCHOVIES",
      "TURKEY",
      "PASTRAMI",

      // Vegetables (standard across chains)
      "MUSHROOMS",
      "ONIONS",
      "GREEN PEPPERS",
      "BLACK OLIVES",
      "TOMATOES",
      "SPINACH",
      "JALAPENOS",
      "PINEAPPLE",
      "GREEN OLIVES",
      "BANANA PEPPERS",
      "RED ONIONS",
      "BROCCOLI",
      "ZUCCHINI",

      // Cheeses (available at most chains)
      "MOZZARELLA",
      "CHEDDAR",
      "PARMESAN",
      "PROVOLONE",
      "FETA",
      "RICOTTA",
      "GOAT CHEESE",

      // Premium/Specialty (available at many chains)
      "BBQ CHICKEN",
      "GRILLED CHICKEN",
      "ROMA TOMATOES",
      "SUN DRIED TOMATOES",
      "ARTICHOKE HEARTS",
      "ROASTED PEPPERS",
      "FRESH BASIL",
      "GARLIC",
      "OREGANO",
      "CILANTRO",
      "ROASTED GARLIC",
    ],
    source: "https://en.wikipedia.org/wiki/List_of_pizza_chains_of_the_United_States",
  },

  // Adobe | 76
  {
    id: 76,
    name: "Adobe Products",
    nameAsRule: "Your password must be a product made by Adobe.",
    hint: "Variants (such as Express, Elements or Rush) are not allowed. But discontinued products are.",
    failedMessage: "Sorry! Adobe does not make [PASS]",
    possible: [
      "ACROBAT",
      "ACROBAT READER",
      "SIGN",
      "ANALYTICS",
      "MAGENTO",
      "MARKETO",
      "ANIMATE",
      "FLASH",
      "FLEX",
      "AIR",
      "SCOUT",
      "AERO",
      "BEHANCE",
      "CONNECT",
      "CREATIVE CLOUD",
      "FRESCO",
      "ILLUSTRATOR",
      "LIGHTROOM",
      "PHONEGAP",
      "PHOTOSHOP",
      "SCAN",
      "SPARK",
      "XD",
      "CAPTIVATE",
      "COLD FUSION",
      "PREMIERE",
      "FONTS",
      "FONT FOLIO",
      "AFTER EFFECTS",
      "CHARACTER ANIMATOR",
      "AUDITION",
      "BRACKETS",
      "BRIDGE",
      "BUSINESS CATALYST",
      "COLOR",
      "CONTENT SERVER",
      "DIGITAL EDITIONS",
      "DIMENSION",
      "DREAMWEAVER",
      "INCOPY",
      "INDESIGN",
      "MUSE",
      "FIREWORKS",
      "ONLOCATION",
      "BROWSERLAB",
      "ATMOSPHERE",
      "FLASHPAPER",
      "GOLIVE",
      "ENCORE",
      "IMAGEREADY",
      "LIVEMOTION",
      "PAGEMAKER",
      "PERSUASION",
      "PHOTODELUXE",
      "SOUNDBOOTH",
      "SOCIAL",
      "SPEEDGRADE",
      "STOCK PHOTOS",
      "STREAMLINE",
      "ULTRA",
    ],
  },

  // Nestlé Brands | 77
  {
    id: 77,
    name: "Nestlé Brands",
    nameAsRule: "Your password must be a brand owned by Nestlé",
    hint: "Looking for brands, not products",
    failedMessage: "[PASS] isn't on the list of Nestlé brands",
    possible: [
      "CARNATION",
      "NESCAU",
      "OVALTINE",
      "CARO",
      "LIBBY'S",
      "NESQUIK",
      "SWEET LEAF",
      "PEACE",
      "MILO",
      "BLUE BOTTLE",
      "PARTNER'S BLEND",
      "BONKA",
      "DULCE GUSTO",
      "MOUNTAIN BLEND",
      "TASTER'S CHOICE",
      "CHAMELEON",
      "NESCAFE",
      //ALSO
      //Nescafé
      "NESPRESSO",
      "PERRIER",
      "ICE MOUNTAIN",
      "PLANCOET",
      "POLAND SPRING",
      "MONTCLAIR",
      "PURE LIFE",
      "SAN PELLEGRINO",
      "CRUNCH",
      "LION",
      "SHREDDIES",
      "CINI MINIS",
      "GOLDEN NUGGETS",
      "AERO",
      "QUALITY STREET",
      "WONKA",
      "BIG TURK",
      "CALIFORNIA PIZZA KITCHEN",
      "LEAN CUISINE",
      "HOT POCKETS",
      "DIGIORNO",
      "STOUFFER'S",
      "TOMBSTONE",
      "JACK'S",
      "PAPA GIUSEPPE",
      "HAAGEN-DAZS",
      "DRUMSTICK",
      "BOOST",
      "PETLIFE",
      "TIDY CATS",
      "WHOLE EARTH",
      "PURINA",
      "TOLL HOUSE",
      "COFFEE-MATE",
    ],
  },

  // U.S. Presidents | 79
  {
    id: 79,
    name: "U.S. Presidents",
    nameAsRule: "Your password must be the last name of a U.S. President.",
    failedMessage: "[PASS] is not a U.S. President.",
    possible: [
      "WASHINGTON",
      "ADAMS",
      "JEFFERSON",
      "MADISON",
      "MONROE",
      "ADAMS", // John Quincy Adams
      "JACKSON",
      "VAN BUREN",
      "HARRISON", // William Henry Harrison
      "TYLER",
      "POLK",
      "TAYLOR",
      "FILLMORE",
      "PIERCE",
      "BUCHANAN",
      "LINCOLN",
      "JOHNSON", // Andrew Johnson
      "GRANT",
      "HAYES",
      "GARFIELD",
      "ARTHUR",
      "CLEVELAND",
      "HARRISON", // Benjamin Harrison
      "CLEVELAND", // Grover Cleveland served two non-consecutive terms
      "MCKINLEY",
      "ROOSEVELT", // Theodore Roosevelt
      "TAFT",
      "WILSON",
      "HARDING",
      "COOLIDGE",
      "HOOVER",
      "ROOSEVELT", // Franklin D. Roosevelt
      "TRUMAN",
      "EISENHOWER",
      "KENNEDY",
      "JOHNSON", // Lyndon B. Johnson
      "NIXON",
      "FORD",
      "CARTER",
      "REAGAN",
      "BUSH", // George H. W. Bush
      "CLINTON",
      "BUSH", // George W. Bush
      "OBAMA",
      "TRUMP",
      "BIDEN",
    ],
    source: "https://en.wikipedia.org/wiki/List_of_presidents_of_the_United_States",
  },

  // Periodic Table Elements | 80
  {
    id: 80,
    name: "Periodic Table Elements",
    nameAsRule: "Your password must be the name of an element on the periodic table.",
    failedMessage: "[PASS] is not an element on the periodic table.",
    possible: [
      "HYDROGEN",
      "HELIUM",
      "LITHIUM",
      "BERYLLIUM",
      "BORON",
      "CARBON",
      "NITROGEN",
      "OXYGEN",
      "FLUORINE",
      "NEON",
      "SODIUM",
      "MAGNESIUM",
      "ALUMINIUM",
      "SILICON",
      "PHOSPHORUS",
      "SULFUR",
      "CHLORINE",
      "ARGON",
      "POTASSIUM",
      "CALCIUM",
      "SCANDIUM",
      "TITANIUM",
      "VANADIUM",
      "CHROMIUM",
      "MANGANESE",
      "IRON",
      "COBALT",
      "NICKEL",
      "COPPER",
      "ZINC",
      "GALLIUM",
      "GERMANIUM",
      "ARSENIC",
      "SELENIUM",
      "BROMINE",
      "KRYPTON",
      "RUBIDIUM",
      "STRONTIUM",
      "YTTRIUM",
      "ZIRCONIUM",
      "NIOBIUM",
      "MOLYBDENUM",
      "TECHNETIUM",
      "RUTHENIUM",
      "RHODIUM",
      "PALLADIUM",
      "SILVER",
      "CADMIUM",
      "INDIUM",
      "TIN",
      "ANTIMONY",
      "TELLURIUM",
      "IODINE",
      "XENON",
      "CESIUM",
      "BARIUM",
      "LANTHANUM",
      "CERIUM",
      "PRASEODYMIUM",
      "NEODYMIUM",
      "PROMETHIUM",
      "SAMARIUM",
      "EUROPIUM",
      "GADOLINIUM",
      "TERBIUM",
      "DYSPROSIUM",
      "HOLMIUM",
      "ERBIUM",
      "THULIUM",
      "YTTERBIUM",
      "LUTETIUM",
      "HAFNIUM",
      "TANTALUM",
      "TUNGSTEN",
      "RHENIUM",
      "OSMIUM",
      "IRIDIUM",
      "PLATINUM",
      "GOLD",
      "MERCURY",
      "THALLIUM",
      "LEAD",
      "BISMUTH",
      "POLONIUM",
      "ASTATINE",
      "RADON",
      "FRANCIUM",
      "RADIUM",
      "ACTINIUM",
      "THORIUM",
      "PROTACTINIUM",
      "URANIUM",
      "NEPTUNIUM",
      "PLUTONIUM",
      "AMERICIUM",
      "CURIUM",
      "BERKELIUM",
      "CALIFORNIUM",
      "EINSTEINIUM",
      "FERMIUM",
      "MENDELEVIUM",
      "NOBELIUM",
      "LAWRENCIUM",
      "RUTHERFORDIUM",
      "DUBNIUM",
      "SEABORGIUM",
      "BOHRIUM",
      "HASSIUM",
      "MEITNERIUM",
      "DARMSTADTIUM",
      "ROENTGENIUM",
      "COPERNICIUM",
      "NIHONIUM",
      "FLEROVIUM",
      "MOSCOVIUM",
      "LIVERMORIUM",
      "TENNESSINE",
      "OGANESSON",
    ],
    source: "https://en.wikipedia.org/wiki/List_of_chemical_elements",
  },

  // Phonetic Alphabet | 81
  {
    id: 81,
    name: "Phonetic Alphabet",
    nameAsRule: "Your password must be a word from the NATO alphabet.",
    hint: "aka the military alphabet, radio alphabet",
    failedMessage: "[PASS] is not a word in the NATO phonetic alphabet.",
    possible: [
      "ALFA",
      "BRAVO",
      "CHARLIE",
      "DELTA",
      "ECHO",
      "FOXTROT",
      "GOLF",
      "HOTEL",
      "INDIA",
      "JULIETT",
      "KILO",
      "LIMA",
      "MIKE",
      "NOVEMBER",
      "OSCAR",
      "PAPA",
      "QUEBEC",
      "ROMEO",
      "SIERRA",
      "TANGO",
      "UNIFORM",
      "VICTOR",
      "WHISKEY",
      "XRAY",
      "YANKEE",
      "ZULU",
    ],
    source: "https://en.wikipedia.org/wiki/NATO_phonetic_alphabet",
  },

  // Crayola Colors | 82
  {
    id: 82,
    name: "Crayola Colors",
    nameAsRule: "Your password must be a color from a modern Crayola 64-pack.",
    failedMessage: "[PASS] is not a color from a modern Crayola 64-pack. Note that some older colors have been retired.",
    possible: [
      "APRICOT",
      "AQUAMARINE",
      "ASPARAGUS",
      "BLACK",
      "BLUE",
      "BLUE BELL",
      "BLUE GREEN",
      "BLUE VIOLET",
      "BRICK RED",
      "BROWN",
      "BURNT SIENNA",
      "BURNT UMBER",
      "CADET BLUE",
      "CARNATION PINK",
      "CERULEAN",
      "CHARCOAL",
      "CHARTREUSE",
      "CHESTNUT",
      "CORNFLOWER",
      "CYAN",
      "DESERT SAND",
      "EGGPLANT",
      "EMERALD",
      "FOREST GREEN",
      "FUCHSIA",
      "GOLD",
      "GOLDENROD",
      "GRAY",
      "GREEN",
      "GREEN YELLOW",
      "HOT PINK",
      "INDIGO",
      "KELLY GREEN",
      "LAVENDER",
      "LEMON YELLOW",
      "LIME GREEN",
      "MAGENTA",
      "MAHOGANY",
      "MANGO TANGO",
      "MAROON",
      "MAUVE",
      "MELON",
      "MIDNIGHT BLUE",
      "MINT GREEN",
      "NAVY BLUE",
      "OLIVE GREEN",
      "ORANGE",
      "ORCHID",
      "OUTER SPACE",
      "PALE GREEN",
      "PEACH",
      "PINE GREEN",
      "PINK",
      "PLUM",
      "PURPLE",
      "RAW SIENNA",
      "RED",
      "RED VIOLET",
      "ROBIN'S EGG BLUE",
      "ROSE",
      "SALMON",
      "SCARLET",
      "SILVER",
      "SKY BLUE",
      "SLATE GRAY",
      "SPRING GREEN",
      "SUNSHINE",
      "TAN",
      "TEAL",
      "TULIP",
      "TURQUOISE BLUE",
      "VIOLET",
      "VIOLET RED",
      "WINE",
      "YELLOW",
      "YELLOW GREEN",
      "YELLOW ORANGE",
      "ZOMBO",
    ],
    source: "https://www.crayola.com/explore/color-collection/64-count-crayons.aspx",
  },

  // Constellations | 84
  {
    id: 84,
    name: "Constellations",
    nameAsRule: "Your password must be the name of a constellation",
    hint: "as officially recognized by the International Astronomical Union",
    failedMessage: "The IAU does not recognize [PASS] as a constellation.",
    possible: [
      "ANDROMEDA",
      "ANTLIA",
      "APUS",
      "AQUARIUS",
      "AQUILA",
      "ARA",
      "ARIES",
      "AURIGA",
      "BOÖTES",
      "CAELUM",
      "CAMELOPARDALIS",
      "CANCER",
      "CANES VENATICI",
      "CANIS MAJOR",
      "CANIS MINOR",
      "CAPRICORNUS",
      "CARINA",
      "CASSIOPEIA",
      "CENTAURUS",
      "CEPHEUS",
      "CETUS",
      "CHAMAELEON",
      "CIRCINUS",
      "COLUMBA",
      "COMA BERENICES",
      "CORONA AUSTRALIS",
      "CORONA BOREALIS",
      "CORVUS",
      "CRATER",
      "CRUX",
      "CYGNUS",
      "DELPHINUS",
      "DORADO",
      "DRACO",
      "EQUULEUS",
      "ERIDANUS",
      "FORNAX",
      "GEMINI",
      "GRUS",
      "HERCULES",
      "HOROLOGIUM",
      "HYDRA",
      "HYDRUS",
      "INDUS",
      "LACERTA",
      "LEO",
      "LEO MINOR",
      "LEPUS",
      "LIBRA",
      "LUPUS",
      "LYNX",
      "LYRA",
      "MENSA",
      "MICROSCOPIUM",
      "MONOCEROS",
      "MUSCA",
      "NORMA",
      "OCTANS",
      "OPHIUCHUS",
      "ORION",
      "PAVO",
      "PEGASUS",
      "PERSEUS",
      "PHOENIX",
      "PICTOR",
      "PISCES",
      "PISCIS AUSTRINUS",
      "PUPPIS",
      "PYXIS",
      "RETICULUM",
      "SAGITTA",
      "SAGITTARIUS",
      "SCORPIUS",
      "SCULPTOR",
      "SCUTUM",
      "SERPENS",
      "SEXTANS",
      "TAURUS",
      "TELESCOPIUM",
      "TRIANGULUM",
      "TRIANGULUM AUSTRALE",
      "TUCANA",
      "URSA MAJOR",
      "URSA MINOR",
      "VELA",
      "VIRGO",
      "VOLANS",
      "VULPECULA",
    ],
    source: "https://en.wikipedia.org/wiki/88_constellations",
  },

  // Composers | 85
  {
    id: 85,
    name: "Classical Composers",
    nameAsRule: "Your password must be the last name a classical composer.",
    hint: "as defined by BBC Music Magazine",
    failedMessage: "BBC Music Magazine does not include [PASS] in its list of the 50 greatest composers.",
    possible: [
      "BACH",
      "BEETHOVEN",
      "MOZART",
      "WAGNER",
      "HAYDN",
      "BRAHMS",
      "SCHUBERT",
      "TCHAIKOVSKY",
      "HANDEL",
      "STRAVINSKY",
      "SCHUMANN",
      "CHOPIN",
      "MENDELSSOHN",
      "DEBUSSY",
      "LISZT",
      "DVOŘÁK",
      "VERDI",
      "MAHLER",
      "VIVALDI",
      "STRAUSS",
      "PROKOFIEV",
      "SHOSTAKOVICH",
      "BARTÓK",
      "BERLIOZ",
      "BRUCKNER",
      "MONTEVERDI",
      "SIBELIUS",
      "RAVEL",
      "PUCCINI",
      "RACHMANINOV",
      "PURCELL",
      "PALESTRINA",
      "GESUALDO",
      "RAMEAU",
      "GLUCK",
      "ROSSINI",
      "GLINKA",
      "MUSSORGSKY",
      "RIMSKY-KORSAKOV",
      "GRIEG",
      "FAURÉ",
      "SATIE",
      "JANÁČEK",
      "PÄRT",
      "ADAMS",
      "GLASS",
      "CAGE",
      "LIGETI",
      "MESSIAEN",
    ],
    source: "https://www.classical-music.com/features/composers/50-greatest-composers-all-time/",
  },

  // EU Countries | 86
  {
    id: 86,
    name: "EU Countries",
    nameAsRule: "Your password must be a country in the European Union.",
    hint: "only member states are allowed",
    failedMessage: "[PASS] is not a member state of the European Union.",
    possible: [
      "AUSTRIA",
      "BELGIUM",
      "BULGARIA",
      "CROATIA",
      "CYPRUS",
      "CZECH REPUBLIC",
      "DENMARK",
      "ESTONIA",
      "FINLAND",
      "FRANCE",
      "GERMANY",
      "GREECE",
      "HUNGARY",
      "IRELAND",
      "ITALY",
      "LATVIA",
      "LITHUANIA",
      "LUXEMBOURG",
      "MALTA",
      "NETHERLANDS",
      "POLAND",
      "PORTUGAL",
      "ROMANIA",
      "SLOVAKIA",
      "SLOVENIA",
      "SPAIN",
      "SWEDEN",
    ],
    source: "https://european-union.europa.eu/principles-countries-history/countries-eu_en",
  },

  // Europe Capitals | 87
  {
    id: 87,
    name: "Europe Capitals",
    nameAsRule: "Your password must be the capital of a country in Europe.",
    failedMessage: "[PASS] is not the capital of any member state in the Council of Europe.",
    possible: [
      "TIRANA",
      "ANDORRA LA VELLA",
      "YEREVAN",
      "VIENNA",
      "BAKU",
      "BRUSSELS",
      "SARAJEVO",
      "SOFIA",
      "ZAGREB",
      "NICOSIA",
      "PRAGUE",
      "COPENHAGEN",
      "TALLINN",
      "HELSINKI",
      "PARIS",
      "TBILISI",
      "BERLIN",
      "ATHENS",
      "BUDAPEST",
      "REYKJAVIK",
      "DUBLIN",
      "ROME",
      "RIGA",
      "VADUZ",
      "VILNIUS",
      "LUXEMBOURG",
      "VALLETTA",
      "CHIȘINĂU",
      "MONACO",
      "PODGORICA",
      "AMSTERDAM",
      "SKOPJE",
      "OSLO",
      "WARSAW",
      "LISBON",
      "BUCHAREST",
      "SAN MARINO",
      "BELGRADE",
      "BRATISLAVA",
      "LJUBLJANA",
      "MADRID",
      "STOCKHOLM",
      "BERN",
      "ANKARA",
      "KYIV",
      "LONDON",
    ],
    source: "https://www.coe.int/en/web/portal/members-states",
  },

  // Programming Languages | 88
  {
    id: 88,
    name: "Programming Languages",
    nameAsRule: "Your password must be the name of a programming languages.",
    hint: "as ranked in top 50 in The TIOBE Index",
    failedMessage: "The TIOBE Index does not rank [PASS] as one of the 50 most popular programming languages.",
    possible: [
      "PYTHON",
      "C",
      "JAVA",
      "C++",
      "C#",
      "JAVASCRIPT",
      "GO",
      "SQL",
      "SWIFT",
      "PHP",
      "ASSEMBLY LANGUAGE",
      "RUST",
      "RUBY",
      "KOTLIN",
      "MATLAB",
      "R",
      "TYPESCRIPT",
      "SCRATCH",
      "VISUAL BASIC",
      "PERL",
      "DELPHI",
      "OBJECT PASCAL",
      "DART",
      "GROOVY",
      "FORTRAN",
      "COBOL",
      "ADA",
      "JULIA",
      "LISP",
      "PROLOG",
      "CLASSIC VISUAL BASIC",
      "PL/SQL",
      "TRANSACT-SQL",
      "LOGO",
      "V",
      "POWERSHELL",
      "ABAP",
      "SCHEME",
      "AWK",
      "ELIXIR",
      "HASKELL",
      "FORTH",
      "CLOJURE",
      "F#",
      "ERLANG",
      "D",
      "OCAML",
      "RPG",
      "APEX",
      "SAS",
      "LABVIEW",
    ],
    source: "https://www.tiobe.com/tiobe-index/",
  },

  // Holywood Walk of Fame | 90
  {
    id: 90,
    name: "Hollywood Walk of Fame",
    nameAsRule: "Your password should be one the first 50 people with a star on the Hollywood Walk of Fame.",
    hint: "Last Name Only",
    failedMessage: "[PASS] was not one of the first 50 poeple on the Hollywood Walk of Fame.",
    possible: [
      "KRAMER",
      "LANCASTER",
      "WOODWARD",
      "BORDEN",
      "COLMAN",
      "FAZENDA",
      "FOSTER",
      "TORRENCE",
      "ARNAZ",
      "BALL",
      "DEMILLE",
      "DISNEY",
      "MACRAE",
      "GWENN",
      "MURPHY",
      "BENNY",
      "JONES",
      "AUTRY",
      "SHORE",
      "TAYLOR",
      "GOLDWYN",
      "LASKY",
      "ROACH",
      "SENNETT",
      "LANTZ",
      "ARTHUR",
      "ASTAIRE",
      "ASTOR",
      "BOGART",
      "BOW",
      "CHAPLIN",
      "COOPER",
      "DAVIS",
      "DEAN",
      "FAIRBANKS",
      "GARBO",
      "GARLAND",
      "GRANT",
      "HEPBURN", // Audrey Hepburn and Katharine Hepburn are both listed as "HEPBURN"
      "HITCHCOCK",
      "HOPE",
      "KARLOFF",
      "KEATON",
      "LAUREL",
      "WEST",
      "WAYNE",
      "GRABLE",
      "MURRAY",
      "MONROE",
    ],
    source: "https://walkoffame.com/history/",
  },

  // Marvel Actors | 91
  {
    id: 91,
    name: "Marvel Actors",
    nameAsRule: "Your password must be somebody who played a superhero in a Marvel Movie",
    hint: "Last Name Only",
    failedMessage: "[PASS] never played a superhero in a Marvel movie.",
    possible: [
      "DOWNEY", // Robert Downey Jr. as Iron Man
      "EVANS", // Chris Evans as Captain America
      "HEMSWORTH", // Chris Hemsworth as Thor
      "RUFFALO", // Mark Ruffalo as Hulk
      "JOHANSSON", // Scarlett Johansson as Black Widow
      "RENNER", // Jeremy Renner as Hawkeye
      "HOLLAND", // Tom Holland as Spider-Man
      "BOSEMAN", // Chadwick Boseman as Black Panther
      "LARSON", // Brie Larson as Captain Marvel
      "RUDD", // Paul Rudd as Ant-Man
      "CUMBERBATCH", // Benedict Cumberbatch as Doctor Strange
      "PRATT", // Chris Pratt as Star-Lord
      "SALDANA", // Zoe Saldana as Gamora
      "BAUTISTA", // Dave Bautista as Drax
      "OLSEN", // Elizabeth Olsen as Scarlet Witch
      "MACKIE", // Anthony Mackie as Falcon / Captain America
      "STAN", // Sebastian Stan as Winter Soldier
      "HIDDLESTON", // Tom Hiddleston as Loki
      "JACKSON", // Samuel L. Jackson as Nick Fury
      "CHEADLE", // Don Cheadle as War Machine
      "LILLY", // Evangeline Lilly as The Wasp
      "BETTANY", // Paul Bettany as Vision
      "DIESEL", // Vin Diesel as Groot (voice)
      "COOPER", // Bradley Cooper as Rocket (voice)
      "THOMPSON", // Tessa Thompson as Valkyrie
      "JACKMAN", // Hugh Jackman as Wolverine
      "REYNOLDS", // Ryan Reynolds as Deadpool
      "STEWART", // Patrick Stewart as Professor X
      "MCAVOY", // James McAvoy as Professor X
      "LAWRENCE", // Jennifer Lawrence as Mystique
      "ISAAC", // Oscar Isaac as Moon Knight
      "LIU", // Simu Liu as Shang-Chi
      "PUGH", // Florence Pugh as Yelena Belova
      "STEINFELD", // Hailee Steinfeld as Kate Bishop
      "MAGUIRE", // Tobey Maguire as Spider-Man
      "GARFIELD", // Andrew Garfield as Spider-Man
      "AFFLECK", // Ben Affleck as Daredevil
      "ALBA", // Jessica Alba as Invisible Woman
      "JONES", // Jessica Jones
      "COX", // Charlie Cox as Daredevil
      "LUNA", // Gabriel Luna as Ghost Rider
      "HARDY", // Tom Hardy as Venom
      "GYLLENHAAL", // Jake Gyllenhaal as Mysterio
      "BERRY", // Halle Berry as Storm
      "PAGE", // Ellen Page as Kitty Pryde
      "BROLIN", // Josh Brolin as Thanos / Cable
      "ZENDAYA", // Zendaya as MJ
      "PALTROW", // Gwyneth Paltrow as Pepper Potts
    ],
    source: "https://en.wikipedia.org/wiki/List_of_Marvel_Cinematic_Universe_cast_members",
  },

  // Cities in Canada | 92
  {
    id: 92,
    name: "Cities in Canada",
    nameAsRule: "Your password must be a city in Canada.",
    hint: "top 30, by population",
    failedMessage: "Sorry [PASS], is not one of the 30 most populated cities in Canada.",
    possible: [
      "TORONTO",
      "MONTREAL",
      "VANCOUVER",
      "CALGARY",
      "EDMONTON",
      "OTTAWA",
      "WINNIPEG",
      "QUEBEC CITY",
      "HAMILTON",
      "HALIFAX",
      "LONDON",
      "KITCHENER",
      "ST. CATHARINES",
      "NIAGARA FALLS",
      "OSHAWA",
      "VICTORIA",
      "WINDSOR",
      "SASKATOON",
      "REGINA",
      "KELOWNA",
      "SURREY",
      "KINGSTON",
      "ABBOTSFORD",
      "GUELPH",
      "BARRIE",
      "SAINT JOHN",
      "SHERBROOKE",
      "TROIS-RIVIERES",
      "MONCTON",
      "BRANTFORD",
    ],
    source: "https://en.wikipedia.org/wiki/List_of_the_largest_cities_in_Canada_by_population",
  },

  // Greek Gods | 93
  {
    id: 93,
    name: "Greek Gods",
    nameAsRule: "Your password must be a Greek God",
    hint: "(or goddess)",
    failedMessage: "[PASS] is not the name of a greek olympian, minor god, or other diety.",
    possible: [
      // Olympians
      "ZEUS",
      "HERA",
      "POSEIDON",
      "DEMETER",
      "ARES",
      "ATHENA",
      "APOLLO",
      "ARTEMIS",
      "HEPHAESTUS",
      "APHRODITE",
      "HERMES",
      "DIONYSUS",
      "HESTIA",
      "HADES",

      // Other Deities and Minor Gods
      "PERSEPHONE",
      "HECATE",
      "IRIS",
      "PAN",
      "ASCLEPIUS",
      "HEBE",
      "EOLUS",
      "JANUS",
      "NEMESIS",
      "NIKE",
      "ECHO",
    ],
    source: "https://en.wikipedia.org/wiki/List_of_Greek_mythological_figures",
  },

  // Greek Mythology | 96
  {
    id: 96,
    name: "Greek Mythology (Misc)",
    nameAsRule: "Your password must be a hero, titan, or mythical beast from Greek Mythology.",
    failedMessage: "[PASS] is not a recognized Greek hero, Titan, or mythical beast.",
    possible: [
      // Heroes
      "HERACLES",
      "PERSEUS",
      "ODYSSEUS",
      "ACHILLES",
      "THESEUS",
      "JASON",
      "BELLEROPHON",
      "HECTOR",
      "ORPHEUS",
      "ATALANTA",
      "OEDIPUS",
      "AENEAS",

      // Titans
      "KRONOS",
      "RHEA",
      "GAIA",
      "OURANOS",
      "OCEANUS",
      "PROMETHEUS",
      "ATLAS",
      "THEMIS",
      "HYPERION",
      "COEUS",
      "CRONUS",
      "PHOEBE",
      "TETHYS",
      "LAPETUS",

      // Mythical Beasts
      "MEDUSA",
      "MINOTAUR",
      "HYDRA",
      "CERBERUS",
      "CHIMERA",
      "SPHINX",
      "CYCLOPS",
      "SIRENS",
      "SCYLLA",
      "CHARYBDIS",
      "HARPIES",
      "GORGON",
      "GRIFFIN",
      "DRAKON",
      "KRAKEN",
    ],
    source: "https://en.wikipedia.org/wiki/List_of_Greek_mythological_figures",
  },

  // World Rvers | 97
  {
    id: 97,
    name: "World Rivers",
    nameAsRule: "Your password must be one of the longest rivers in the world.",
    failedMessage: "Sorry, [PASS] is not one of the world's 40 longest rivers.",
    possible: [
      "NILE",
      "AMAZON",
      "YANGTZE",
      "MISSISSIPPI",
      "YENISEY",
      "YELLOW RIVER",
      "OB",
      "PARANA",
      "CONGO",
      "AMUR",
      "LENA",
      "MEKONG",
      "MACKENZIE",
      "NIGER",
      "BRAHMAPUTRA",
      "MURRAY-DARLING",
      "TOCANTINS",
      "VOLGA",
      "EUPHRATES",
      "MADEIRA",
      "PURÚS",
      "YUKON",
      "INDUS",
      "SÃO FRANCISCO",
      "SYR DARYA",
      "SALWEEN",
      "SAINT LAWRENCE",
      "RIO GRANDE",
      "LOWER TUNGUSKA",
      "COLORADO",
      "DANUBE",
      "IRRAWADDY",
      "ZAMBEZI",
      "AMU DARYA",
      "ORANGE",
      "GANGES",
      "COLUMBIA",
      "TIGRIS",
      "MARONI",
      "XINGU",
    ],
    source: "https://en.wikipedia.org/wiki/List_of_river_systems_by_length",
  },

  // Types of Pasta | 98
  {
    id: 98,
    name: "Types of Pasta",
    nameAsRule: "Your password must be a type of pasta.",
    failedMessage: "[PASS] is not recognized as a pasta shape in the PastaFits Pasta Dictionary.",
    possible: [
      "ANGEL HAIR",
      "BUCATINI",
      "CAPELLINI",
      "DITALINI",
      "FARFALLE",
      "FETTUCCINE",
      "FUSILLI",
      "GEMELLI",
      "GNOCCHI",
      "LASAGNA",
      "LINGUINE",
      "MACARONI",
      "MANICOTTI",
      "ORZO",
      "PAPPARDELLE",
      "PASTINA",
      "PENNE",
      "RADIATORE",
      "RAVIOLI",
      "RIGATONI",
      "ROTELLE",
      "ROTINI",
      "SHELLS",
      "SPAGHETTI",
      "TAGLIATELLE",
      "TORTELLINI",
      "TUBINI",
      "VERMICELLI",
      "ZITI",
    ],
    source: "https://www.pastafits.org/pasta-dictionary/",
  },

  // Spice Rack | 99
  {
    id: 99,
    name: "Spice Rack",
    nameAsRule: "Your password must be the name of a spice.",
    failedMessage: "[PASS] is not on the official list of dried spices from the CIA.",
    hint: "as defined by the Culinary Institute of America",
    possible: [
      "ALLSPICE",
      "ANCHO CHILE",
      "ANISE",
      "ANNATTO SEED",
      "BASIL",
      "BAY LEAF",
      "CARDAMOM",
      "CARAWAY",
      "CAYENNE PEPPER",
      "CHILI POWDER",
      "CINNAMON",
      "CLOVES",
      "CORIANDER",
      "CUMIN",
      "CURRY POWDER",
      "DILL",
      "FENNEL SEED",
      "FENUGREEK",
      "GARLIC POWDER",
      "GINGER",
      "JUNIPER BERRIES",
      "MACE",
      "MARJORAM",
      "MUSTARD SEED",
      "NUTMEG",
      "ONION POWDER",
      "OREGANO",
      "PAPRIKA",
      "PEPPERCORN",
      "ROSEMARY",
      "SAFFRON",
      "SAGE",
      "SESAME SEED",
      "STAR ANISE",
      "SUMAC",
      "THYME",
      "TURMERIC",
    ],
    source: "https://www.ciachef.edu/wp-content/uploads/2024/07/dried-spices.pdf",
  },

  // WWE Champions | 100
  {
    id: 100,
    name: "WWE Champions",
    nameAsRule: "Your password must be the last name of a WWF/WWE Champion.",
    failedMessage: "[PASS] is not the last name of someone who has held the WWF/WWE Championship belt.",
    hint: "Last names only, if applicable.",
    possible: [
      "ROGERS",
      "SAMMARTINO",
      "KOLOFF",
      "MORALES",
      "STASIAK",
      "GRAHAM",
      "BACKLUND",
      "INOKI",
      "SHEIK",
      "HOGAN",
      "GIANT",
      "DIBIASE",
      "SAVAGE",
      "WARRIOR",
      "SLAUGHTER",
      "UNDERTAKER",
      "FLAIR",
      "HART",
      "YOKOZUNA",
      "DIESEL",
      "MICHAELS",
      "SID",
      "AUSTIN",
      "KANE",
      "ROCK",
      "MANKIND",
      "FOLEY",
      "HELMSLEY",
      "MCMAHON",
      "SHOW",
      "ANGLE",
      "JERICHO",
      "LESNAR",
      "GUERRERO",
      "LAYFIELD",
      "CENA",
      "EDGE",
      "VAN DAM",
      "ORTON",
      "HARDY",
      "BATISTA",
      "SHEAMUS",
      "MIZ",
      "PUNK",
      "MYSTERIO",
      "DEL RIO",
      "BRYAN",
      "ROLLINS",
      "REIGNS",
      "AMBROSE",
      "STYLES",
      "WYATT",
      "MAHAL",
      "KINGSTON",
      "MCINTYRE",
      "LASHLEY",
      "BIG E",
      "RHODES",
    ],
    source: "https://en.wikipedia.org/wiki/List_of_WWE_Champions",
  },

  // DC Comics Movies | 101
  {
    id: 101,
    name: "DC Comics Movies",
    nameAsRule: "Your password must be a theatrical film featuring DC Comics characters",
    failedMessage: "[PASS] is not the title of a DC Comics superhero movie.",
    hint: "No sequels. Don't include 'The' in titles.",
    possible: [
      "SUPERMAN",
      "SUPERGIRL",
      "BATMAN",
      "STEEL",
      "CATWOMAN",
      "CONSTANTINE",
      "BATMAN BEGINS",
      "SUPERMAN RETURNS",
      "WATCHMEN",
      "JONAH HEX",
      "GREEN LANTERN",
      "MAN OF STEEL",
      "SUICIDE SQUAD",
      "WONDER WOMAN",
      "JUSTICE LEAGUE",
      "AQUAMAN",
      "SHAZAM!",
      "JOKER",
      "BIRDS OF PREY",
      "BATMAN",
      "BLACK ADAM",
      "FLASH",
      "BLUE BEETLE",
      "V FOR VENDETTA",
      "LEAGUE OF EXTRAORDINARY GENTLEMEN",
      "A HISTORY OF VIOLENCE",
      "ROAD TO PERDITION",
      "RED",
      "STARDUST",
      "LOSERS",
      "KITCHEN",
    ],
    source: "https://en.wikipedia.org/wiki/List_of_films_based_on_DC_Comics_publications",
  },

  // Orchestra Instruments | 102
  {
    id: 102,
    name: "Orchestra Instruments",
    nameAsRule: "Your password must be an orchestral instrument.",
    failedMessage: "[PASS] is not a standard modern symphony orchestra instrument.",
    hint: "Basic instrument names from a modern symphony orchestra.",
    possible: [
      // Strings
      "VIOLIN",
      "VIOLA",
      "CELLO",
      "DOUBLE BASS",
      "HARP",
      // Woodwinds
      "FLUTE",
      "PICCOLO",
      "OBOE",
      "COR ANGLAIS",
      "ENGLISH HORN",
      "HECKELPHONE",
      "CLARINET",
      "BASSET HORN",
      "BASSOON",
      "CONTRABASSOON",
      "SAXOPHONE",
      // Brass
      "HORN",
      "FRENCH HORN",
      "TRUMPET",
      "CORNET",
      "FLUGELHORN",
      "TROMBONE",
      "CIMBASSO",
      "TUBA",
      "EUPHONIUM",
      // Percussion
      "TIMPANI",
      "SNARE DRUM",
      "TENOR DRUM",
      "TOM-TOM",
      "BASS DRUM",
      "CYMBALS",
      "TRIANGLE",
      "TAM-TAM",
      "TAMBOURINE",
      "WOOD BLOCK",
      "GLOCKENSPIEL",
      "XYLOPHONE",
      "VIBRAPHONE",
      "MARIMBA",
      "TUBULAR BELLS",
      "CHIMES",
      // Keyboards
      "PIANO",
      "PIPE ORGAN",
      "HARPSICHORD",
      "ACCORDION",
      "CELESTA",
    ],
    source: "https://en.wikipedia.org/wiki/Orchestra",
  },

  // Valuable Painters | 103
  {
    id: 103,
    name: "Valuable Painters",
    nameAsRule: "Your password must be the last name of a valuable painter.",
    failedMessage: "[PASS] is not the last name of an artist who created one of the 50 most expensive paintings.",
    hint: "Last name only",
    possible: [
      "DA VINCI",
      "DE KOONING",
      "CEZANNE",
      "GAUGUIN",
      "POLLOCK",
      "KLIMT",
      "ROTHKO",
      "PICASSO",
      "REMBRANDT",
      "MODIGLIANI",
      "RENOIR",
      "BAISHI",
      "SEURAT",
      "MUNCH",
      "BACON",
      "VAN GOGH",
      "MONET",
      "RUBENS",
      "LICHTENSTEIN",
      "WARHOL",
      "BASQUIAT",
      "HOPPER",
      "NEWMAN",
      "RAUSCHENBERG",
      "MALEVICH",
      "BOTTICELLI",
      "TWOMBLY",
      "MATISSE",
      "TITIAN",
      "EAKINS",
      "JOHNS",
      "HOCKNEY",
      "KOONS",
      "MAGRITTE",
      "WU BIN",
      "WANG MENG",
      "ZAO WOU-KI",
      "LEGER",
      "STILL",
      "HOLBEIN",
      "PONTORMO",
    ],
    source: "https://en.wikipedia.org/wiki/List_of_most_expensive_paintings",
  },

  // Hotel Breakfast | 104
  {
    id: 104,
    name: "Hotel Breakfast",
    nameAsRule: "Your password must be a food served in a hotel breakfast buffet",
    failedMessage: "You won't find [PASS] at the hotel breakfast buffet.",
    hint: "Foods only, no beverages.",
    possible: [
      // Hot Foods
      "SCRAMBLED EGGS",
      "FRIED EGGS",
      "BACON",
      "SAUSAGE",
      "HAM",
      "HASH BROWNS",
      "HOME FRIES",
      "PANCAKES",
      "WAFFLES",
      "FRENCH TOAST",
      "OATMEAL",
      "GRITS",
      "BISCUITS",
      "GRAVY",

      // Bread & Pastries
      "TOAST",
      "BAGELS",
      "MUFFINS",
      "CROISSANTS",
      "DANISH",
      "DONUTS",
      "CINNAMON ROLLS",
      "ENGLISH MUFFINS",
      "BREAD",
      "ROLLS",

      // Cereals & Grains
      "CEREAL",
      "GRANOLA",
      "CORNFLAKES",
      "CHEERIOS",
      "RAISIN BRAN",

      // Dairy
      "MILK",
      "YOGURT",
      "COTTAGE CHEESE",
      "CREAM CHEESE",

      // Fruits
      "BANANAS",
      "APPLES",
      "ORANGES",
      "GRAPEFRUIT",
      "CANTALOUPE",
      "HONEYDEW",
      "GRAPES",
      "STRAWBERRIES",
      "BLUEBERRIES",
    ],
    source: "https://en.wikipedia.org/wiki/Breakfast_by_country#Continental_breakfast",
  },

  // Fast Food Chains | 105
  {
    id: 105,
    name: "Fast Food Chains",
    nameAsRule: "Your password must be a major fast food chain",
    failedMessage: "[PASS] is not in the top 50 fast food chains.",
    hint: "Top 50 globally, by number of locations.",
    possible: [
      // United States
      "MCDONALD'S",
      "STARBUCKS",
      "SUBWAY",
      "KFC",
      "DOMINO'S",
      "BURGER KING",
      "PIZZA HUT",
      "DUNKIN'",
      "KRISPY KREME",
      "HUNT BROTHERS",
      "TACO BELL",
      "BASKIN-ROBBINS",
      "WENDY'S",
      "DAIRY QUEEN",
      "PAPA JOHN'S",
      "LITTLE CAESARS",
      "CARL'S JR",
      "HARDEE'S",
      "POPEYES",
      "SONIC DRIVE-IN",
      "ARBY'S",
      "CHIPOTLE",
      "CHICK-FIL-A",
      "JIMMY JOHN'S",
      "JERSEY MIKE'S",
      "JACK IN THE BOX",
      "PANDA EXPRESS",
      "PANERA BREAD",
      "EINSTEIN BROS",
      "AUNTIE ANNE'S",
      "CHESTER'S",
      "IHOP",
      "CHURCH'S",
      "MOS",
      "APPLEBEE'S",

      // China
      "MIXUE",
      "LUCKIN",
      "WALLACE",
      "COTTI",
      "GOOD ME",
      "AUNTEA JENNY",
      "CHAPANDA",
      "TASTIEN",
      "CHAGEE",
      "HEY TEA",
      "DICOS",
      "PALA",
      "MI BIBIMBAP",

      // Canada
      "TIM HORTONS",

      // United Kingdom
      "COSTA",
      "GREGGS",

      // Philippines
      "JOLLIBEE",
    ],
    source: "https://en.wikipedia.org/wiki/List_of_the_largest_fast_food_restaurant_chains",
  },

  // Wine Varietals | 106
  {
    id: 106,
    name: "Wine",
    nameAsRule: "Your password must be a type of wine",
    failedMessage: "[PASS] is not a wine varietal.",
    hint: "Looking for wine grape varietals.",
    possible: [
      // Noble grapes (classic international varietals)
      "CHARDONNAY",
      "CABERNET SAUVIGNON",
      "PINOT NOIR",
      "MERLOT",
      "RIESLING",
      "SAUVIGNON BLANC",

      // Other major international varietals
      "PINOT GRIGIO",
      "PINOT GRIS",
      "SYRAH",
      "SHIRAZ",
      "TEMPRANILLO",
      "SANGIOVESE",
      "CHENIN BLANC",
      "GEWÜRZTRAMINER",
      "VIOGNIER",
      "NEBBIOLO",
      "BARBERA",
      "GRENACHE",
      "MOURVÈDRE",
      "PETIT VERDOT",
      "MALBEC",
      "CABERNET FRANC",
      "PINOT BLANC",
      "SÉMILLON",
      "MUSCAT",
      "MOSCATO",

      // Spanish varietals
      "ALBARIÑO",
      "VERDEJO",
      "GARNACHA",
      "MONASTRELL",
      "BOBAL",
      "MENCÍA",
      "GODELLO",

      // Italian varietals
      "TREBBIANO",
      "CHIANTI",
      "DOLCETTO",
      "ARNEIS",
      "FIANO",
      "FALANGHINA",
      "NERO D'AVOLA",
      "PRIMITIVO",
      "AGLIANICO",
      "MONTEPULCIANO",
      "VERDICCHIO",
      "GRECO",
      "CORTESE",
      "FREISA",
      "BRACHETTO",
      "BRUNELLO",
      "CORVINA",
      "RONDINELLA",
      "GRIGNOLINO",
      "PELAVERGA",
      "CILIEGIOLO",
      "COLORINO",
      "CANAIOLO",

      // German/Austrian varietals
      "GRÜNER VELTLINER",
      "MÜLLER-THURGAU",
      "SILVANER",
      "KERNER",
      "SCHEUREBE",
      "ZWEIGELT",
      "BLAUFRÄNKISCH",
      "ST. LAURENT",

      // Loire varietals
      "MUSCADET",
      "MELON DE BOURGOGNE",
      "ALIGOTÉ",
      "GAMAY",

      // Rhône varietals
      "MARSANNE",
      "ROUSSANNE",
      "CINSAUT",

      // Bordeaux varietals
      "MUSCADELLE",

      // Portuguese varietals
      "TOURIGA NACIONAL",
      "TOURIGA FRANCA",
      "TINTA RORIZ",
      "TINTA BARROCA",
      "VINHO VERDE",
      "ARINTO",
      "LOUREIRO",
      "ALVARINHO",

      // Other European varietals
      "ASSYRTIKO",
      "XINOMAVRO",
      "AGIORGITIKO",
      "RODITIS",
      "SAVATIANO",
      "FURMINT",
      "HÁRSLEVELŰ",
      "KADARKA",
      "FETEASCĂ NEAGRĂ",
      "FETEASCĂ ALBĂ",
      "WELSCHRIESLING",
      "ZIERFANDLER",
      "ROTGIPFLER",
    ],
    source: "https://en.wikipedia.org/wiki/List_of_grape_varieties",
  },

  // Hat Styles | 108
  {
    id: 108,
    name: "Hat",
    nameAsRule: "Your password must be a hat",
    failedMessage: "[PASS] is not a style of hat.",
    hint: "Hat styles, ignoring the word 'hat' or 'cap'",
    possible: [
      "AKUBRA",
      "ASCOT",
      "BALMORAL",
      "BASEBALL",
      "BEANIE",
      "BERET",
      "BICORNE",
      "BOATER",
      "BONNET",
      "BOWLER",
      "BUCKET",
      "BUSBY",
      "CAMPAIGN",
      "CLOCHE",
      "COONSKIN",
      "COWBOY",
      "DERBY",
      "FASCINATOR",
      "FEDORA",
      "FEZ",
      "FLAT",
      "GATSBY",
      "HARD",
      "HOMBURG",
      "KEPI",
      "MORTARBOARD",
      "NEWSBOY",
      "PANAMA",
      "PEAKED",
      "PILLBOX",
      "PITH",
      "PORKPIE",
      "SAILOR",
      "SHAKO",
      "SOMBRERO",
      "STETSON",
      "SUN",
      "TAM",
      "TOP",
      "TRILBY",
      "TRUCKER",
      "TURBAN",
      "TYROLEAN",
      "USHANKA",
      "VISOR",
      "WIZARD",
    ],
    source: "https://en.wikipedia.org/wiki/List_of_hat_styles",
  },
];
